### PR TITLE
Update BLT to v0.4.1

### PR DESCRIPTION
**Pull request by davidbeckingsale**
# Summary

- This PR updates BLT to v0.4.1

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
Thanks @davidbeckingsale

**Review by rhornung67 — APPROVED** [review]

**Review by rhornung67 — DISMISSED** [review]

**Comment by rhornung67** [comment]
@davidbeckingsale if/when this comes back green, is it good to merge?

**Comment by davidbeckingsale** [comment]
Yup!

**Comment by rhornung67** [comment]
@davidbeckingsale any idea what's going on with the gitlab ci?

**Comment by rhornung67** [comment]
@davidbeckingsale is there a way to kickstart gitlab to run ci on this?

**Comment by rhornung67** [comment]
@mdavis36 something is not right with our azure testing. This PR is an example of things that started going haywire yesterday. do you know what's going on?

**Review by rhornung67 — APPROVED** [review]

**Pull request merged**
