### PR TITLE
Add mailing list link to README

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by rhornung67** [comment]
The link to the email list should be moved down and worked into the last paragraph before the Release information

**Comment by davidbeckingsale** [comment]
Perhaps. Although having it near the top makes people less likely to miss it.

**Comment by rhornung67** [comment]
Move the paragraph up?

**Comment by keasler** [comment]
I'm good with the current location.  It looks 'friendly'.

**Comment by davidbeckingsale** [comment]
@rhornung67 does this look better? All the info regarding contributing has been moved up to the "Documentation" section.

**Comment by davidbeckingsale** [comment]
Let's take a quick vote (add your reactions):

- 398c96e ( 👍 )
or
- 1e42eb3 ( 👎 )

@keasler @ajkunen @DavidPoliakoff @tgamblin @trws @rhornung67

**Comment by davidbeckingsale** [comment]
Reverted to the "friendly" location. Can someone approve this for merging?

**Comment by keasler** [comment]
I'm good with this organization and the other one you tried.

**Pull request merged**
