### PR TITLE
Updating name of clang-ibm specs

### PR DESCRIPTION
**Pull request by kab163**
# Summary

- This PR is a bugfix
- It fixes how the clang-ibm jobs are called for the Lassen CI. With this fix, spack will find the right version of clang-ibm.

### CODE REVIEW

**Comment by rhornung67** [comment]
@kab163 any updates on this from Greg B?

**Comment by kab163** [comment]
> @kab163 any updates on this from Greg B?

Not since his email a while back (subject is "clang vs. clang-ibm", you are cc'd). What should we do? It may be a wont-fix problem, and if that's the case, then something like "clang@9-ibm" would work (I think that was the old fix).

**Comment by rhornung67** [comment]
If something like 'clang@9-ibm' works, let's go with that for now.

**Comment by rhornung67** [comment]
@kab163 looking through the Gitlab CI logs here, it looks like the lassen jobs are building, but not running any tests. Any ideas?

**Comment by kab163** [comment]
May need to change this to "clang@ibm.9.0.0" in this PR and radiuss config files.

**Comment by davidbeckingsale** [comment]
Looks good - hopefully the CI passes 😄

**Comment by kab163** [comment]
@rhornung67 This is ready to be merged!

**Review by rhornung67 — APPROVED** [review]

**Pull request merged**
