### PR TITLE
Add "threshold" for codecov

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@rhornung67 - there are examples of both, and the docs say it should be a "number"

**Comment by rhornung67** [comment]
@davidbeckingsale OK. I this passes checks, I will approve.

**Comment by davidbeckingsale** [comment]
🙏

**Comment by davidbeckingsale** [comment]
Magic! I don't think having 3 digits after the decimal place is helpful.

**Pull request merged**
