### PR TITLE
Bump BLT to v0.3.6

### PR DESCRIPTION
**Pull request by davidbeckingsale**
# Summary

- Update BLT to v0.3.6
- Update camp master to #eb555ee

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@trws - can you peek at the Appveyor failure? I think we might need to switch Visual Studio version or something...

**Comment by trws** [comment]
That is a strange failure, it must be claiming to have support for it despite not having support for it.  I think we need two things here, one is to add an MSVC version check, will have to work out what the min is for type_pack_element, and also probably update MSVC since we haven't for quite a while.  Maybe ask some of the app folks what they're currently targeting?

**Comment by davidbeckingsale** [comment]
Okay, I'll check in with apps teams. The appveyor configs are identical between camp and RAJA (which makes me nervous)

**Comment by rhornung67** [comment]
> Okay, I'll check in with apps teams. The appveyor configs are identical between camp and RAJA (which makes me nervous)

I just sent a teams message to alan asking what they use for his code. They're the most important RAJA windows user.

**Comment by davidbeckingsale** [comment]
> I just sent a teams message to alan asking what they use for his code. They're the most important RAJA windows user.

Thanks! That's who I was going to ask.

**Comment by trws** [comment]
Something stranger is going on here, when I test it on godbolt the __type_pack_element code never gets activated because the __has_builtin check doesn't work right in these versions of MSVC, I'm having a heck of a time reproducing this.  The check clearly needs to be made more specific, so I'm working on that, but it weirds me out to no end that I'm getting different behavior over there.

**Comment by trws** [comment]
On Tue, 28. Jul 15:04, David Beckingsale wrote:
>> I just sent a teams message to alan asking what they use for his code. They're the most important RAJA windows user.
>
>Thanks! That's who I was going to ask.

Any word back on this?

**Comment by rhornung67** [comment]
@trws Sorry about not keeping folks in the loop here. I discussed the Windows stuff with David on MS Teams.  Here's the gist: 

They don't yet have a working CUDA build on Windows yet. Someone is working for that. There is desire on the project to use MSVC for development, but they currently use Visual Studio 2017 to drive Intel 19.

**Comment by trws** [comment]
Interesting, alright.  For camp I added VS 2017 in addition to VS 2015, we
should probably do that here as well, but it would be good to know if we still
need 2015 in there.  I was impressed by 2017 FWIW, the compile and test cycle
completes in a third of the time it took for the 2015 version.  Not at all bad.

**Comment by rhornung67** [comment]
I don't think we need VS 2015.

**Comment by davidbeckingsale** [comment]
@trws - do you mind if I update the RAJA hip docker image?

**Comment by trws** [comment]
Not a bit. Mind if I add a quick commit here to up the MSVC version on appveyor?

**Comment by davidbeckingsale** [comment]
No problem, go ahead.

**Comment by trws** [comment]
I misspoke before, it was 2017 and 2019, that being the case I added 2019 but have not removed 2017.

**Comment by davidbeckingsale** [comment]
Hopefully this will all pass 😄

**Comment by rhornung67** [comment]
> Hopefully this will all pass 😄

🤞

**Comment by trws** [comment]
Well... that's disturbing, we have a failure on 2019 with the staticlayout expansion.  I'll dig into that.

**Comment by davidbeckingsale** [comment]
Is everyone okay if we remove 2019 for now to get this merged (since the BLT and camp changes are required for HIP)? @rhornung67 @trws

**Comment by rhornung67** [comment]
I'm OK with removing 2019.

**Comment by trws** [comment]
Go ahead, I'll make a separate PR for it.

**Comment by MrBurmark** [comment]
Bumping up camp breaks some cuda tests at runtime due to the camp cuda resource constructor not initializing device.

**Comment by davidbeckingsale** [comment]
@rhornung67 - this is ready to go as soon as CI passes.

**Pull request merged**
