### PR TITLE
Adding Coverity badge

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by keasler** [comment]
Is this pull-request active?  @DavidPoliakoff, @rhornung67, @trws  might have an opinion.

**Comment by davidbeckingsale** [comment]
Yes. Why are you commenting on every PR like this?

**Comment by keasler** [comment]
Just checking.  The one-liner especially seemed a simple change.

We need to have a short RAJA meeting, and I’m wondering if the first thing we should do is just get a status update on the open pull requests.  I know I want to discuss a few points about the BoxSegment pull-request before I merge it, which is why I need a “quick” meeting.

-Jeff

**Comment by davidbeckingsale** [comment]
No problem. I have left this unmerged because I haven't managed to get the static analysis from Coverity working yet.

---
David Beckingsale, david@llnl.gov, people.llnl.gov/david <http://people.llnl.gov/david>
Center for Applied Scientific Computing @ Lawrence Livermore National Laboratory

**Pull request closed without merging**
