### PR TITLE
Fixes for compilation with Intel

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by willkill07** [comment]
That cursed `Cilk` typo.

Out of curiosity, what was wrong with the `cilk_for` under type traits?

**Comment by davidbeckingsale** [comment]
`cilk_for` is a cilk function!

**Comment by DavidPoliakoff** [comment]
If you check this https://github.com/travis-ci/travis-ci/issues/4604

Apparently Jeff and somebody who uses Travis have gotten stuff set up such that (public) Intel compilers can be used in Travis.

Note: using this post to say I'm volunteering to attempt to make that work would violate the Geneva Convention

**Comment by davidbeckingsale** [comment]
@DavidPoliakoff Looks good but we would have to figure out what license key was okay to use...

**Comment by davidbeckingsale** [comment]
I just emailed @tgamblin about this 😄

**Comment by DavidPoliakoff** [comment]
I know you can encrypt things you provide to Travis... don't know if that would make our lives easier, haven't really had a time to look through the technical parts of how the Travis Intel script works.

**Comment by davidbeckingsale** [comment]
The thing I'm unsure about is whether we have a license key, or a license server that sends out the floating licenses on demand.

**Comment by tgamblin** [comment]
Adding @lee218llnl

**Comment by DavidPoliakoff** [comment]
Ohhhhh, right. My bad.

Can Travis instances call out? If we could figure out their IP, getting an exception for them to hit only the Intel license server sounds like a real pain, but maybe maybe okay?

**Comment by davidbeckingsale** [comment]
That would probably be too much. If we have a license key we can encrypt then I think this is viable. Else we have to just get this set up in Bamboo.

**Comment by DavidPoliakoff** [comment]
Yeah, honestly that's probably the _easiest_ path, it would just be nice to have this in Travis with all that niceness.

**Comment by tgamblin** [comment]
I heard someone say that Intel might one day allow their compilers to be used for open source testing without the need to pay for it.  Is that true?  Maybe @jeffhammond knows.  Must we pay intel to make their compilers look good?

**Comment by jeffhammond** [comment]
See https://github.com/nemequ/icc-travis and https://software.intel.com/en-us/qualify-for-free-software.  Write me email at my work address to continue discussion.

**Comment by jeffhammond** [comment]
If you dislike Cilk, `-no-intel-extensions` disables it.

**Comment by DavidPoliakoff** [comment]
Theoretically we support Cilk, disabling it would be poor form. Thanks for the help!

**Comment by davidbeckingsale** [comment]
I'm not sure we can use the open-source version:

> I will not be compensated in any form for applications developed or maintained with Intel® Software Development Products under the terms of the non-commercial license.

**Comment by jeffhammond** [comment]
I use my own license via secure environment variables for Travis testing.

Like I said, I'll be happy to discuss in more detail over email. I rarely disappoint.

**Comment by willkill07** [comment]
@davidbeckingsale and @DavidPoliakoff: PolyBench/RAJA had travis-icc unit tests in a prior commit 

what @jeffhammond linked to was exactly the process I used.

**Pull request merged**
