### PR TITLE
Update hip launch wrapper

### PR DESCRIPTION
**Pull request by MrBurmark**
Update hip launch wrapper and use consistently when launching kernels in hip backend.

# Summary

- This PR is a refactoring
- It does the following:
  - Modifies/refactors hip kernel launches

### CODE REVIEW

**Review by artv3 — DISMISSED** [review]
Is this similar to how its done with CUDA?

**Comment by MrBurmark** [comment]
The main change here is to bring this in line with the cuda backend where all kernel launches go through a single function. But this also changes the function signature a little bit to use the hip launch kernel GGL function. The difference is the use of a parameter pack instead of an array of void pointers. I prefer the way this looks over the cuda version. We should think about how we want to handle object lifetimes. I'm not sure of using hipLaunchKernelGGL here causes an extra copy of the objects or not.

**Review by rhornung67 — APPROVED** [review]

**Review by mdavis36 — DISMISSED** [review]

**Comment by MrBurmark** [comment]
I checked and the GGL launch version does make an extra copy of the arguments to I'm reverting back to the pointer to args launch function.

**Comment by rhornung67** [comment]
> I checked and the GGL launch version does make an extra copy of the arguments to I'm reverting back to the pointer to args launch function.

Good to know. Thanks! 👍

**Review by rhornung67 — APPROVED** [review]

**Review by willkill07 — APPROVED** [review]

**Pull request merged**
