### PR TITLE
travis: login to docker as rajaci user to up cap

### PR DESCRIPTION
**Pull request by trws**
Use the new raja user to login and double the rate cap for docker image fetches.

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]

**Comment by rhornung67** [comment]
LGTM

**Comment by rhornung67** [comment]
@trws the raja-admin@llnl.gov email list is now active. If this PR changes anything for us to run Travis CI, please let us know.

**Comment by trws** [comment]
I'm working on updating the email address, but it shouldn't change anything for the way the tests are run.

**Comment by rhornung67** [comment]
LGTM

**Comment by rhornung67** [comment]
LGTM

**Comment by rhornung67** [comment]
@davidbeckingsale @trws I merged in the latest develop changes and kicked off Gitlab CI. I believe this can be merged when checks pass, correct?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale @trws I merged in the latest develop changes and kicked off Gitlab CI. I believe this can be merged when checks pass, correct?

Yup, I believe so. Looks like Travis failed though :(

**Comment by rhornung67** [comment]
For some reason the clang9 check timed out after about 28 minutes. I restarted it.

**Comment by rhornung67** [comment]
@davidbeckingsale this is all green. should I merge it so we can move on to other prs?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale this is all green. should I merge it so we can move on to other prs?

Sure thing!

**Comment by trws** [comment]
Thanks for pushing this through! Especially for doing so when I wasn't
in a position to respond.

**Pull request merged**
