### PR TITLE
Simplify header names

### PR DESCRIPTION
**Pull request by willkill07**
`RAJA/policy/openmp/forall_openmp.hpp` has duplicate information. This PR proposes removing all `_<policy>` tags from the end of all headers found within a given policy.

This PR also fixes the Cilk includes.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
We talked about this, and decided that it is risky due to people being over zealous with includes - unique names are probably best.

**Comment by willkill07** [comment]
I really don't see how users could possibly misinterpret an include path.

Mandating that a user type the execution policy twice doesn't make any sense.

**Comment by DavidPoliakoff** [comment]
The problem is that bad developers will have -I<RAJA_DIR>/policy/openmp on their build lines.

Apparently firing these developers out of a very powerful cannon aimed at the sun isn't an option (I forget who brought that solution up (it was me...))

 I'm right there with you on this one.

**Comment by trws** [comment]
Every large c++ project I can think of would suffer from this problem if someone were so incredibly stupid as to do that. If they do, they get what they deserve.

The solve is to just include policy/openmp.hpp which is easier, shorter, and has the benefit of being correct.

Why is this an issue?


---
Sent from VMware Boxer

On April 28, 2017 at 7:33:19 AM PDT, David Poliakoff <notifications@github.com> wrote:

The problem is that bad developers will have -I<RAJA_DIR>/policy/openmp on their build lines.

Apparently firing these developers out of a very powerful cannon aimed at the sun isn't an option (I forget who brought that solution up (it was me...))

I'm right there with you on this one.

**Comment by rhornung67** [comment]
Actually, I like Tom's suggestion if I'm interpreting it correctly.  Have a policy directory with a single header file for each programming model that users include (e.g., policy/openmp.hpp, policy/cuda.hpp, etc.) and then have those headers include the appropriate internal header files that we can organize and name in a way that makes sense to us and which is not exposed to apps. unless they're doing something funky.

**Comment by trws** [comment]
David already did it I think, but yes that's what I meant.


---
Sent from VMware Boxer

On April 28, 2017 at 10:16:00 AM PDT, rhornung67 <notifications@github.com> wrote:

Actually, I like Tom's suggestion if I'm interpreting it correctly. Have a policy directory with a single header file for each programming model that users include (e.g., policy/openmp.hpp, policy/cuda.hpp, etc.) and then have those headers include the appropriate internal header files that we can organize and name in a way that makes sense to us and which is not exposed to apps. unless they're doing something funky.

**Comment by DavidPoliakoff** [comment]
Will did it, but I'll take the credit until it breaks something. I think somebody rejected this idea at the RAJA meeting, I still like it

**Comment by trws** [comment]
Apologies for my unnecessarily combative tone earlier, but are there any arguments as to why this shouldn't be merged?

As it is, every backend and component of each backend should be accessible for include by `policy/<backend>.hpp` or `policy/<backend>/<component>.hpp`.

**Comment by davidbeckingsale** [comment]
My header refactor made the `policy/<backend>.hpp` include work, and that is what a user would include. I don't mind the duplicate naming for components inside the `<backend>` directory, but since they are "internal" only, what's the downside to the unique names?

The only reason I said we shouldn't merge this is because it explicitly came up at the meeting and we decided not to (otherwise I would have changed the names already).

**Comment by trws** [comment]
They are internal, but potentially usable from outside if say someone wants everything but foralln, or everything but scan.  They're also inconsistent in their capitalization.  It's not a critical thing, clearly, but it seemed to follow logically with the other reorganization and cleanup.

**Comment by willkill07** [comment]
> Since they are "internal" only, what's the downside to the unique names?

It's name bloat. Example: in OpenMP scan the following header is required:

`#include <RAJA/policy/sequential/scan_sequential.hpp>`

The `_sequential` suffix is completely superfluous because (1) it doesn't provide any additional feature and (2) requires developers/maintainers to duplicate already known information.

This is also inconsistent with other components of RAJA, namely the forallN machinery. If we wanted similar consistency, then `tile.hpp` should be called `tile_forallN.hpp` and `permute.hpp` should be called `permute_forallN.hpp`.

I am personally advocating simple, effective names which describe the components specified in a header file. The include path is (arguably) part of a header name -- a header file name doesn't necessarily need to stand on it's own. This can be observed in the [`range-v3`](https://github.com/ericniebler/range-v3) repository (specifically `range/v3/algorithm/for_each.hpp` vs. `range/v3/view/for_each.hpp`).

**Comment by davidbeckingsale** [comment]
Fair comments. Fix up the cuda stuff and then let's merge this.

**Comment by willkill07** [comment]
This should be good to go.

**Comment by davidbeckingsale** [comment]
Yup, but did you test the CUDA build? I haven't yet...

**Comment by willkill07** [comment]
I had to add a `vector` include but otherwise, yes, the tests passed on my machine with NVCC. Commit incoming.

**Comment by willkill07** [comment]
```
Test project /home/wkillian/RAJA/build
      Start  1: layout-test.exe
 1/19 Test  #1: layout-test.exe ..................   Passed    0.00 sec
      Start  2: timer-test.exe
 2/19 Test  #2: timer-test.exe ...................   Passed    2.00 sec
      Start  3: multipolicy.exe
 3/19 Test  #3: multipolicy.exe ..................   Passed    0.01 sec
      Start  4: CPUreduce-test.exe
 4/19 Test  #4: CPUreduce-test.exe ...............   Passed    0.54 sec
      Start  5: CPUnested-test.exe
 5/19 Test  #5: CPUnested-test.exe ...............   Passed    0.03 sec
      Start  6: CPUnested_reduce-test.exe
 6/19 Test  #6: CPUnested_reduce-test.exe ........   Passed    0.01 sec
      Start  7: indexset-tests.exe
 7/19 Test  #7: indexset-tests.exe ...............   Passed    0.50 sec
      Start  8: reduction-tests.exe
 8/19 Test  #8: reduction-tests.exe ..............   Passed    0.02 sec
      Start  9: scan-tests.exe
 9/19 Test  #9: scan-tests.exe ...................   Passed    0.02 sec
      Start 10: forall-tests.exe
10/19 Test #10: forall-tests.exe .................   Passed    0.49 sec
      Start 11: reducemin.exe
11/19 Test #11: reducemin.exe ....................   Passed    1.12 sec
      Start 12: reducemax.exe
12/19 Test #12: reducemax.exe ....................   Passed    1.09 sec
      Start 13: reducesum.exe
13/19 Test #13: reducesum.exe ....................   Passed    3.67 sec
      Start 14: traversal.exe
14/19 Test #14: traversal.exe ....................   Passed    0.45 sec
      Start 15: nested.exe
15/19 Test #15: nested.exe .......................   Passed    1.51 sec
      Start 16: reduceminloc.exe
16/19 Test #16: reduceminloc.exe .................   Passed    1.69 sec
      Start 17: reducemaxloc.exe
17/19 Test #17: reducemaxloc.exe .................   Passed    1.82 sec
      Start 18: forallN.exe
18/19 Test #18: forallN.exe ......................   Passed    0.83 sec
      Start 19: scan.exe
19/19 Test #19: scan.exe .........................   Passed    3.99 sec
```

**Comment by davidbeckingsale** [comment]
Okay, sounds good!

**Pull request merged**
