### PR TITLE
found a bug in nested for all

### PR DESCRIPTION
**Pull request by artv3**

### CODE REVIEW

**Comment by ajkunen** [comment]
@artv3 thanks for making a unit-test reproducer. I'll try and tack a whack at that when I have a moment to breathe.

**Comment by artv3** [comment]
@ajkunen I am a bit confused my test didn't fail the tests...

**Comment by ajkunen** [comment]
@artv3 The nvcc tests will pass because they only build the code.  Travis CI cannot run them (no GPU's)

**Comment by ajkunen** [comment]
Ok, I fixed some issues in the policies.  I think it all works now.  That unit tests pass (I fixed the closed form of the sum since it was wrong).

@artv3  Please try this again, and let me know if it works for you

**Comment by artv3** [comment]
Thanks @ajkunen, it works now. Can we merge so I can update the user-docs branch?

**Comment by artv3** [comment]
@ajkunen :-)

**Pull request merged**
