### PR TITLE
Task/add xl cuda ci jobs

### PR DESCRIPTION
**Pull request by kab163**
# Summary

- This PR is improving the gitlab CI  by adding XL+CUDA jobs

**To discuss:**
- [ ] Figuring out PGI:
  - Tried to add a PGI job to Lassen, but when it ran with OpenMP (as it does by default), I got an 'illegal type conversion' error on a OpenMP header file. (https://lc.llnl.gov/gitlab/radiuss/RAJA/-/jobs/162416) When turning OFF OpenMP, I got a new error:
"/g/g0/belcher6/RAJA/tpl/camp/include/camp/tuple.hpp", line 110: error: cannot
          overload functions distinguished by return type alone
      CAMP_HOST_DEVICE CAMP_CONSTEXPR14 Type& get_inner() noexcept { return val; }
  - Is adding PGI tests needed? If so, how do we solve those errors?
- [x] XL+CUDA seems to still go over the 45 minute mark (I thought PR #955 solved it?)
  - Rich is looking in to a subset of tests to run with XL+CUDA that will cut down link time - TBD

Note:

Passing gitlab CI test suite is now ***REQUIRED*** to get your PR merged.
You can initiate the gitlab CI test suite by simply commenting on your PR 
after creation with something as simple as "LGTM".

### CODE REVIEW

**Comment by kab163** [comment]
LGTM

**Comment by kab163** [comment]
LGTM

**Review by rhornung67 — DISMISSED** [review]
This looks like a good place to start.

**Comment by kab163** [comment]
LGTM

**Comment by kab163** [comment]
> This looks like a good place to start.

Cool! Also, I can make these as "allow failure" for now if they still time out

**Comment by rhornung67** [comment]
> > This looks like a good place to start.
> 
> Cool! Also, I can make these as "allow failure" for now if they still time out

If they do time out, there's something amiss. I build RAJA with xl+nvcc regularly. Is the duration of the allocation set in Gitlab or in a script someplace?

**Comment by kab163** [comment]
> > > This looks like a good place to start.
> > 
> > 
> > Cool! Also, I can make these as "allow failure" for now if they still time out
> 
> If they do time out, there's something amiss. I build RAJA with xl+nvcc regularly. Is the duration of the allocation set in Gitlab or in a script someplace?

In a script (see https://github.com/LLNL/RAJA/blob/bbb70974735061c88b7e5f7c2915699e8f2a96e0/.gitlab-ci.yml#L75). I can modify the time by modifying that "DEFAULT_TIME" variable in the xl+cuda spec

**Comment by rhornung67** [comment]
60 minutes should be plenty for these. Let's let that ride for a while.

**Comment by kab163** [comment]
Currently, builds for xl+cuda work, but right at 100% built there is an error:
`WARNING: junit.xml: no matching files              
ERROR: No files to upload  `

**Review by rhornung67 — DISMISSED** [review]

**Comment by rhornung67** [comment]
@kab163 is this PR good to merge?  Please resolve the merge conflict and I will approve so we can get it in.

**Comment by kab163** [comment]
> @kab163 is this PR good to merge? Please resolve the merge conflict and I will approve so we can get it in.

Yes, assuming I resolved the merge conflict correctly, it should be good to merge. I think the tests are still set to allow failure since the XL+cuda just takes too long to finish building and run all the tests.

**Comment by rhornung67** [comment]
@kab163 in a meeting now. Tomorrow morning, I'll poke around in the CI stuff and see if tweaking the allocation time for these can make them pass.

**Review by rhornung67 — APPROVED** [review]

**Comment by rhornung67** [comment]
@davidbeckingsale @MrBurmark are you OK with merging this. The XL+CUDA tests don't complete within the 60 minute allocation and so are allowed to fail. Should we leave it that way? I can try bumping the allocation time for those builds and see if we can get the tests to pass.  However, this seems like a continual moving target since the XL compiler is a piece of crap.

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale @MrBurmark are you OK with merging this. The XL+CUDA tests don't complete within the 60 minute allocation and so are allowed to fail. Should we leave it that way? I can try bumping the allocation time for those builds and see if we can get the tests to pass. However, this seems like a continual moving target since the XL compiler is a piece of crap.

Fine with me.

**Review by davidbeckingsale — APPROVED** [review]

**Comment by rhornung67** [comment]
@davidbeckingsale fine with leaving it fail or bumping t he time?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale fine with leaving it fail or bumping t he time?

The allowed failure. We could potentially add something that catches the timeout and marks it as "passing", and then make the job required so that any true compilation issues would trigger a failure.

**Pull request merged**
