### PR TITLE
forceinline recursive

### PR DESCRIPTION
**Pull request by artv3**
Codes like SW4-lite can add the Intel compiler directive #pragma forceinline recursive prior to nested regions

`#pragma forceinline recursive`
  `RAJA::forall<POL2>(k_range, [=] (int k){`
        `RAJA::forall<POL1>(j_range, [=] (int j){`
              `RAJA::forall<RAJA::simd_exec>(i_range, [=] (int i){`

to help vectorize (more specifically this helps simd_exec not loop_exec). Post my work with SW4,  I had suggested adding the directive prior to RAJA calls ( I believe there are examples of codes that add this directive prior to RAJA methods). From recent conversations, I am wondering if this should be part of the simd policy or if it should be a user specified directive? 

Pros: Code runs faster, pragma hidden in policy.  

Cons: Longer compile times. May not be needed in all cases.

### CODE REVIEW

**Comment by ajkunen** [comment]
I don't think we want simd_exec to control if "forceinline recursive" is used.  It also makes sense for loop_exec, and any other policy.

In our code, we're applying this pragma before every call to RAJA::kernel.  We rarely use simd_exec, but we see a large performance improvement anyways.  We also don't see a noticeable increase in compile time, but we do see a _very_ large increase in compile time when using the inline cutoff command-line flags. 

I would be a proponent of trying out "forceinline recursive" at the top-level of the forall/kernel API.

**Comment by rhornung67** [comment]
@ajkunen trying out forceinline recursive at the top level of forall/kernel is a good idea.  Any good ideas about making sure the intel compiler doesn't barf on this? It's not clear to me that we have enough coverage in the unit tests for this.

**Comment by artv3** [comment]
@ajkunen , @trws , @davidbeckingsale , @rhornung67 , I introduced a new macro RAJA_FORCEINLINE_RECURSIVE and an option in CMAKE to add/remove the directive. This also allows the SW4-kernel to realize the performance previously observed.

**Comment by artv3** [comment]
@ajkunen , I was wondering if you could checkout this branch and let me know if this is along the lines of what we wanted to do. In particular, the force-inline recursive pragma is only invoked with kernel.

**Pull request closed without merging**
