### PR TITLE
Docs for RAJA team loops

### PR DESCRIPTION
**Pull request by artv3**
# Summary

- This PR starts sketching out documentation for RAJA Team loops.
- Very much a work in progress, but the PR creates a space to start discussion. 

Link to read the docs: 
https://raja.readthedocs.io/en/docs-artv3-raja-teams/

### CODE REVIEW

**Comment by artv3** [comment]
@rhornung67 , I've started sketching out an introduction to RAJA team loops under "Elements of Loop Execution" (https://raja.readthedocs.io/en/docs-artv3-raja-teams/feature/loop_basic.html) . I haven't added a discussion of an example yet (we can use the examples from https://github.com/LLNL/RAJA/pull/928 or I can add a simpler one here) but I was wondering if this would be a good way to start introducing the material?

**Comment by artv3** [comment]
Folks I pushed tut_teams_basic.cpp to help illustrate similarities between writing nested loops in C/CUDA/and Teams. If you guys have a second, please let me know if this is helpful.

**Comment by artv3** [comment]
Once we merge in https://github.com/LLNL/RAJA/pull/935 I was thinking of adding additional examples.

**Review by rhornung67 — APPROVED** [review]
@artv3 looks good. I took an edit pass through this and fixed typos and made some minor working changes.

**Comment by artv3** [comment]
LGTM

**Pull request merged**
