### PR TITLE
Enable RAJA Teams to run on CAMP default resource

### PR DESCRIPTION
**Pull request by artv3**
# Summary

This PR modifies kernel launches on Teams so they may run on the CAMP default stream.

Future work will expand the interface to users may pass in a resource object.

### CODE REVIEW

**Comment by artv3** [comment]
HIP is failing on gitlab, but I believe that is a known issue.

**Review by MrBurmark — APPROVED** [review]

**Comment by artv3** [comment]
Hey... I got a failure with this test: 

`	 67 - test-forall-segment-multiple-ReduceMinLoc-Hip.exe (Failed)` 

Which was not modified within this PR.

**Comment by rhornung67** [comment]
@artv3 I was playing around on corona yesterday and I noticed that that failed sometimes, but not always. @rchen20 do you have any ideas about this?

**Comment by rchen20** [comment]
> @artv3 I was playing around on corona yesterday and I noticed that that failed sometimes, but not always. @rchen20 do you have any ideas about this?

When I ran in to this error with XLC, it was just due to some of the C++ flags not being passed in properly to the compiler. However, I'm not seeing that here, and I cannot seem to reproduce the error on corona . . .

**Comment by rhornung67** [comment]
@rchen20 yeah, it's weird. It's only that test and it fails intermittently.

**Comment by rhornung67** [comment]
@artv3 try restarting the Gitlab CI jobs that failed. It may pass on another try.

**Comment by rchen20** [comment]
These flags should be used with gcc (`-finline-functions -finline-limit=20000`), which are not set in .gitlab/corona-jobs.yml. I'll push this update now and we can re-run.

**Comment by artv3** [comment]
> These flags should be used with gcc (`-finline-functions -finline-limit=20000`), which are not set in .gitlab/corona-jobs.yml. I'll push this update now and we can re-run.

Thanks!

**Comment by artv3** [comment]
@davidbeckingsale we seem to have some permission issues? The gitlab testing  framework reports the following error for HIP: 
`su: warning: cannot change directory to /g/g92/ukbeck: Permission denied`

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale we seem to have some permission issues? The gitlab testing framework reports the following error for HIP:
> `su: warning: cannot change directory to /g/g92/ukbeck: Permission denied`

Looking into it, not sure what's going on.

**Comment by artv3** [comment]
Can I get a re-approval on this PR?

**Review by mdavis36 — APPROVED** [review]

**Comment by mdavis36** [comment]
@davidbeckingsale the gitlab `gcc_8_3_1_cuda` test failed and fails each time I try to restart it, any ideas?

**Comment by artv3** [comment]
Did anyone else want to review? Or am I good to merge ?

**Review by rhornung67 — APPROVED** [review]

**Pull request merged**
