### PR TITLE
Make targets for test directories

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary

Add make targets for testing subdirectories via macros raja_add_test_subdirectory and raja_add_test.
This makes it easy to build only a subset of the tests which makes iterating on something faster as modifying any of our headers causes all of the tests and examples to be rebuilt.

- This PR is a feature
- It does the following:
  - Adds make targets for each test directory

### CODE REVIEW

**Comment by MrBurmark** [comment]
@rchen20 pointed out that I could cd into the build/test directory and run make there to only make the tests.
It doesn't appear that cding further into say the unit test directory allows you to run make there however.
I was about to close this PR, but I would still like to be able to build subsets of the tests.

**Comment by gzagaris** [comment]
> @rchen20 pointed out that I could cd into the build/test directory and run make there to only make the tests.
> It doesn't appear that cding further into say the unit test directory allows you to run make there however.
> I was about to close this PR, but I would still like to be able to build subsets of the tests.

Not sure if this helps, but, when using the Unix Makefile generator with CMake, you can say `make <target_name>` or `make <target_name>/fast` to build only that particular target. The `/fast` suffix should tells Make to skip the dependency checks. I've had success using that in the past.

**Comment by MrBurmark** [comment]
I've used that but it only allows me to easily make a single test, but with the test build time reorg we're splitting our tests into multiple sub tests so I'm looking for a way to build a set of tests like make test-*workgroup* but make doesn't support that syntax.

**Comment by rhornung67** [comment]
> I've used that but it only allows me to easily make a single test, but with the test build time reorg we're splitting our tests into multiple sub tests so I'm looking for a way to build a set of tests like `make test-*workgroup*` but make doesn't support that syntax.

Cyrus, Chris W, or David B may know some CMake mojo for doing what you want to do...

**Comment by MrBurmark** [comment]
I looked in the build/test subdirectories again and they did have makefiles, so I either missed that or was looking at a messed up build space.
I'll close this PR then.

**Pull request closed without merging**
