### PR TITLE
Update copyright dates in all files.

### PR DESCRIPTION
**Pull request by rhornung67**
Probably should have done this in the last release :-(

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Yup, whoops. Looks good. Have you added a script for doing this?

**Comment by rhornung67** [comment]
I have a script but it's not correct. I have to run one command manually and edit a file to make it work. So it's not automatic.  I'll show you what I have. Maybe you have a better way.

**Comment by rhornung67** [comment]
I thought appveyor was fixed?

**Comment by rhornung67** [comment]
should I merge even if appveyor is broken?

**Comment by davidbeckingsale** [comment]
Nope. It will be fixed once this PR goes in to BLT: https://github.com/LLNL/blt/pull/131

**Pull request merged**
