### PR TITLE
the \# is not valid in a macro, switch to macro pragma syntax

### LINKED ISSUE #85: clang-format of  foralln/Permute.hxx breaks nvcc-7.5_gcc-4.9.3 build
Thought it was initially limited to clang-format tool from clang-3.8.0+ but I'm seeing this with clang-3.7.0. 

Clang builds are fine as you might expect.

### PR DESCRIPTION
**Pull request by trws**
fixes #85

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Assuming that syntax is supported everywhere we need it, I approve.

**Comment by davidbeckingsale** [comment]
:+1:

**Comment by trws** [comment]
It was added to C in C99 and imported into C++ with the C99 preprocessor in C++11.  Since it's a cuda-specific pragma though, it should only ever come up in nvcc and clang, both of which accept it thankfully.

**Comment by keasler** [comment]
Something to keep in mind -- on MS Windows, the pragma macro takes a different form.  That said, I much prefer the functional form of pragma to the preprocessor form.

**Comment by trws** [comment]
You're right @keasler, they decided that capitalizing the P was a bad idea for some reason.  I'm not sure what nvcc would do on Windows, but we might need to add a switch for that if it comes up.  The issue here is that the functional form shouldn't work in this context at all, the `#` having been interpreted as a "stringize" character rather than the start of a directive, so keeping it the way it was is not really a good option.

**Comment by rhornung67** [comment]
@trws , @keasler Peter R. has an outstanding RAJA branch with some fixes to make it work on Windows. After the L2 dust settles, we should coordinate with him to pull those changes in.

**Comment by trws** [comment]
That sounds really good @rhornung67.  I don't know if you've tried it, but the current develop is portable to MacOS and probably just about any BSD or Unix now too, so if we can cover windows it should hit basically all the bases.

**Comment by davidbeckingsale** [comment]
This just bit me :( let's get it merged ASAP.

**Comment by davidbeckingsale** [comment]
Once this passes travis I'll merge.

**Comment by jonesholger** [comment]
This needs to be merged!!!

**Pull request merged**
