### PR TITLE
Adapt corona allocation to flux

### PR DESCRIPTION
**Pull request by adrienbernede**
# Summary

- This PR is a evolution following corona switch from slurm to flux

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
This was on my todo list. Thanks for taking care of it @adrienbernede !

**Comment by adrienbernede** [comment]
@rhornung67, you’re welcome. I don’t why Azure fails all of a sudden though. Seems to be missing openmp.

**Comment by rhornung67** [comment]
> @rhornung67, you’re welcome. I don’t get why Azure fails all of a sudden though. Seems to be missing openmp.

Hmm. @mdavis36 fixed this a couple of days ago. The docker file wasn't setting LD_LIBRARY_PATH to point at the OpenMP runtime. @mdavis36 can you take a look at this?

**Comment by rhornung67** [comment]
@adrienbernede apparently the LD_LIBRARY_PATH fix was done on a branch and not develop....https://github.com/LLNL/RAJA/blob/task/tut-reorg-aws/Dockerfile#L44

**Comment by rhornung67** [comment]
Sorry. Didn't mean to click "close".

**Comment by adrienbernede** [comment]
@rhornung67 just to mention I cherry-picked mdavis36 commit and test are now passing.

**Comment by adrienbernede** [comment]
@davidbeckingsale I think this is the PR you are looking for.

**Review by davidbeckingsale — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]
Thank you @adrienbernede

**Pull request merged**
