### PR TITLE
RAJA - CHAI: Multi project integration

### PR DESCRIPTION
**Pull request by adrienbernede**
### Summary

This PR introduces multi-project integration.

### Design review

Multi-project integration consists in 2 use cases:
- When working on RAJA, testing whether new changes impact projects depending on RAJA (CHAI, at the moment).
- When working on CHAI, testing whether updating with a newer RAJA will work.

To achieve this, the present PR:
- Allows an external pipeline to update RAJA during CI via definition of a specific environment variable.
- Introduces a pipeline trigger, when testing "develop" branch, that will test how develop behaves in CHAI.

This has no impact on regular CI, except adding useful information when testing "develop" on Gitlab.

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
@adrienbernede - does this need a compilers.yml and packages.yml in uberenv?

**Comment by davidbeckingsale** [comment]
LGTM.

**Pull request merged**
