### PR TITLE
Release version 0.2.0

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Great questions. Basically, we screwed up by never doing releases. v0.2.0 will be our baseline for committing to semantic versioning releases. I will try come up with some better notes.

Going forward, bugfixes and small changes will be released as 0.2.x changes, and new features/functionality that doesn't change the interface will be released as 0.x.0

I propose that the 0.2.x releases happen approximately weekly (assuming some changes), and the 0.x.0 releases happen as necessary (e.g. the new reduction style for OpenMP would be a 0.x.0 release)

**Comment by DavidPoliakoff** [comment]
Good stuff, I like that release schedule.

**Comment by ajkunen** [comment]
Agreed!

**Comment by davidbeckingsale** [comment]
I need approvals... 😄  @rhornung67 @DavidPoliakoff @ajkunen @trws

**Comment by DavidPoliakoff** [comment]
:+1: but think Rich should weigh in on releases

**Comment by davidbeckingsale** [comment]
Yup, and our pullapprove rules enforce this. (Also, I met with him this morning and that prompted this release!)

**Comment by DavidPoliakoff** [comment]
Ah, great

**Comment by rhornung67** [comment]
I have the semantic versioning process, etc. described in the dev guide on my branch. I need to do a little more clean up and then it will be linked off our README page.

I asked folks to look this over and provide feedback a good while back…..

**Comment by DavidPoliakoff** [comment]
Yeah, I was pretty emphatically pro when it came up (off email, I think)

**Comment by davidbeckingsale** [comment]
Yup, that's right. We discussed and agreed on it. However, there is a significant difference between agreeing on a release model and actually following it...

**Comment by davidbeckingsale** [comment]
Also, following this release, `master` will be the default branch on GitHub, and we will point applications either at master or at a specific release tag.

**Comment by rhornung67** [comment]
:+1:

**Pull request merged**
