### PR TITLE
V0.13.0 rc

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR is to merge the v0.13.0 RC branch into main for the v0.13.0 release. Please review the changes in this PR https://github.com/LLNL/RAJA/pull/919 and approve THIS PR.

### CODE REVIEW

**Review by MrBurmark — APPROVED** [review]

**Review by rchen20 — APPROVED** [review]

**Comment by rhornung67** [comment]
@trws do you know what's going on with the two camp test failures on appveyor?

**Comment by rhornung67** [comment]
> @trws do you know what's going on with the two camp test failures (resource and tuple) on appveyor and travis?

@trws The issue appears to be related to the BLT bump I did to be consistent with Umpire. If I back that out camp tests pass.  It looks like a gtest version compatibility issue.

**Comment by trws** [comment]
> @trws do you know what's going on with the two camp test failures (resource and tuple) on appveyor and travis?

What failures? Theres a test that succeeds by getting the correct compilation error, is that the one you mean?

**Comment by rhornung67** [comment]
@trws the camp failures were due to a BLT issue. That is fixed and so the tests are all passing now. I'm waiting on a BLT release (hopefully by the end of today). Then I will bump the submodule to that and this is good to go.

**Comment by trws** [comment]
Gotcha, thanks @rhornung67!

**Comment by rhornung67** [comment]
I'm going to merge this PR and do a release at 3pm today. If anyone else wants to review, please do so before then. Thank you.

**Review by artv3 — APPROVED** [review]

**Pull request merged**
