### PR TITLE
Allow for const iterators in loop exclusive scan.

### PR DESCRIPTION
**Pull request by corbett5**
You should be able to use a const iterator in the loop exclusive scans.

### CODE REVIEW

**Comment by willkill07** [comment]
This should also be done for sequential scan (exclusive). We must also be missing tests for this 🙁

**Comment by rhornung67** [comment]
@corbett5 we briefly discussed this PR at the RAJA meeting this morning. We are OK with this change, but it needs to be done in several other places in the code. Please update the base branch and apply the same change to all relevant code points for all RAJA scans. Then, request @willkill07 @MrBurmark @trws and @rhornung67 (plus other RAJA folks if you wish) for review and approval.  Thank you.

**Comment by corbett5** [comment]
Sounds good. I might not get around to it for a bit though.

**Comment by willkill07** [comment]
This should be good for review.

I also fixed memory access bug for OpenMP and renamed things to avoid `i0`

**Comment by MrBurmark** [comment]
Is this ready to merge?

**Comment by rhornung67** [comment]
> Is this ready to merge?

I think so. @willkill07 is this good to merge?

**Comment by willkill07** [comment]
Yup!

**Pull request merged**
