### PR TITLE
Switch back to multiple test executables

### PR DESCRIPTION
**Pull request by willkill07**
Closes #298 

Instead of undoing all of the google-test refactor, this PR just updates the binary generation to it's previous state (one binary per test source file).

There are some performance implications with having the tests be separate binaries though -- on the order of 15% for compilation on `wiz` and 10% for execution.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
I'm honestly a fan of leaving it as it is (one executable) and maybe having scripts that run that executable with filter arguments in order to get the old behavior

**Comment by willkill07** [comment]
I figure I should at least quantify the changes instead of just state an opinion.

Under a compute node on rzwiz I configured RAJA with CUDA and CHAI support and built RAJA under the `develop` (single executable) and `enh/revert-multiple-tests` (multiple executables) for both CUDA 8 and CUDA 9.

The script i used:
```bash
echo 'Configure + Compile'
time (cmake \
-DRAJA_ENABLE_CUDA=On \
-DCUDA_TOOLKIT_ROOT_DIR=$CUDA_ROOT_DIR \
-DCMAKE_PREFIX_PATH=$CHAI_INSTALL_DIR \
-DRAJA_ENABLE_CHAI=On .. >&/dev/null
make -j >&/dev/null)
echo 'Test Suite'
time ctest >&/dev/null"
```

## CUDA 8

| Version | `enh/revert-multiple-tests` | `develop` | % improvement |
|:------:|:-------:|:-------:|:--:|
| Configure + Compile (Real) | 1:24.30 | 0:53.14 | 36.96% |
| Configure + Compile (User) | 4:25.32 | 4:23.88 | 0.54% |
| Execute Test Suite | 0:23.40 | 0:13.18 | 43.67% |

## CUDA 9

| Version | `enh/revert-multiple-tests` | `develop` | % improvement |
|:------:|:-------:|:-------:|:--:|
| Configure + Compile (Real) | 0:45.06 | 0:43.29 | 3.92% |
| Configure + Compile (User) | 3:59.71 | 3:58.60 | 0.46% |
| Execute Test Suite | 0:20.27 | 0:10.09 | 50.22% |

So from these times, we see there is not so much benefit with CUDA 9 compared to CUDA 8, but the tests still run in half the time.

Of course there's more to it than just end-to-end time. Yes, it was a breaking change, but I wasn't aware that there was dependencies on analyzing tests. I should have probed for more input on it. So I'm sorry about that. It won't happen again.

Regardless, I don't mind either form since I'm just going to run `ctest -V` anyways. For me, I just care whether or not the tests work as intended. The complete switch to google-test helps out with that a lot.

**Comment by willkill07** [comment]
I did observe an interesting (read: bad) property. With the additional examples under @artv3's branch, Travis consumed all of the virtual memory:

https://travis-ci.org/LLNL/RAJA/jobs/260414929#L2904

I'm not sure if this is an effect of the additional examples or if this is happening due to concurrent linking. @artv3 got around it by disabling parallel compilation (removing `-j` from the `make` invocation), but I'm not really sure. But if we are indeed consuming all of Travis' resources because of the single binary, this is definitely a tick in box for multiple test files.

**Comment by willkill07** [comment]
Alternatively, we can also create a binary per directory. We already split our tests in the following way:

* `test/integration/<THING>` -- tests for integrating *THING* with RAJA
* `test/unit/*.cpp` -- agnostic/generic tests
* `test/unit/cpu/*.cpp` -- tests for CPU (including sequential and OpenMP)
* `test/unit/cuda/*.cpp` -- tests for CUDA
* `test/unit/omp-target/*.cpp` -- tests for OpenMP 4.5 Target Offload

**Comment by trws** [comment]
Consuming all of the memory is a surprise.  Does this generate a compile of an object for each file followed by a link, or does it generate a single compile command?  Something is making me wonder whether it would work to link each as a shared library then have a single binary made up of gtest_main and all of those .so files.

**Comment by willkill07** [comment]
Closes #304

**Comment by davidbeckingsale** [comment]
Pinging @ajkunen and @rhornung67...

**Pull request merged**
