### PR TITLE
PR from fork/1236

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR pulls the branch from the fork in https://github.com/LLNL/RAJA/pull/1236 into the RAJA repo so all CI will be run on it. 
- The original PR discussion can be viewed in https://github.com/LLNL/RAJA/pull/1236. 
- **Please approve this PR for merging.**

### CODE REVIEW

**Review by artv3 — DISMISSED** [review]

**Comment by andrewcorrigan** [comment]
> @andrewcorrigan don't worry about the gitlab ci failures at this point. they are being patched today. i'll restart when they're back up.

thanks for letting me know.  I was actually curious about how this worked and was watching the pipeline progress on CZ and saw the failures. I'm not worried about most of the failures, but [one of the jobs looks like I may have broken something](https://lc.llnl.gov/gitlab/radiuss/RAJA/-/jobs/604219).

**Comment by andrewcorrigan** [comment]
I see it failed again, I just repro'd manually on ruby and will try to fix it ASAP

**Review by mdavis36 — APPROVED** [review]

**Comment by rhornung67** [comment]
It looks like we have to force intel 19 to use a lower C++ standard, probably C++14. @trws thoughts on that?

**Comment by andrewcorrigan** [comment]
Reverting this change bypasses the reported error:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 19b7404cf..6833b45cf 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -64,7 +64,7 @@ if(NOT DEFINED BLT_CXX_STD)
     set(BLT_CXX_STD c++14 CACHE STRING "Version of C++ standard")
     message("Using C++ standard: ${BLT_CXX_STD}")
   else() #cmake has no idea what to do, do it ourselves...
-    foreach(flag_var "c++20" "c++17" "c++14" "c++11")
+    foreach(flag_var "c++17" "c++14" "c++11")
       CHECK_CXX_COMPILER_FLAG("-std=${flag_var}" COMPILER_SUPPORTS_${flag_var})
       if(COMPILER_SUPPORTS_${flag_var})
         set(BLT_CXX_STD ${flag_var} CACHE STRING "Version of C++ standard")
```

It looks like `CHECK_CXX_COMPILER_FLAG` detects `-std=c++20` is available:
```
-- Performing Test COMPILER_SUPPORTS_c++20
-- Performing Test COMPILER_SUPPORTS_c++20 - Success
Using C++ standard: c++20
```

but then CMake doesn't know that this compiler supports it:
```
CMake Error in CMakeLists.txt:
  Target "RAJA" requires the language dialect "CXX20" , but CMake does not
  know the compile flags to use to enable it.
```
Would it make sense to replace `CHECK_CXX_COMPILER_FLAG` with the same functionality CMake is using to set the language dialect?

Also, I'm encountering the following error when compiling `develop` not the PR branch:
```
[  0%] Building CXX object blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
In file included from /g/g12/acorriga/RAJA/tpl/camp/include/camp/camp.hpp(24),
                 from /g/g12/acorriga/RAJA/tpl/camp/src/errors.cpp(11):
/g/g12/acorriga/RAJA/tpl/camp/include/camp/tuple.hpp(114): error: cannot overload functions distinguished by return type alone
      CAMP_HOST_DEVICE constexpr Type& get_inner() noexcept { return val; }
                                       ^

In file included from /g/g12/acorriga/RAJA/tpl/camp/include/camp/camp.hpp(24),
                 from /g/g12/acorriga/RAJA/tpl/camp/src/errors.cpp(11):
/g/g12/acorriga/RAJA/tpl/camp/include/camp/tuple.hpp(138): error: cannot overload functions distinguished by return type alone
      CAMP_HOST_DEVICE constexpr Type& get_inner() noexcept
                                       ^
```

**Comment by rhornung67** [comment]
I pushed a change to see if intel will pass. I think we're using CMake 3.14.5, which is the default on the systems we are running Gitlab testing.

**Comment by trws** [comment]
Yeah, intel 19 will probably need to be lower.  In principle it should work with whatever it says it supports, but it will probably never support C++ 20.

**Comment by andrewcorrigan** [comment]
[It looks like it still failed](https://lc.llnl.gov/gitlab/radiuss/RAJA/-/jobs/604458).   Would just reverting just the one line as I showed above be acceptable?

This would:
- Still allow for manually specifying `-DBLT_CXX_STD=c++20`, which I tested on ruby with `/usr/tce/packages/clang/clang-13.0.0` and confirmed that it builds with C++20 and `make test` succeeds.
- Bypasses the immediate error when building `intel-19.1.0`. However, I'm still getting the subsequent error that occurs in `camp` on the current `develop` branch, both with `-DBLT_CXX_STD=c++17` and `-DBLT_CXX_STD=c++14`

**Comment by trws** [comment]
That's a peculiar error, is it specific to ICC 19? If so, @rhornung67 where are we on getting feedback if we need to continue to support the legacy Intel stack?

**Comment by andrewcorrigan** [comment]
> That's a peculiar error, is it specific to ICC 19?

It looks like all the other tests passed, so I guess so.  Are there others you'd like me to test?

**Comment by rhornung67** [comment]
@andrewcorrigan if the change you described above fixes the problem with intel 19 and everything else works, I say go for it. We can't officially require C++17 yet, much less C++20, until the compilers our production apps rely on catch up.

@trws I really wish we could get off the older intel compilers, and I've been trying to push apps toward that end, but I think we need to support intel 19 for a while longer.

BTW, I'm on vacation today. So I will be offline for the rest of today.

**Comment by andrewcorrigan** [comment]
I updated my branch.   I'm not sure what your preferred approach is, but I re-did the first commit and force-pushed so it's still just two clean commits.  Please let me know if you prefer a different approach.

**Comment by rhornung67** [comment]
> I updated my branch. I'm not sure what your preferred approach is, but I re-did the first commit and force-pushed so it's still just two clean commits. Please let me know if you prefer a different approach.

Can you push your changes to the branch here instead of your fork? If you don't have permissions, please let me know.

**Comment by andrewcorrigan** [comment]
> Can you push your changes to the branch here instead of your fork? If you don't have permissions, please let me know.

I don't have permissions. 

In case you need it, the commit is available from my fork here: https://github.com/andrewcorrigan/RAJA/commit/986549a17c71527928d16e45f0f453abb2abb1db

**Comment by rhornung67** [comment]
> > Can you push your changes to the branch here instead of your fork? If you don't have permissions, please let me know.
> 
> I don't have permissions.
> 
> In case you need it, the commit is available from my fork here: [andrewcorrigan@986549a](https://github.com/andrewcorrigan/RAJA/commit/986549a17c71527928d16e45f0f453abb2abb1db)

Sorry about that. I can't add you to the RAJA-contrib team since you are not in the LLNL GitHub org. I'll work on getting your changes into the branch here. We'll see what we can do about getting you permissions. @trws  how did you work this for Brian H. recently?

**Comment by trws** [comment]
We now have a "collaborators" group of sorts in the organization, it's not something we officially support though so we should probably only do that if the plan is to make regular contributions.  I'm working another angle with Ian on triggering gitlab builds for fork PRs, but I'm not sure if that will work out, especially unless I can find someone with a couple hours to work on it.

**Comment by adayton1** [comment]
> Reverting this change bypasses the reported error:
> 
> ```
> diff --git a/CMakeLists.txt b/CMakeLists.txt
> index 19b7404cf..6833b45cf 100644
> --- a/CMakeLists.txt
> +++ b/CMakeLists.txt
> @@ -64,7 +64,7 @@ if(NOT DEFINED BLT_CXX_STD)
>      set(BLT_CXX_STD c++14 CACHE STRING "Version of C++ standard")
>      message("Using C++ standard: ${BLT_CXX_STD}")
>    else() #cmake has no idea what to do, do it ourselves...
> -    foreach(flag_var "c++20" "c++17" "c++14" "c++11")
> +    foreach(flag_var "c++17" "c++14" "c++11")
>        CHECK_CXX_COMPILER_FLAG("-std=${flag_var}" COMPILER_SUPPORTS_${flag_var})
>        if(COMPILER_SUPPORTS_${flag_var})
>          set(BLT_CXX_STD ${flag_var} CACHE STRING "Version of C++ standard")
> ```
> 
> It looks like `CHECK_CXX_COMPILER_FLAG` detects `-std=c++20` is available:
> 
> ```
> -- Performing Test COMPILER_SUPPORTS_c++20
> -- Performing Test COMPILER_SUPPORTS_c++20 - Success
> Using C++ standard: c++20
> ```
> 
> but then CMake doesn't know that this compiler supports it:
> 
> ```
> CMake Error in CMakeLists.txt:
>   Target "RAJA" requires the language dialect "CXX20" , but CMake does not
>   know the compile flags to use to enable it.
> ```
> 
> Would it make sense to replace `CHECK_CXX_COMPILER_FLAG` with the same functionality CMake is using to set the language dialect?
> 
> Also, I'm encountering the following error when compiling `develop` not the PR branch:
> 
> ```
> [  0%] Building CXX object blt/thirdparty_builtin/googletest-master-2020-01-07/googletest/CMakeFiles/gtest.dir/src/gtest-all.cc.o
> In file included from /g/g12/acorriga/RAJA/tpl/camp/include/camp/camp.hpp(24),
>                  from /g/g12/acorriga/RAJA/tpl/camp/src/errors.cpp(11):
> /g/g12/acorriga/RAJA/tpl/camp/include/camp/tuple.hpp(114): error: cannot overload functions distinguished by return type alone
>       CAMP_HOST_DEVICE constexpr Type& get_inner() noexcept { return val; }
>                                        ^
> 
> In file included from /g/g12/acorriga/RAJA/tpl/camp/include/camp/camp.hpp(24),
>                  from /g/g12/acorriga/RAJA/tpl/camp/src/errors.cpp(11):
> /g/g12/acorriga/RAJA/tpl/camp/include/camp/tuple.hpp(138): error: cannot overload functions distinguished by return type alone
>       CAMP_HOST_DEVICE constexpr Type& get_inner() noexcept
>                                        ^
> ```

This may be totally a red herring, but I think I saw a similar error just this last week when building a different library with clang but using the system default c++ libraries. IIRC, if I told it via the --gcc-toolchain flag to use gcc 8.3.1 libraries or newer then it compiled. (I think a lot of LC systems use gcc 4.9.3 by default.)

**Comment by andrewcorrigan** [comment]
looks like the CI pipeline failures are just timeouts or other unrelated issues now.

**Comment by rhornung67** [comment]
@andrewcorrigan restarted those jobs. Hopefully, they will go through now.

**Comment by andrewcorrigan** [comment]
I saw two failures that weren't marked "allowed to fail":
- A timeout for the intel-19.1 compiler, which looks unrelated, since it is now compiling in C++17 mode
- Another error with gcc-8.3 + CUDA, which was compiling in C++14 mode

**Comment by andrewcorrigan** [comment]
I just checked the latest pipeline.  Besides the usual failures from the "allowed to fail" jobs, there were only the following two failures remaining:

[hip_4_5_2_clang_13_0_0](https://lc.llnl.gov/gitlab/radiuss/RAJA/-/jobs/610809)
```
$ srun -p pbatch -t 30 -N 1 scripts/gitlab/build_and_test.sh
srun: job 43202 queued and waiting for resources
Error encountered during job: signal: killed
Error encountered during job: Error executing run_exec: exit status 1
ERROR: Job failed: execution took longer than 3h0m0s seconds
```

[hip_4_5_2_clang_13_0_0_desul_atomics](https://lc.llnl.gov/gitlab/radiuss/RAJA/-/jobs/610810)
```
WARNING: Starting with version 14.0 the 'build_script' stage will be replaced with 'step_script': https://gitlab.com/gitlab-org/gitlab-runner/-/issues/26426
$ srun -p pbatch -t 30 -N 1 scripts/gitlab/build_and_test.sh
srun: job 43205 queued and waiting for resources
Error encountered during job: signal: killed
Error encountered during job: Error executing run_exec: exit status 1
ERROR: Job failed: execution took longer than 3h0m0s seconds
```

**Comment by rhornung67** [comment]
@andrewcorrigan we're having issues with getting our jobs through the queues on some systems. We'll keep trying. Hopefully, this will go through soon.

**Comment by rhornung67** [comment]
@trws @davidbeckingsale @rchen20 @mdavis36 this looks good to merge. Please approve if you thinks it's good.

**Review by mdavis36 — APPROVED** [review]

**Review by rchen20 — APPROVED** [review]

**Comment by rhornung67** [comment]
@davidbeckingsale any concerns about this before I merge it?

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale any concerns about this before I merge it?

None from me. Merge away!

**Pull request merged**
