### PR TITLE
Issue186 install on windows

### PR DESCRIPTION
**Pull request by tepperly**
Windows needs RUNTIME DESTINATION for .dll libraries to be installed.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
@tepperly I believe the current practice is to aim pull requests at the develop branch, @davidbeckingsale can correct me if I'm wrong there

**Comment by davidbeckingsale** [comment]
That depends. @tepperly are you using the master branch or do you still build your code against develop?

If master, we can create a hotfix branch for this and merge directly to master and bump the bugfix version.

**Comment by tepperly** [comment]
It's a mistake. It should be develop.

Tom

**Comment by davidbeckingsale** [comment]
Okay, I'm not sure if you can change the PR, but if as soon as you make one against develop we can get that merged right away.

**Comment by davidbeckingsale** [comment]
I was able to change it. I'll wait for the tests to pass and we can get this merged.

**Pull request merged**
