### PR TITLE
Adding Intel build (hopefully)

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Thanks to @jeffhammond it looks like we can now build with Intel on Travis! 😄

**Comment by trws** [comment]
Very nice!

**Comment by davidbeckingsale** [comment]
It works! So I think with an approval we can just merge this. It might be worth forking that script and then using it to support multiple Intel versions, but that can be a future PR. This should be enough to catch any Intel snafus for now.

**Comment by jeffhammond** [comment]
You may want to subscribe to https://github.com/nemequ/icc-travis/issues/10 to see if/when progress is made on version support.  I'll try to do the tedious part at least, since I have every version of the compiler installed locally.

**Comment by davidbeckingsale** [comment]
Nice! Subscribed.

**Comment by trws** [comment]
Thanks @jeffhammond!

**Pull request merged**
