### PR TITLE
PR from fork/699

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR pulls the branch from the fork in this PR https://github.com/LLNL/RAJA/pull/699 into the RAJA repo.

We will modify, review, approve, and merge this one when it is ready.

### CODE REVIEW

**Comment by rhornung67** [comment]
@trws I took a stab at merging develop into your old forked branch and resolving the merge conflicts.

**Comment by rhornung67** [comment]
So I got everything to build and pass except for hip (azure and gitlab). Curiously, the hip build with desul atomics enabled builds and passes, but the others do not. I see no difference in the build specs between one that works and one that does not.

**Comment by trws** [comment]
Now that's interesting.  It's possible there's something in the classic atomics specifically for hip that tickles something, I think the desul switch compiles some things out.  Planning to dig into this after the OSDI deadline this afternoon.

**Comment by trws** [comment]
Quick glance shows that the hip compiler is insisting on compiling in 11 mode rather than 14 mode, I remember there being a bug where the hipcc wrapper injected `-std=c++11` that's my best guess for culprit.  Switching to amdclang would probably solve it, or seeing if a newer hip version fixes the bug.

**Comment by rhornung67** [comment]
@mdavis36 your change appears to have fixed the Gitlab CI issue for Hip. It hasn't reported back yet since XL checks are still running.  Thanks for your help!

**Comment by trws** [comment]
Looking back at this, it looks like everything is passing right now.  I'm going to take a pass for cruft, but one thing we could consider changing is that I was looking for the *bare minimum* useful C++14 when I wrote this.  That meant that it could work with some pretty old compilers and helped with XL, that should be on our list to snug up as we go forward.

**Review by trws — APPROVED** [review]
This works, there are things we could clean up, but no obvious craft that's trivial to change.  There are a couple of things in camp I found that need to be cleaned up actually, but this looks good to get us going.

The big thing is now we can use generic lambdas where useful, and return type deduction without a trailing return type.

**Review by mdavis36 — APPROVED** [review]

**Comment by rhornung67** [comment]
@trws it sounds like your good with this as is. please merge if that is true.

**Comment by trws** [comment]
I am, and enabled the option to set "merge when checks pass" on this repository, then set that option on this PR.  It will merge itself if and when everything comes back green after the merge in from develop.

**Comment by trws** [comment]
And now it looks like that maybe won't happen, there are two failures in gitlab from user permission errors (clang9 and gcc 8.3) and it looks like there's an error in one of the hip builds from Device::callbackQueue? Does that sound familiar @mdavis36?

**Comment by mdavis36** [comment]
@trws No I've never seen that before

**Comment by rhornung67** [comment]
Gitlab has weird intermittent failures. Nothing has changed that should cause the failures after merging the latest changes on develop. I restarted the Gitlab CI. Hopefully, it will come back green.

**Comment by rhornung67** [comment]
@trws Gitlab CI checks came back green after restarting them.  The automatic merge thingy didn't work. I'm going to merge.

**Pull request merged**
