### PR TITLE
Remove 'breathe' from Sphinx requirements

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by rhornung67** [comment]
So are we planning to generate source code documentation in sphinx via breathe? That may be OK, but it's more limited (navigation, etc.) than doxygen.

**Comment by ajkunen** [comment]
We are starting to use doxygen only in Ardra… doxygen 1.8.0 introduced Markdown support, making it unnecessary to use doxygen+sphinx

-Adam

**Comment by davidbeckingsale** [comment]
I didn't think we were, but you had 'breathe' as a requirement in the sphinx config, so I fixed it this way. Since we aren't generating doxygen you could just instead remove the breathe requirement entirely.

**Comment by davidbeckingsale** [comment]
I'm documentation tool agnostic, as long as it uses a sane format.

**Comment by davidbeckingsale** [comment]
I have removed the 'breathe' requirement since we don't have doxygen anyway. We can always document classes using Sphinx. There's a good example of that here: http://ceres-solver.org/guide.html

**Pull request merged**
