### PR TITLE
Testing building applications with GCC-4.9

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This doesn't need to be merged, I just wanted to test out building the example-applications as part of our CI.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
This works, but we need to fix warnings and make sure that the applications work without OpenMP. @rhornung67 do you want the applications to be built as part of the tests?

**Comment by rhornung67** [comment]
@davidbeckingsale yes, I think we should build the proxy apps as part of the tests. Agree?

**Comment by davidbeckingsale** [comment]
Yup, we need to fix the warnings though...

**Comment by davidbeckingsale** [comment]
Closing, this needs the applications warnings to be fixed first.

**Pull request closed without merging**
