### PR TITLE
switch to unowned for temporary scoped listsegment objects

### PR DESCRIPTION
**Pull request by trws**
Addresses slowdown discussed by mail (hopefully).

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
👍 

[Approved with PullApprove](https://pullapprove.com/LLNL/RAJA/pull-request/127/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=LLNL/RAJA) [Approved with PullApprove](https://pullapprove.com/LLNL/RAJA/pull-request/127/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=LLNL/RAJA)

**Comment by DavidPoliakoff** [comment]
Approved

**Comment by trws** [comment]
Good catch by the way @MrBurmark, I completely missed that there were owned and unowned variants.  This should be a quick trivially correct win.

**Comment by rhornung67** [comment]
:+1:  I second kudos to @MrBurmark for tracking this down. That likely save others a chunk of time looking for something else.

**Comment by DavidPoliakoff** [comment]
Anybody want to press the big shiny merge button?

**Pull request merged**
