### PR TITLE
update to a camp that links with nvcc

### PR DESCRIPTION
**Pull request by trws**
Should solve nvcc10 issues with clang6 and gcc 7.3.

Somehow camp's build system was falling into a state where it wasn't linking a test with nvcc that should have been, this took care of it for cases I managed to repro on lassen.  @rhornung67, let me know if this does it for you.

### CODE REVIEW

**Comment by trws** [comment]
Glad to hear it, waiting to make sure the tests come back green then we can merge.

Also, speaking of, we should probably put up a container that tests at least one of those combinations, it looks like there's some new wrinkle with a combination of nvcc10, cmake and clang6/gcc7 that we were tickling here.

**Comment by rchen20** [comment]
Sorry to be pushy, but would it be possible to merge this soon-ish? I'd like to put in a fix for omp target seg faults affecting PerfSuite. It tests fine with RAJA master, but would be good to make sure it works in develop. Thanks!

**Comment by rhornung67** [comment]
@rchen20 I approved last week. It needs to be updated with the base branch. Then it can be merged.

**Comment by trws** [comment]
I'll update again, thought I had when it was approved.

Now updated, tests running.

**Comment by rhornung67** [comment]
@trws Feel free to merge it when tests pass.

**Comment by trws** [comment]
Thanks for hitting the button Robert!

On 12 Aug 2019, at 9:47, Robert Chen wrote:

Merged #648<https://github.com/LLNL/RAJA/pull/648> into develop.

**Comment by rchen20** [comment]
I merged it after the tests passed. @trws Thanks for your help!

**Pull request merged**
