### PR TITLE
Task/openmptarget smoketests

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR creates a subset of OpenMP target tests to build by default. Test building for all other back-ends is unchanged.
  - A CMake variable has been added to control this behavior (turn off to build all OpenMP target tests
  - With the 2021.01.08 drop of the XL compiler, the subset of OpenMP target tests builds in ~40 minutes, which should be suitable for Gitlab CI.
- Build scripts have been updated to cull old ones and add new ones.

Note: I did not define a subset of openmp target tests for the recently added kernel tiling tests. If folks approve of the changes here, I can do a similar thing for those tests.

Note: While the subset of OpenMP targert tests builds successfully, several fail at run time. There appear to be two issues. First, kernel tests fail with strongly-typed indices. I believe this used to work. Second, other tests (not all) fail with segfaults. I believe the culprit is the camp openmp target resource since all RAJA openmp target kernels run successfully in the perf suite. There, we don't use camp resource objects. Instead, we manage device memory explicitly with openmp library calls (alloc, memcpy, etc.)

### CODE REVIEW

**Comment by rhornung67** [comment]
LGTM

**Review by artv3 — DISMISSED** [review]

**Review by rhornung67 — COMMENTED** [review]
Is the issue similar for the functional reduction tests?

**Comment by rchen20** [comment]
@rhornung67 I'm working through non-strongly typed index failures, and they don't seem to be the same thing. I'll keep poking at it. There are a bunch that are strong typed index failures though.

**Comment by rhornung67** [comment]
LGTM

**Comment by rhornung67** [comment]
LGTM

**Review by rchen20 — APPROVED** [review]

**Comment by rhornung67** [comment]
LGTM

**Pull request merged**
