### PR TITLE
Minor mods and additions to build scripts; e.g., naming consistency, added Intel 16.0.210, etc.

### PR DESCRIPTION
**Pull request by rhornung67**
In addition to script changes, ran a battery of tests.  A couple of things to note:
1) CPUnested test segfaults with Intel 16.0.210 with -O3 and -O2. Runs fine with -O1 and -O0. Also works with Intel 16.0.19 at all optimization levels.
2) CUDA 8.0 appears to have a bug -- complains about overloading one of the atomics in the CUDA reductions based on return type, which is not the case.  CUDA 7.5 works fine.

### CODE REVIEW

**Comment by keasler** [comment]
In CUDA 8, the standard library may now contain an overloading of the function(s) we had to write for types that were not supported in 7.5 .

**Comment by rhornung67** [comment]
But, what I noted is still a compiler bug.

**Comment by trws** [comment]
CUDA 8 provides overloads for the atomic operations on doubles, so we'll have to add an `#if` check for whether cuda 8 is in use or not to get through that most likely. As to the PR though:

👍

**Comment by rhornung67** [comment]
Folks, I don't want to approve my own PR. Can I get someone else to approve this? I want to get it in and start on some other things. Thanks, in advance.

**Comment by davidbeckingsale** [comment]
@keasler should approve this, then the pullapprove check will pass.

**Comment by trws** [comment]
If we get one more approver, @keasler or not, I'm satisfied with this one and think it would be reasonable to merge it.  By the by, I spoke with the developer of pullapprove, they're looking at having a way to assign reviewers, it will be attached to the GitHub assignees on a PR if and when they do, so we may be able to get the exact rule that was used before on stash before too long.

**Comment by keasler** [comment]
I'm not the right person to approve this. I have to defer to the Cmake and git experts.

**Comment by davidbeckingsale** [comment]
👍

**Pull request merged**
