### PR TITLE
Return raw pointer to registry entries 

### PR DESCRIPTION
**Pull request by davidbeckingsale**
# Summary

- This PR is a refactoring:
- It does the following:
    - Modifies the Registry API to return a raw pointer rather than a `shared_ptr`

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
CC @adayton1 @robinson96

**Review by adayton1 — APPROVED** [review]
LGTM

**Comment by adayton1** [comment]
Thanks!

**Review by rhornung67 — APPROVED** [review]
Should there be a comment in the documentation describing who owns the object vs. just using it?

**Comment by davidbeckingsale** [comment]
Check that `get()` never explicitly assigned to `shared_ptr`

**Comment by rhornung67** [comment]
LGTM

**Comment by davidbeckingsale** [comment]
LGTM

**Comment by rhornung67** [comment]
@davidbeckingsale wanna merge this?

**Pull request merged**
