### PR TITLE
Sphinx structure

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This is a documentation PR. It does the following:
  - Fixes grammar, typos, broken links, etc. in parts of the sphinx docs
  - Adds structure to the sphinx files, adding a top-level page and making it easier to build up more documentation in the future; e.g., developer guide, etc.
  - There is a link to the doxygen generated source docs from the main sphinx page. We will discuss how to improve that at an upcoming project meeting.

The sphinx doc build can be viewed here: https://raja.readthedocs.io/en/sphinx-structure/

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]
Looks fine to me.

**Review by artv3 — DISMISSED** [review]

**Comment by rhornung67** [comment]
Any comments or suggestions on this? Please submit your review. We can improve the doxygen part in a subsequent PR. Thanks.

**Review by davidbeckingsale — APPROVED** [review]
I think this loosk good. The only change I would suggest is to put the link to the Doxygen in the sidebar too, but I don't mind if that's done later.

**Comment by rhornung67** [comment]
> I think this looks good. The only change I would suggest is to put the link to the Doxygen in the sidebar too, but I don't mind if that's done later.

I'm not sure how to do that, but I'll look into it. I'm going to merge this, then play around with the doxygen organization more.

**Pull request merged**
