### PR TITLE
Add guards for RAJA_ENABLE_NESTED to tests

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This address compiler warnings mentioned in #125 
Tests requiring nested functionality are only build when `-DRAJA_ENABLE_NESTED=On`

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@trws @DavidPoliakoff can I get an approval?

**Comment by DavidPoliakoff** [comment]
Approved . Nice catch

**Comment by trws** [comment]
Since the user can use add that define, and use the constructs from the headers, even without setting that CMAKE define, do we really want to not run the tests?  It might be fine, but the default should be that RAJA_ENABLE_NESTED is on if that's the case.

**Comment by davidbeckingsale** [comment]
Sure, we could revert it, and check `RAJA_ENABLE_NESTED` before we re-define it.

**Comment by davidbeckingsale** [comment]
I reverted the previous changes and instead guarded the definitions.
@trws how's this?

**Comment by trws** [comment]
Works for me.

LGTM

**Comment by DavidPoliakoff** [comment]
Updates look fine to me, and pullapprove says it's good to go, as does Travis. Shiny merge button?

**Comment by davidbeckingsale** [comment]
I'll just wait for Travis to pass, then I'll hit the button.

**Pull request merged**
