### PR TITLE
fixing corona gitlab ci build issues

### PR DESCRIPTION
**Pull request by kab163**
# Summary

- This PR is a bugfix
- It fixes the corona gitlab CI build issues

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]

**Review by rhornung67 — COMMENTED** [review]
How does insert -L/opt/rocm-4.1.0/hip/lib on the link line? I may be missing something, but I only see -L/opt/rocm-4.1.0/lib

**Review by rhornung67 — APPROVED** [review]
Nevermind. I missed the '..' part.

**Comment by kab163** [comment]
> How does insert -L/opt/rocm-4.1.0/hip/lib on the link line? I may be missing something, but I only see -L/opt/rocm-4.1.0/lib

The "hip_root" is "/opt/rocm-4.*.0/hip"

**Comment by kab163** [comment]
Wow that was a scary accident lol sorry! I hope that doesn't mess anything up! (I accidentally clicked "close with comment" instead of "comment"....)

**Comment by rhornung67** [comment]
I think it's OK. It probably only restarted the CI stuff.

**Pull request merged**
