### PR TITLE
Bugfix/burmark1/use blt cxx std

### LINKED ISSUE #1049: Automatic c++ std detection can result in multiple standards in cxx flags
I noticed this with the new xl build script, but manually setting BLT_CXX_STD causes more than one -std=c++?? to end up in CMAKE_CXX_FLAGS.

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary
Set BLT_CXX_STD where we find the cxx std version. Remove RAJA_CXX_STANDARD_FLAG and use BLT_CXX_STD  instead.

- This PR is a refactoring, bugfix
- It does the following:
  - Modifies/refactors the way we set the cxx std version in cmake
  - Fixes #1049

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]
Nice, this a cool solution.

**Review by rhornung67 — APPROVED** [review]
Looks great. Thanks @MrBurmark

**Review by trws — COMMENTED** [review]
I like it.  The only thing I'd request, and it's an addition admittedly, is a check that the user-set flag is at least c++11.

**Comment by davidbeckingsale** [comment]
I think it's a CMake version issue in Travis, and on GitLab there seems to be some incompatibility between Intel and the GCC headers.

**Comment by trws** [comment]
I haven't checked the gitlab logs, but unless you change the gcc that intel uses for its STL from 4.9.3 to one of the devtoolset ones or one of the ones in TCE it will fail on 17.  Checking for c++98 seems reasonable.

**Review by rhornung67 — APPROVED** [review]
Thanks @MrBurmark

**Review by rhornung67 — APPROVED** [review]
Thanks @MrBurmark !

**Pull request merged**
