### PR TITLE
Non-Resource RAJA::forall gets default resource by value

### PR DESCRIPTION
**Pull request by mdavis36**
# Summary

- This PR is a bugfix for Issue #1048 
- It does the following:
  - Get a reference to the default resource within non-resource forall api calls.

### CODE REVIEW

**Review by artv3 — APPROVED** [review]

**Comment by artv3** [comment]
I approve under the condition the change gets propagated to the other use cases.

**Comment by trws** [comment]
This would solve that specific problem, but it seems like it leaves the resource-accepting functions fragile to this kind of bug introduced by calling code.  Since the resources are cheap to copy, perhaps accepting them by value and/or constructing event proxies by value would make sense?

**Comment by rhornung67** [comment]
@mdavis36 where do we stand on this? Do you need to make more changes?

**Comment by mdavis36** [comment]
@rhornung67 I spent some time on getting the EventProxy changes implemented and things are mostly working, I have a couple of issues that I'm looking into but this should be ready soon

**Comment by mdavis36** [comment]
Some changes are needed in camp for this PR see: https://github.com/LLNL/camp/pull/64

**Comment by MrBurmark** [comment]
Can you change the API to take resource by value (or const&) instead of by reference.

**Comment by trws** [comment]
> Theis looks good, but can the API to take resource by value (or const&) instead of by reference.

This is also my preference, and would fit with the camp updates as well.  The resource and event types are meant to be cheaply (trivially I think) copyable types to use as handles, so passing them by reference shouldn't be necessary.

**Comment by MrBurmark** [comment]
We are still taking type erased resources by reference. Should we change how that is done?

**Comment by trws** [comment]
In general I would say we shouldn't take them by reference, since it's easier to be certain we don't end up with dangling, but it doesn't matter terribly much as long as the function is reference safe.

**Comment by mdavis36** [comment]
> We are still taking type erased resources by reference. Should we change how that is done?

I don't believe how we pass type-erased resources would be as critical as it is for concrete resources. It looks like the type-erased Resource is mostly used in tests with a few other instances in the src and example dirs, so for consistencies sake I think we can change how it is used. I think I got all of them but let me know if I missed any.

**Review by MrBurmark — DISMISSED** [review]

**Review by rhornung67 — DISMISSED** [review]
Thanks @mdavis36 I scanned the code and didn't see any that you missed. But, I'm not 100% sure.

**Comment by mdavis36** [comment]
@rhornung67 @MrBurmark Can I get this re approved when you get a chance please

**Review by rhornung67 — APPROVED** [review]
I approve, but I think others should as well before merging.

**Review by MrBurmark — APPROVED** [review]

**Comment by rhornung67** [comment]
@mdavis36 i re-ran the gitlab ci jobs that timed out previously. it looks like everything will come back green now.

**Pull request merged**
