### PR TITLE
add Intel _mm_{malloc,free} to aligned heap managers

### PR DESCRIPTION
**Pull request by jeffhammond**
This fills the (small) gap between POSIX (`posix_memalign`) and C++17 (`std::aligned_alloc`), should one exist.

### CODE REVIEW

**Comment by trws** [comment]
I'm good with this, just need the icc compiler test on travis to pass... I'll restart it.

**Comment by trws** [comment]
Looks like we're getting:

```
Sorry, but the Trial License Activation does not work in silent mode on this
environment. If you still want to use it, please run installation in usual mode.
```

From the icpc test.  Thoughts @davidbeckingsale, @jeffhammond?

**Comment by jeffhammond** [comment]
🤷‍♂️

**Comment by davidbeckingsale** [comment]
It's something to do with the `secure` part of our Travis config, and I'm guessing it's because @jeffhammond is setting up this PR from a fork, unlike most of our internal PRs that are branches of this repo.

**Comment by jeffhammond** [comment]
Ah yes, that's the reason.  Travis doesn't know that my PR doesn't print the secure env var to the terminal, thereby defeating security.  They trust the authors of branches to not do this.

**Comment by trws** [comment]
Huh... we need a way to deal with that somehow.  I'm not sure what that would be though.  The obvious solution is to not test intel when it's a PR from an external fork, but that leaves us with part of our test coverage lost.  We can always pull PRs like this into local branches, but it's a much higher overhead workflow at that point.

@jeffhammond, have you run into any good ways to deal with this?

**Comment by jeffhammond** [comment]
https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by trws** [comment]
Thanks @jeffhammond!

**Pull request merged**
