### PR TITLE
repair includes for headers, based on creation of a module-map for clang

### PR DESCRIPTION
**Pull request by trws**
As part of a test for something else I tried modularizing RAJA, turns out that's less hard than I thought, but these include issues popped out as part of the process.  By way of a side note, a compilation of a minimal test file using modules turned out to be about six times faster than the classic header model.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
Modules in C++17 or riot!

More seriously, I'd be curious to see what that module map looks like

**Comment by trws** [comment]
See below, it's auto-generated then fixed up a bit, name this module.modulemap in include/RAJA and it just works.  The one funky part is leaving out the cuda headers, they would probably work with clang-cuda but they kill regular clang's module compilation so... probably a cmake preprocessing would be needed to actually include this in the repo.

```
// RAJA.modulemap
// Generated by: modularize -I=include -root-module=RAJA -block-check-header-list-only -module-map-path=RAJA.modulemap headers.txt

module RAJA {
    module index {
        module BaseSegment {
            header "index/BaseSegment.hpp"
                export *
        }
        module IndexSetBuilders {
            header "index/IndexSetBuilders.hpp"
                export *
        }
        module IndexSet {
            header "index/IndexSet.hpp"
                export *
        }
        module IndexSetSegInfo {
            header "index/IndexSetSegInfo.hpp"
                export *
        }
        module IndexSetUtils {
            header "index/IndexSetUtils.hpp"
                export *
        }
        module IndexValue {
            header "index/IndexValue.hpp"
                export *
        }
        module ListSegment {
            header "index/ListSegment.hpp"
                export *
        }
        module RangeSegment {
            header "index/RangeSegment.hpp"
                export *
        }
    }
    module internal {
        module DepGraphNode {
            header "internal/DepGraphNode.hpp"
                export *
        }
        module fault_tolerance {
            header "internal/fault_tolerance.hpp"
                export *
        }
        module ForallNPolicy {
            header "internal/ForallNPolicy.hpp"
                export *
        }
        module IndexArray {
            header "internal/IndexArray.hpp"
                export *
        }
        module index_sequence {
            header "internal/index_sequence.hpp"
                export *
        }
        module Iterators {
            header "internal/Iterators.hpp"
                export *
        }
        module LegacyCompatibility {
            header "internal/LegacyCompatibility.hpp"
                export *
        }
        module MemUtils_CPU {
            header "internal/MemUtils_CPU.hpp"
                export *
        }
        module RAJAVec {
            header "internal/RAJAVec.hpp"
                export *
        }
        module rangelist_forall {
            header "internal/rangelist_forall.hpp"
                export *
        }
        module ThreadUtils_CPU {
            header "internal/ThreadUtils_CPU.hpp"
                export *
        }
        module type_traits {
            header "internal/type_traits.hpp"
                export *
        }
    }
    module pattern {
        module forall {
            header "pattern/forall.hpp"
                export *
        }
        module forallN {
            header "pattern/forallN.hpp"
                export *
        }
        module permute {
            header "pattern/permute.hpp"
                export *
        }
        module reduce {
            header "pattern/reduce.hpp"
                export *
        }
        module scan {
            header "pattern/scan.hpp"
                export *
        }
        module tile {
            header "pattern/tile.hpp"
                export *
        }
    }
    module policy {
        module cilk {
            module forall {
                header "policy/cilk/forall.hpp"
                    export *
            }
            module policy {
                header "policy/cilk/policy.hpp"
                    export *
            }
            module reduce {
                header "policy/cilk/reduce.hpp"
                    export *
            }
            header "policy/cilk.hpp"
                export *
        }
        //module cuda {
        //    module forall {
        //        header "policy/cuda/forall.hpp"
        //            export *
        //    }
        //    module forallN {
        //        header "policy/cuda/forallN.hpp"
        //            export *
        //    }
        //    module MemUtils_CUDA {
        //        header "policy/cuda/MemUtils_CUDA.hpp"
        //            export *
        //    }
        //    module policy {
        //        header "policy/cuda/policy.hpp"
        //            export *
        //    }
        //    module raja_cudaerrchk {
        //        header "policy/cuda/raja_cudaerrchk.hpp"
        //            export *
        //    }
        //    module reduce {
        //        header "policy/cuda/reduce.hpp"
        //            export *
        //    }
        //    module scan {
        //        header "policy/cuda/scan.hpp"
        //            export *
        //    }
        //    header "policy/cuda.hpp"
        //        export *
        //}
        module MultiPolicy {
            header "policy/MultiPolicy.hpp"
                export *
        }
        module openmp {
            module forall {
                header "policy/openmp/forall.hpp"
                    export *
            }
            module forallN {
                header "policy/openmp/forallN.hpp"
                    export *
            }
            module policy {
                header "policy/openmp/policy.hpp"
                    export *
            }
            module reduce {
                header "policy/openmp/reduce.hpp"
                    export *
            }
            module scan {
                header "policy/openmp/scan.hpp"
                    export *
            }
            header "policy/openmp.hpp"
                export *
        }
        module PolicyBase {
            header "policy/PolicyBase.hpp"
                export *
        }
        module sequential {
            module forall {
                header "policy/sequential/forall.hpp"
                    export *
            }
            module policy {
                header "policy/sequential/policy.hpp"
                    export *
            }
            module reduce {
                header "policy/sequential/reduce.hpp"
                    export *
            }
            module scan {
                header "policy/sequential/scan.hpp"
                    export *
            }
            header "policy/sequential.hpp"
                export *
        }
        module simd {
            module forall {
                header "policy/simd/forall.hpp"
                    export *
            }
            module policy {
                header "policy/simd/policy.hpp"
                    export *
            }
            header "policy/simd.hpp"
                export *
        }
    }
    module util {
        module defines {
            header "util/defines.hpp"
                export *
        }
        module Layout {
            header "util/Layout.hpp"
                export *
        }
        module OffsetLayout {
            header "util/OffsetLayout.hpp"
                export *
        }
        module Operators {
            header "util/Operators.hpp"
                export *
        }
        module Permutations {
            header "util/Permutations.hpp"
                export *
        }
        module PermutedLayout {
            header "util/PermutedLayout.hpp"
                export *
        }
        module Timer {
            header "util/Timer.hpp"
                export *
        }
        module types {
            header "util/types.hpp"
                export *
        }
        module View {
            header "util/View.hpp"
                export *
        }
    }
}
```

**Comment by trws** [comment]
We could make a simpler version with directory globs, by the by, but this is what modularize decided to do so... :man_shrugging:

**Comment by DavidPoliakoff** [comment]
That's quite nice, I might look at what would be needed to generate it from CMake, I have a feeling we won't be the only ones who need this in the future

**Comment by trws** [comment]
Fair point, it gets that transitively but I have no issue adding it back as an explicit include.

**Comment by davidbeckingsale** [comment]
Yeah, I thought we were trying to move away from the transitive includes?

**Comment by davidbeckingsale** [comment]
But I guess every file is standalone, then a transitive include is fine.

**Comment by trws** [comment]
While a good goal, for this I had been going for "every header includes everything it needs to compile when included alone."

**Comment by davidbeckingsale** [comment]
Yup, I misunderstood. This is good!

**Pull request merged**
