### PR TITLE
try new logic for windows shared exports

### PR DESCRIPTION
**Pull request by cyrush**
# Summary

- The companion PR for this PR on a fork is: https://github.com/LLNL/RAJA/pull/1436
- Please review and approve https://github.com/LLNL/RAJA/pull/1436

### CODE REVIEW

**Comment by rhornung67** [comment]
@cyrush does this change fix your issue? If so, I will pull your fork branch into our repo so GitLab CI will run and it can be merged.

**Comment by cyrush** [comment]
Let me test one more time this afternoon on Windows.

**Comment by cyrush** [comment]
@rhornung67  This does allow me to build on windows. I still have an issue with the generated tests, but thats a mystery. I can try to open another ticket if I can collect enough useful details.

**Comment by rhornung67** [comment]
@cyrush thanks for the report.  I'll pull your branch into the RAJA repo and make a companion PR to run CI and merge.  Please post an issue if you have any info to report on the test generation.

**Pull request merged**
