### PR TITLE
Master

### PR DESCRIPTION
**Pull request by rhornung67**
Update develop branch after v0.7.0 release

### CODE REVIEW

**Comment by rhornung67** [comment]
@davidbeckingsale the release branch was merged into master with my last PR. This PR updates develop with the new release info. We only make release tags on master. So we have to merge master into develop after a release.

**Comment by davidbeckingsale** [comment]
That's not the process we have been using.  I think you should merge `v0.7.0-rc1` to develop, which should only really update the version numbers.

**Comment by rhornung67** [comment]
Then, how does the release tag get onto develop?

**Comment by davidbeckingsale** [comment]
It depends what you tagged... I've always been tagging the merge commit into master as the release, so the tags won't be on develop.

**Pull request closed without merging**
