### PR TITLE
limit parallel compile steps to 3

### PR DESCRIPTION
**Pull request by trws**
I'd like to see how long this takes to run in travis to see if we should tweak the limit, but we'll need to limit it to something not too far from this most likely.

### CODE REVIEW

**Comment by willkill07** [comment]
This actually appears faster with the job limit set to 3 O_o

**Comment by trws** [comment]
I'm a bit shocked, but yeah, I guess they were tromping over each other enough that it was actually slowing things down.

**Comment by willkill07** [comment]
I think this is sensible. 3 jobs at once isn't too restrictive and the build times seem reasonable. LGTM 👍

**Comment by rhornung67** [comment]
👍

**Pull request merged**
