### PR TITLE
Make uberenv a submodule and build external camp/blt TPLs

### PR DESCRIPTION
**Pull request by davidbeckingsale**
# Summary

- This PR updates the CI to:
  -  use uberenv as a submodule, rather than embedding it directly in the repo, and
  - use Spack to build external versions of camp and blt instead of pointing at the submodules.

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]

**Comment by kab163** [comment]
There were a few files that were deleted from uberenv - was that intentional? I've seen that in a few places now and it confuses me. @davidbeckingsale is that supposed to be like that?

**Comment by davidbeckingsale** [comment]
> There were a few files that were deleted from uberenv - was that intentional? I've seen that in a few places now and it confuses me. @davidbeckingsale is that supposed to be like that? (Since you're the author of this PR, I can't request your review lol)

Yup, the deleted files are because we changed from having those files in the repository, to being a submodule. It just looks a bit confusing on the diff.

**Comment by kab163** [comment]
The desul CI job needs some modification so that it can have "+desul+rocm" instead of "+desul+hip" - if the +rocm option is in there, other things conflict. Will need to look at this next week!

**Comment by kab163** [comment]
@davidbeckingsale , @rhornung67  this is ready for review!

**Comment by rhornung67** [comment]
@kab163 is this good to merge if it comes back all green?

**Comment by kab163** [comment]
> @kab163 is this good to merge if it comes back all green?

Yes! You'll have to push the button though :D

**Review by rhornung67 — APPROVED** [review]

**Pull request merged**
