### PR TITLE
Release version 0.4.0

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@rhornung67 - I had the base as `develop` by mistake. It's now `master`, can you check it again.

**Comment by davidbeckingsale** [comment]
I've added the #341 changes to this release.

**Comment by willkill07** [comment]
Should `nested::forall` be mentioned at all in the release notes?

**Comment by davidbeckingsale** [comment]
Yup, Rich is going to update the notes some time soon. We are then planning to track release notes directly in the repo, but haven’t made that switch yet.

**Comment by ajkunen** [comment]
can we get the stride-1 PR in too?

**Comment by davidbeckingsale** [comment]
Nope. The release branch had been finalized and merged to master. We can make another release next week though.

**Comment by rhornung67** [comment]
I already updated the notes. I didn't see anything major in there -- just documentation updates, a few minor fixes, etc. since the v0.3.1 release a couple of weeks ago.

@willkill07 I didn't see anything about nested::forall in the commits in this PR. If you know of some things worth mentioning, please let me know.

**Comment by davidbeckingsale** [comment]
@rhornung67 this branch does include the `nested` stuff.

**Comment by rhornung67** [comment]
OK. I'll read through the commits again and change the notes as needed.  Won't get to it until tomorrow morning.

**Comment by davidbeckingsale** [comment]
No problem.

**Pull request merged**
