### PR TITLE
Update rocmcc

### PR DESCRIPTION
**Pull request by adrienbernede**
# Summary

This PR updates rocmcc to 5.5.x version on corona and tioaga.

### CODE REVIEW

**Comment by adrienbernede** [comment]
@rhornung67 Ready to go, when tests pass.

**Comment by rhornung67** [comment]
@adrienbernede we're going to merge https://github.com/LLNL/RAJA/pull/1334 before this PR. Is that OK with you? I will merge develop into this

**Comment by adrienbernede** [comment]
@rhornung67 ready to go.

**Comment by rhornung67** [comment]
@adrienbernede I would like to get this https://github.com/LLNL/RAJA/pull/1516 in first since it resolves several issues. OK with you?

**Comment by adrienbernede** [comment]
@rhornung67 closing in favor of #1527

**Pull request closed without merging**
