### PR TITLE
Improve error messages from algorithm span API

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary
Call the final API method instead of calling other intermediate API methods in scan, sort, and forall. This avoids very long error messages caused by no longer supported argument sets. Specifically this replaces the error manifesting as an infinite template recursion with an error noting that no overload matches the arguments.

This will conflict with #1054, I'll fix up the conflicts.

- This PR is a bugfix
- It does the following (modify list as needed):
  - Fixes (issue number(s))

### CODE REVIEW

**Comment by trws** [comment]
This looks like it's mainly annotating the specific namespace to use, which compiler does it improve errors for?

I'm good with making the change, though if they're going to become qualified names, it would probably be best to make them fully qualified.  We'll need to do some of that at some point anyway defensively, but if you're already touching all of these adding the `::RAJA::` on the front to finish it out would help move that along.

**Comment by MrBurmark** [comment]
Not quite, previously the non-resource policy by template versions called the resource policy by template version. The main offender was nvcc.

Sure, that's pretty easy to add for these.

**Review by artv3 — APPROVED** [review]
Thanks! I think I ran into this when trying out the latest RAJA in my application. This will greatly help!

**Comment by rhornung67** [comment]
@MrBurmark is this good to merge?

**Comment by MrBurmark** [comment]
Sure, I'll merge it if I get another approve.

**Review by rhornung67 — APPROVED** [review]

**Pull request merged**
