### PR TITLE
Support types other than int for Index_type

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This lets other types work for `Index_type`. We were previously mixing usage of `Index_type` and `int`, which meant that changing that typedef caused compile errors.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@rhornung67 can you take a look at this?

**Comment by davidbeckingsale** [comment]
Okay, I've made `int` the default again. The main point of this branch was to ensure that other types _do_ work, not that we ought to use one or the other.

**Comment by rhornung67** [comment]
I wasn't suggesting that we don't change it to long. Just that we need to pay attention to this sort of thing. Would it be better to make the index type and double type a compile-time choice via a CMake option, so users don;t have to hunt around and edit our header files?

**Comment by davidbeckingsale** [comment]
Yup, I can make it a compile time choice. We really need to come up with a better way to determine what are install-time choices and what are compile-time choices.

**Comment by tomdeakin** [comment]
This has come up with some work with between us and Intel on GPU-STREAM. We found we needed to use `long` in the lambda argument, i.e. `forall<policy>(index_set, [=] RAJA_DEVICE (long index)` instead of `forall<policy>(index_set, [=] RAJA_DEVICE (int index)` to regain some of the performance gap between it and C STREAM.

Shouldn't the iterator type be determined at user code compiler time based on what type they used in their lambda?

**Comment by rhornung67** [comment]
@davidbeckingsale let's discuss this today if you have time and figure out how we should handle this since it has come up before.

**Comment by willkill07** [comment]
@tomdeakin The only issue with that is that the passed `index_set` into `forall` would need to be constructed with the same type as the lambda. I'm not aware of that being possible within the library semantics of RAJA, but it could be facilitated by adding template parameters to `RangeSegment`, `RangeStrideSegment`, and friends.

Advantages: 
* `RAJA::RangeSegment{0, static_cast<long>(std::numeric_limits<int>::max()) + 1}` would work right out of the box
* Querying the index_type of a given RAJA Iterable would still be possible: e.g. `typename decltype(index_set)::index_type`
** though I'd argue to add a type_trait to make it less eye-gouging: `RAJA::index_type_of`

Disadvantages:
* This -could- *will* allow the programmer to easily shoot themselves in the foot.
** Specifically, construction of `RangeSegments` within `IndexSet` at different times could yield mix-typed `Segments` stored within
** This could be avoided with an `enable_if` affixed to the `IndexSet` add to ensure the index_type is consistent, but I'm sure there are use cases where the `IndexSet` could be `int` while the `RangeSegments` within could be `long`
* Code size increase due to specialization/inlining

Arguable:
* The dependence on `RAJA::Index_type` would most likely go away
* Automatic inlining due to C++ compilers inlining short template functions (none of which are really long with `*Segment` or `IndexSet`)

**Comment by tomdeakin** [comment]
I think we're getting mixed types any way, using `int` in the lambda and whatever `RAJA::Index_type` is set to when the policy is constructed - we don't specify types when we do the following:
```
unsigned int array_size = 1024;
RAJA::RangeSegment seg(0, array_size);
RAJA::IndexSet index_set;
index_set.push_back(seg);
forall<policy>(index_set, [=] RAJA_DEVICE (int index) {});
```
So the programmer has already shot themselves in the foot without knowing.

**Comment by davidbeckingsale** [comment]
We will add this to our roadmap and try and figure out a way to support this.

I'm not sure I agree with the "shooting in the foot without knowing" when using `int` in the lambda though. `RAJA::Index_type` is provided as a typedef for the indices. If you don't use it, then that's too bad 😄

**Comment by tomdeakin** [comment]
Should we be using `forall<policy>(index_set, [=] RAJA_DEVICE (RAJA::Index_type index) {});` instead then?

The `pi.cxx` example that ships with RAJA uses `int` for the index type, as does LULESH in the RAJA-examples repo. These are the canonical RAJA examples as there is no programming guide, so it feels *as a user* that using `int` is the recommended approach.

**Comment by davidbeckingsale** [comment]
I agree with that. That is a hangover from `Index_type` being an `int`. So they have been treated interchangeably in the code base. These usages were the main thing I had to refactor when adding the support for `long` in this PR.

Using `Index_type` as the lambda argument is a good idea since it will give you consistentcy, and the flexibility to change the index type is one place.

**Pull request merged**
