### PR TITLE
Don't use alignx when CUDA is enabled

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
I forgot to bring this up at the meeting, but do we want to merge this temporary fix?

**Comment by rhornung67** [comment]
I think we should merge something, but I'm not sure which is better, one macro or two (see my earlier comment above).  Wanna pull Adam and Jason into the PR as reviewers?

**Comment by davidbeckingsale** [comment]
Sure thing!

**Comment by MrBurmark** [comment]
I don't see any places where this is used in device code.

**Comment by rhornung67** [comment]
@MrBurmark it's not used in device code. But, it breaks the xl compiler when you use it as the host compiler with nvcc. Hopefully, this will be fixed. I'm finding a variety of other issues with the xl compiler....

**Comment by davidbeckingsale** [comment]
Do we want to merge this? @rhornung67

**Comment by rhornung67** [comment]
@davidbeckingsale probably. Is this something we should report to IBM?

**Comment by davidbeckingsale** [comment]
I think @mcordery may have done that. Matt - have you reported this internally?

**Pull request merged**
