### PR TITLE
Fix cmake cache issue with cuda and omp

### PR DESCRIPTION
**Pull request by trws**
Switch to a non-cache variable to aggregate flags before setting a cache value we use to set CUDA_NVCC_FLAGS, also use the per-build-type cuda variables to factor out some of the duplication.

This version still re-runs cmake after the first make, there seems to be an extra dependency we need to remove, but it resolves the openmp flag issue.

```
Re-run cmake file: Makefile older than: test/unit/cpu/CMakeFiles/test-scan.exe.dir/test-scan.exe_generated_test-scan.cpp.o.depend
```

### CODE REVIEW

**Comment by trws** [comment]
Ugh... yay nvidia, this is expected behavior for FindCUDA.cmake https://cmake.org/pipermail/cmake/2011-January/042173.html

**Comment by davidbeckingsale** [comment]
"Expected behavior" that's just great :(

**Comment by trws** [comment]
Hrm... wondering whether I should have merged this yet.  @rhornung67, if this causes any issues for you let me know, I think I tested all the cases but could well be wrong.

**Comment by davidbeckingsale** [comment]
@rhornung67 and I were already debugging something like this with BLT and the performance suite, so this should help. Thanks.

**Comment by rhornung67** [comment]
@davidbeckingsale if you push changes into the feature/blt branch and want me to try it again, please let me know.  @trws thanks for clearing up some (hopefully most) of this.

**Pull request merged**
