### PR TITLE
Allow CUDA Standard 14

### PR DESCRIPTION
**Pull request by jonesholger**
BLUEOS CUDA11 needs C++ standard 14 for thrust/cub

Quick fix in SetupCompilers.cmake CMAKE_CUDA_STANDARD is cache variable

Exercised with new blueos_nvcc11_gcc8.3.1.sh script. Verbose on to verify compile commands

-----------------------------------------------------------------------
Other issue or considerations

There is a Todo to propagate CMAKE_CXX_STANDARD into BLT_CXX_STANDARD
but noticed this comment in #699 
 #TODO set BLT_CXX_STD
 #NOTE @trws: did not do this as it does not behave correctly 

If RAJA automatically detects CXX standard then it would be useful to propagate BLT_CXX_STD  or RAJA_BLT_CXX_STD as property in export interface for client applications.  I may look at this closer and open an issue if progress can be made.

Independently the camp resource test fails; but it did for cuda10 too under gcc8.3.1. Undefined references to OMP symbols

### CODE REVIEW

**Comment by trws** [comment]
Looks like the right change to me.  It seems a bit odd that it's just the blueos one, do we need this for nvcc11 on the other platforms?  I don't remember hitting it when I tested with nvcc11, but it's possible I was building with 14 anyway at the time.

**Comment by jonesholger** [comment]
I just noticed blueos first. But, it's likely to be needed for other platforms unless you're hooking into an older version of thrust. Also, I'll keep an eye on

https://github.com/thrust/thrust/issues/1200

**Comment by MrBurmark** [comment]
Is this good to go?

**Comment by trws** [comment]
Needs an update, but otherwise I'd approve it.

**Comment by rhornung67** [comment]
Merged to latest develop. CI is running....

**Pull request merged**
