### PR TITLE
merge master back into develop

### PR DESCRIPTION
**Pull request by trws**
Is this what you had in mind @davidbeckingsale?

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
I meant your bug fix branch to develop, but this would be fine and supersedes my merge of the 0.4.0 release branch to develop.

**Comment by trws** [comment]
I went this way because the bugfix branch had all of this same stuff in it to make sure that it followed from master.  If it doesn't cause a problem this seemed to more clearly reflect what we're doing.

**Comment by davidbeckingsale** [comment]
This only failed because the stride-1 stuff was merged to develop before we sorted this out.

**Comment by ajkunen** [comment]
@davidbeckingsale sorry about that, I should have waited

**Comment by davidbeckingsale** [comment]
It doesn't matter. Merging the bugfix branch into both develop and master is a more robust solution anyway.

**Pull request closed without merging**
