### PR TITLE
Feature/docker

### PR DESCRIPTION
**Pull request by DavidPoliakoff**
Hey folks, adding a template Dockerfile to the repo.

You can build this pretty easily and start working with RAJA anywhere Docker exists. CUDA programs will only run successfully if the host docker runs on is configured specially, but those programs can compile and link, and all other programs should work.

Zero urgency on this PR, I just use this Dockerfile anyway, thought I'd share it

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
This is pretty cool. I would suggest changing the maintainer to raja-dev if we are going to merge this?

**Comment by DavidPoliakoff** [comment]
Fixed, thanks for that

**Comment by davidbeckingsale** [comment]
I'm happy with this, but we should probably get more of a consensus before merging.

**Comment by DavidPoliakoff** [comment]
Sure thing, it's zero urgency.

@trws : I'd guess you're the most likely to have used Docker in the past, anything you see that's iffy?
@rhornung67 : you okay with having another file in the root directory? That's pretty standard practice for people shipping Docker containers, but about half the people downloading the repo might say "what on earth is this?"

**Comment by trws** [comment]
It looks just fine to me.

**Pull request merged**
