### PR TITLE
Fixup builds with MSVC

### PR DESCRIPTION
**Pull request by davidbeckingsale**
Brings in bits from #101 and @trws [trws/windows/portability](https://github.com/LLNL/RAJA/tree/feature/trws/windows-portability) branch.

Adds additional fixes for using GoogleTest with Visual Studio.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@trws I started a new branch with this stuff since merging develop into your branch ended up in a bit of a mess.

**Comment by trws** [comment]
Sounds good to me.  Looks like it built too, but ran into an issue with my test script on appveyor.  I fixed the script and re-started the build just now.

**Comment by davidbeckingsale** [comment]
Nice one, thanks. I'm running into a runtime issue, I think it's the aligned_free stuff that Peter needed - I'm just adding that.

**Comment by trws** [comment]
Sounds good.  It took another tweak, but the appveyor output should be meaningful now, looks like two out of six tests pass with the current version. =)

**Comment by davidbeckingsale** [comment]
Fixed that issue. There is something going on with one of the nested tests though, one of the nested policies with tiling is failing:

    typedef NestedPolicy<ExecList<seq_exec,
                                 seq_exec,
                                 omp_collapse_nowait_exec,
                                 omp_collapse_nowait_exec>,
                        OMP_Parallel<Tile<TileList<tile_none,
                                                   tile_none,
                                                   tile_none,
                                                   tile_fixed<16>>,
                                          Permute<PERM_LKIJ,
                                                  Execute  // implicit
                                                 >>>>
        EXEC;

**Comment by davidbeckingsale** [comment]
@trws This is looking good. I think some of your changes introduced warnings which is why the Travis build fails. The appveyor build fails because it looks like some changes have been overwritten. We need a couple of changes to how Google Test is linked in on Windows: https://github.com/LLNL/RAJA/pull/145/commits/7ad89088cde188cfb2026a2f0be42b506fc07190

**Comment by trws** [comment]
Thanks @davidbeckingsale, I'm hoping with that link fix back in this may do it.  The scan tests were blowing up in the tuple flattener before, that seems to be addressed, but it was still choking on the linker.  @willkill07, what do you think of just factoring out the flattener like this? It's less general I'll freely admit, but has the same behavior for all existing uses of the product class.  Unfortunately, even though they now compile just fine, the scan tests throw a runtime exception on windows. ><

**Comment by trws** [comment]
*sighs* It looks like we may be having issues with clang+travis as well.

This version passes everything but scan-tests on windows, and even that builds with MSVC 2014, and all gcc tests on travis, clang tests locally.  Do we have a good story for disabling a feature on a specific platform? We may just want to ignore scan failures for the time being, at least on appveyor.

**Comment by DavidPoliakoff** [comment]
Re: "do useless things to appease warning on memalign," I bet you could suss out which projects have continuous integration by looking through their commits for comments on memalign, or just seeing if they handle that error. Fun way to extract hidden info.

**Comment by davidbeckingsale** [comment]
The best way I can think of is to add an option `RAJA_ENABLE_SCAN` and have it turned off if the compiler is MSVC.

**Comment by davidbeckingsale** [comment]
I think it would be good to get this merged. How about just guarding the scan test and disabling it if building with MSVC? @trws

**Comment by trws** [comment]
I at least wanted the compilation fixed, which it now is, but tracking down the runtime error will be much more complicated without a local development environment.  I'd be for filing an issue on it and moving on.  It will be nice to have the board actually light green on PRs too.

**Comment by DavidPoliakoff** [comment]
👍 , green PRs a go

**Comment by rhornung67** [comment]
@davidbeckingsale and others, please delete the branches after PR merges or closures if you won't need them any longer. Thanks.

**Comment by trws** [comment]
Cleared.  For the record, https://github.com/LLNL/RAJA/branches/yours 
will show you all of your branches, highlighting the ones that have been 
merged and offering a nice bright red trashcan to kill them off.

**Comment by DavidPoliakoff** [comment]
That's a really useful link, thanks @trws

**Pull request merged**
