### PR TITLE
Renew CI specs per LLNL/radiuss-shared-ci#15

### PR DESCRIPTION
**Pull request by adrienbernede**
This PR is the counterpart of
https://github.com/LLNL/CHAI/pull/218
https://github.com/LLNL/Umpire/pull/813

It is meant to switch to the new specs in the shared CI as specified in
https://github.com/LLNL/radiuss-shared-ci/issues/15

It also updates the CI on ruby to the new toss4 software stack.

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
Does the ordering really make a difference? If so, that is not good and we should report to Spack team.

**Comment by adrienbernede** [comment]
Recent fix: I had added gcc toolchain flag to the oneapi target, and it caused the build to fail with an error typical to an outdated c++ library.
That was confusing because the gcc toolchain is typically used to fix those.

In the end, I just had to revert that change: the build is fine without the gcc toolchain, I added it simultaneously to other targets (typically intel ones) but it was a mistake to assume that oneapi could need it too.

**Comment by adrienbernede** [comment]
@rhornung67 what I found however is that there isn’t really a oneapi@2022.3 on LC: the directory exists, but it points to oneapi@2022.2.

I realized that when Spack couldn’t find the 2022.3 even with the associated module loaded.

My question is: shouldn’t we explicitly use 2022.2?

**Comment by adrienbernede** [comment]
Running again in random failures of the asan job...

**Comment by rhornung67** [comment]
> @rhornung67 what I found however is that there isn’t really a oneapi@2022.3 on LC: the directory exists, but it points to oneapi@2022.2.
> 
> I realized that when Spack couldn’t find the 2022.3 even with the associated module loaded.
> 
> My question is: shouldn’t we explicitly use 2022.2?

Right. I noticed that a while back as well. Yes, let's use 2022.2 explicitly if that is the latest version.

Also, do you understand what is going on with the GItLab CI here. Is something wrong with the script that drives CI on ruby? I've never seen this error before.

**Comment by adrienbernede** [comment]
@rhornung67 I’m gonna make the switch to 2022.2

The CI issue is an easy fix, I’ll take care of it (and point to the new radiuss shared ci release.)

Yes, Tioga is out today. I seized the opportunity to improve the management of machines out in the Shared CI.

This should be up and running tomorrow.

**Comment by rhornung67** [comment]
@adrienbernede thanks for the response. I made a bunch of comments on https://github.com/LLNL/RAJAPerf/pull/254 and asked others to look at it. When approved, we can merge it and move on to the next PR.

**Comment by adrienbernede** [comment]
Done.
Tioga still out. Asan still failing randomly...

**Comment by adrienbernede** [comment]
Here is what happens when ignoring a leak:

```
        Start 475: test-algorithm-sort-OpenMP.exe
475/522 Test #475: test-algorithm-sort-OpenMP.exe ...........................................***Failed    0.06 sec
Running main() from /dev/shm/lassen378-1127945/clang-14.0.5/blt-0.5.2-gzvg5l6vvt6hhtpj4kp4ou37ljovtnf4/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest_main.cc
[==========] Running 6 tests from 6 test suites.
[----------] Global test environment set-up.
[----------] 1 test from OpenMPTest/SortUnitTest/0, where TypeParam = camp::list<PolicySort<RAJA::PolicyBaseT<(RAJA::Policy)4, (RAJA::Pattern)1, (RAJA::Launch)0, (camp::resources::v1::Platform)1, RAJA::policy::omp::Parallel, RAJA::wrapper<RAJA::policy::omp::omp_for_schedule_exec<RAJA::policy::omp::Auto> > > >, camp::resources::v1::Host, long, camp::integral_constant<long, 10000l> >
[ RUN      ] OpenMPTest/SortUnitTest/0.UnitSort
AddressSanitizer:DEADLYSIGNAL
=================================================================
AddressSanitizer:DEADLYSIGNAL
==12648==ERROR: AddressSanitizer: SEGV on unknown address 0xbebebebebebebebc (pc 0xbebebebebebebebc bp 0x2200160af0b0 sp 0x7fffffff1270 T0)
==12648==The signal is caused by a UNKNOWN memory access.
AddressSanitizer:DEADLYSIGNAL
AddressSanitizer: nested bug in the same thread, aborting.
```

**Comment by adrienbernede** [comment]
Full reproducer:

```
working_dir="/usr/workspace/${USER}/RAJA/276863-$(date +%s)"
mkdir -p ${working_dir} && cd ${working_dir} 
git clone https://github.com/LLNL/RAJA.git --single-branch --depth=1 
cd RAJA
git fetch origin --depth=1 1ca7a911ce678e7191a810e2d03f8dcdb99e85d0 
git checkout 1ca7a911ce678e7191a810e2d03f8dcdb99e85d0 
git submodule update --init --recursive
suppressions=$(pwd)/suppressions.asan
SPEC=" ~shared +openmp +tests %clang@14.0.5 cxxflags==\"-fsanitize=address\" " MODULE_LIST="" lalloc 1 -W 60 ./scripts/gitlab/build_and_test.sh
```

**Comment by rhornung67** [comment]
> Here is what happens when ignoring a leak:
> 
> ```
>         Start 475: test-algorithm-sort-OpenMP.exe
> 475/522 Test #475: test-algorithm-sort-OpenMP.exe ...........................................***Failed    0.06 sec
> Running main() from /dev/shm/lassen378-1127945/clang-14.0.5/blt-0.5.2-gzvg5l6vvt6hhtpj4kp4ou37ljovtnf4/thirdparty_builtin/googletest-master-2020-01-07/googletest/src/gtest_main.cc
> [==========] Running 6 tests from 6 test suites.
> [----------] Global test environment set-up.
> [----------] 1 test from OpenMPTest/SortUnitTest/0, where TypeParam = camp::list<PolicySort<RAJA::PolicyBaseT<(RAJA::Policy)4, (RAJA::Pattern)1, (RAJA::Launch)0, (camp::resources::v1::Platform)1, RAJA::policy::omp::Parallel, RAJA::wrapper<RAJA::policy::omp::omp_for_schedule_exec<RAJA::policy::omp::Auto> > > >, camp::resources::v1::Host, long, camp::integral_constant<long, 10000l> >
> [ RUN      ] OpenMPTest/SortUnitTest/0.UnitSort
> AddressSanitizer:DEADLYSIGNAL
> =================================================================
> AddressSanitizer:DEADLYSIGNAL
> ==12648==ERROR: AddressSanitizer: SEGV on unknown address 0xbebebebebebebebc (pc 0xbebebebebebebebc bp 0x2200160af0b0 sp 0x7fffffff1270 T0)
> ==12648==The signal is caused by a UNKNOWN memory access.
> AddressSanitizer:DEADLYSIGNAL
> AddressSanitizer: nested bug in the same thread, aborting.
> ```

@MrBurmark does this look familiar to you?

**Comment by rhornung67** [comment]
> @jonesholger, here is an example of the leak caught by ASAN. I am instructing asan to ignore libxlsmp. Could this leak after RAJA or codes using it? Maybe...
> 
> ```
>         Start   2: blt_openmp_smoke
>   2/522 Test   #2: blt_openmp_smoke .........................................................***Failed    0.20 sec
> 
> My thread id is: 0
> Num threads is: 4
> Max threads is: 4
> 
> My thread id is: 2
> Num threads is: 4
> Max threads is: 4
> 
> My thread id is: 1
> Num threads is: 4
> Max threads is: 4
> 
> My thread id is: 3
> Num threads is: 4
> Max threads is: 4
> llvm-symbolizer: Unknown command line argument '--inlines'.  Try: '/usr/bin/llvm-symbolizer -help'
> llvm-symbolizer: Did you mean '-inlining'?
> ==56361==WARNING: Can't read from symbolizer at fd 5
> llvm-symbolizer: Unknown command line argument '--inlines'.  Try: '/usr/bin/llvm-symbolizer -help'
> llvm-symbolizer: Did you mean '-inlining'?
> ==56361==WARNING: Can't read from symbolizer at fd 5
> llvm-symbolizer: Unknown command line argument '--inlines'.  Try: '/usr/bin/llvm-symbolizer -help'
> llvm-symbolizer: Did you mean '-inlining'?
> ==56361==WARNING: Can't read from symbolizer at fd 5
> llvm-symbolizer: Unknown command line argument '--inlines'.  Try: '/usr/bin/llvm-symbolizer -help'
> llvm-symbolizer: Did you mean '-inlining'?
> ==56361==WARNING: Can't read from symbolizer at fd 5
> ==56361==WARNING: Failed to use and restart external symbolizer!
> 
> =================================================================
> ==56361==ERROR: LeakSanitizer: detected memory leaks
> 
> Direct leak of 32 byte(s) in 1 object(s) allocated from:
>     #0 0x100bbdcc  (/dev/shm/lassen385-1125514/build_lassen-blueos_3_ppc64le_ib_p9-clang@14.0.5-ebc4we75/tests/blt_openmp_smoke+0x100bbdcc)
>     #1 0x20000032b25c  (/lib64/libpthread.so.0+0xb25c) (BuildId: ef37c99e38407286a17c9cdb6b158ecb6871e50f)
>     #2 0x2000003ff7a8  (/usr/tce/packages/xl/xl-2022.08.19/lib/libxlsmp.so.1+0x3f7a8)
>     #3 0x2000007b91f0  (/usr/tce/packages/xl/xl-2022.08.19/lib/libxlsmp.so.1+0x3f91f0)
>     #4 0x2000004b7310  (/usr/tce/packages/xl/xl-2022.08.19/lib/libxlsmp.so.1+0xf7310)
>     #5 0x20000067f0c4  (/usr/tce/packages/xl/xl-2022.08.19/lib/libxlsmp.so.1+0x2bf0c4)
>     #6 0x10114b78  (/dev/shm/lassen385-1125514/build_lassen-blueos_3_ppc64le_ib_p9-clang@14.0.5-ebc4we75/tests/blt_openmp_smoke+0x10114b78)
>     #7 0x2000008752fc  (/lib64/libc.so.6+0x252fc) (BuildId: 331b490ddc9720579d25ccaf0db72ea0536a8d01)
>     #8 0x2000008754f0  (/lib64/libc.so.6+0x254f0) (BuildId: 331b490ddc9720579d25ccaf0db72ea0536a8d01)
> 
> SUMMARY: AddressSanitizer: 32 byte(s) leaked in 1 allocation(s).
> llvm-symbolizer: Unknown command line argument '--inlines'.  Try: '/usr/bin/llvm-symbolizer -help'
> llvm-symbolizer: Did you mean '-inlining'?
> ```

@white238 do you test BLT with address sanitizer?

**Comment by rhornung67** [comment]
@adrienbernede does it make sense to turn off address sanitizer for now, get all the GitLab CI PRs merged. Then circle back to asan?

**Comment by adrienbernede** [comment]
@rhornung67 Yes it does make sense, I’ll deactivate the job for now.

**Comment by MrBurmark** [comment]
That segv did not look familiar to me.

**Comment by rhornung67** [comment]
> There are some intentional memory leaks in RAJA for memory pools.

Can the leaks be removed?  I added https://github.com/LLNL/RAJA/issues/1469 to keep track of this.

**Comment by rhornung67** [comment]
@adrienbernede it looks like the ruby Spack specs are not correct. The machine has been upgraded to RHEL 8.  We're working on a fix for the lassen CUDA errors coming from camp.

**Comment by adrienbernede** [comment]
> @adrienbernede it looks like the ruby Spack specs are not correct. The machine has been upgraded to RHEL 8. We're working on a fix for the lassen CUDA errors coming from camp.

I indeed noticed the change of OS. I’ll update the radiuss-spack-configs

**Comment by rhornung67** [comment]
lassen will also be upgraded to RHEL8 soon. I don't know what issues we will run into with that, but we need to get the CUDA issue coming from camp sorted first. We know a fix, but need to see if there is a better way.

**Comment by rhornung67** [comment]
@adrienbernede Camp main was changed which should re-enable GitLab CI on lassen. I restarted several PRs

**Pull request merged**
