### PR TITLE
Add kernel names in forall tests

### PR DESCRIPTION
**Pull request by artv3**
This PR will add further testing to the kernel naming API found in RAJA::forall.

### CODE REVIEW

**Comment by MrBurmark** [comment]
Is the kernel name exposed to plugins?

**Comment by artv3** [comment]
> Is the kernel name exposed to plugins?

I don't think so.

**Comment by MrBurmark** [comment]
> > Is the kernel name exposed to plugins?
> 
> I don't think so.

Something we could think about during our next meeting.

**Review by rchen20 — APPROVED** [review]

**Comment by artv3** [comment]
Did others want to review? or is this good to go when green?

**Review by adayton1 — APPROVED** [review]
LGTM

**Comment by MrBurmark** [comment]
This is just testing the mechanics, right? There are no things that actually use/test the fact that the loops are named?

**Comment by rchen20** [comment]
> This is just testing the mechanics, right? There are no things that actually use/test the fact that the loops are named?

Yes, we just want to make sure it compiles correctly, and avoid problems like in #1699. Previously, the kernel names were only used in examples/forall-param-reductions.cpp, and this would make sure there are some automated builds of kernelname.

**Comment by artv3** [comment]
> > This is just testing the mechanics, right? There are no things that actually use/test the fact that the loops are named?
> 
> Yes, we just want to make sure it compiles correctly, and avoid problems like in #1699. Previously, the kernel names were only used in examples/forall-param-reductions.cpp, and this would make sure there are some automated builds of kernelname.

Right, at the moment we only support ROCTX/NVTX -- an area of future investigation is how to better integrate with profiling tools that allow kernel naming.

**Review by MrBurmark — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]

**Pull request merged**
