### PR TITLE
Update desul

### PR DESCRIPTION
**Pull request by mdavis36**
# Summary

- This PR is a bugfixq
- It updates to the latest commit of desul and fixes some API changes. This is brings in fixes for using an installed version of RAJA/desul that were previously broken.

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
Thank you @mdavis36

**Comment by rhornung67** [comment]
@mdavis36 adding a few more reviewers. I would like @trws to approve before merging.

**Review by MrBurmark — APPROVED** [review]

**Comment by mdavis36** [comment]
@rhornung67 I need to leave the branch open for this for work I'm doing on Spheral. I will delete it when things are tidied up again

**Comment by rhornung67** [comment]
Sorry about that. I thought you were done with it.

**Pull request merged**
