### PR TITLE
Turn on Windows & Mac tests.

### PR DESCRIPTION
**Pull request by mdavis36**
# Summary

- This PR is a bugfix...
- It enables tests of Windows and Mac builds on Azure

### CODE REVIEW

**Comment by rhornung67** [comment]
It looks like the windows tests passed/will pass.  Mac tests are still commented out.

**Comment by rhornung67** [comment]
It looks like we need to adjust the timer test for Mac. It ran, but the timings were outside of the tolerance we have hard-coded in the test.  If this is too hard to get right, we could omit that test for azure. Better, let it run, but allow failure if we can do that.

**Comment by mdavis36** [comment]
@rhornung67 Running the tests natively on my mac passed so I think we should go ahead and omit them

**Comment by rhornung67** [comment]
> @rhornung67 Running the tests natively on my mac passed so I think we should go ahead and omit them

Let me noodle with it and see if I can make it work.

**Comment by mdavis36** [comment]
@rhornung67 This is coming back green now.

**Review by rhornung67 — APPROVED** [review]
Great. So the test tweak worked.

**Pull request merged**
