### PR TITLE
Don't cache LLVM files in Travis

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@rhornung67 - this should reduce the cache sizes for builds. Let's see if it increases build times significantly before we merge.

**Comment by rhornung67** [comment]
@davidbeckingsale this change breaks the clang builds.  Should we leave it as it was and dig into it only if the issue reappears?

**Comment by davidbeckingsale** [comment]
@rhornung67 - I've hopefully fixed that problem. If this works, let's merge. The travis guidelines for caching say that it's not a good idea for a large download anyway, since the download still has to be made from the cache server.

**Comment by rhornung67** [comment]
@davidbeckingsale travis is still running and what has run has passed. Appveyor failed. What's up with that?

**Comment by davidbeckingsale** [comment]
It's probably the "Previous" visual studio thingy 😞

**Comment by rhornung67** [comment]
Can we specify a specific build to use in appveyor?  Travis passed.

**Comment by davidbeckingsale** [comment]
I don't think so, but hopefully this will fix it.

**Pull request merged**
