### PR TITLE
Fix View pointer type.

### PR DESCRIPTION
**Pull request by rchen20**
# Summary

- This PR is a bugfix
- It does the following:
  - Fixes https://github.com/LLNL/Kripke/pull/30 and https://github.com/LLNL/Kripke/pull/32
  - The CHAI ManagedArray type was not being passed through to View. Instead, the raw pointer type was being used. This caused missing CHAI memory transfers. (Thanks @vsrana01 @davidbeckingsale!)
  - Note: For RAJA v0.14.0 and Kripke (and https://github.com/LLNL/RAJAProxies/pull/23), need to use internal::ViewBase to work around this problem. RAJA v0.15.0 should be able to use this current fix.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
This looks good to me. Do you think we should also expose PointerType in the TypedView? https://github.com/LLNL/RAJA/blob/28a1e441eda23c584b4e68edb58888bbef86e3b3/include/RAJA/util/View.hpp#L59

I cannot remember if we used to in previous releases. In CHAI, we currently use TypedViewBase to provide this functionality.

**Comment by ajkunen** [comment]
@rchen20 @davidbeckingsale I think the issue with exposing the pointer type in TypedView was the variadic template list.  Perhaps we should have another TypeView alias... like TypedViewP that takes the type list as a camp::list, and provides the PointerType defaulted like View.
Something like:   
`template <typename ValueType, typename LayoutType, typename IndexTypes, typename PointerType = ValueType*>
using TypedViewP =
    internal::TypedViewBase<ValueType, PointerType, LayoutType, IndexTypes >;`

**Comment by rchen20** [comment]
> This looks good to me. Do you think we should also expose PointerType in the TypedView?
> 
> https://github.com/LLNL/RAJA/blob/28a1e441eda23c584b4e68edb58888bbef86e3b3/include/RAJA/util/View.hpp#L59
> 
> I cannot remember if we used to in previous releases. In CHAI, we currently use TypedViewBase to provide this functionality.

When I looked at RAJA v0.10.0 yesterday, TypedViewBase was not exposed to PointerType, but I can add that in for good measure.

**Comment by davidbeckingsale** [comment]
We should add that to RAJA and to CHAI. We can work with @kab163 to set this up.

**Pull request merged**
