### PR TITLE
add gcc8, update clang debug target, remove old clang and intel targets

### PR DESCRIPTION
**Pull request by trws**

### CODE REVIEW

**Comment by trws** [comment]
I'm going to re-start the tests, the new gcc8 image is an ubuntu bionic base, completely new base image, that will include the gcc offload support on nvptx in case we want to try that.

**Comment by davidbeckingsale** [comment]
Awesome!

**Comment by trws** [comment]
Ouch, looks like the clang 6 updated address sanitizer is finding something suspicious in kernel collapse... will look into that shortly.

**Comment by trws** [comment]
Ok, newly found "bug" fixed.  New gcc8 in, icc16 and clang4 out.  LGTM?

**Pull request merged**
