### PR TITLE
[DNM] testing PR

### PR DESCRIPTION
**Pull request by trws**

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/LLNL/RAJA/pull/69" target="_blank">ReviewNinja

**Comment by ajkunen** [comment]
Hmm,

This hosed my browser :)

-Adam

**Comment by trws** [comment]
Uh... that's not promising, what happened?

**Comment by rhornung67** [comment]
I was able to give ReviewNinja authorization for my account.  But, then I got stuck in an “unresponsive script” dialogue. After I clicked ’stop script’ a couple of times, I was able to see your code changes.  That’s as far as I got.  I have a meeting  now.

**Pull request closed without merging**
