### PR TITLE
Rework test structure to reduce build times.

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR is intended to get feedback on one way that we can significantly reduce RAJA test build times for some compilers. The PR covers only one test directory. If folks are OK with this, or have suggestions for improving it, I will work whatever we agree on into the other tests.
- It's not ideal, but it maintains the basic character of our new test organization. There are just more files to maintain and a slightly different pattern to follow.
- What's in develop instantiates all the tests for each back-end in a single source file (case C below). The main difference here (case A below) is that there is only one test set in each test suite and each suite is instantiated in its own source file. The result is that there are multiple source files for each back-end.
- Note that I also tried something between these two alternatives (case B below), by instantiating all the test suites for each back-end in one file. Results shown below indicate that this was not as good in terms of build times as what is in this PR.
- A side benefit of this organization is that it removes a circular header file dependency that was inadvertently introduced in the new test organization. However, that could have been removed by other means.
- I collected timings to build RAJA with everything turned off except the changed tests in this PR. Here's what I found (these are full build times - compile and link everything). Times are min:sec.
```
Compiler                     case A (this PR)    case B           case C
XL(seq, omp)                 1:39                6:41             6:11
XL(seq, omp, omp target)     4:45                inf              inf
icpc19(seq, omp, tbb)        0:39                1:38             1:38
clang9(seq, omp)             0:19                0:27             0:28
```
The XL builds were done on rzansel. The icpc and clang builds were done on rzalastor.  Here, 'inf' means that the build did not complete in a standard (lalloc 1) allocation. All builds shown here are release builds. I tried debug builds with the XL compiler for the 'inf' cases and they also did not complete.

Anyway, please take a look at the code and let me know if you have suggestions and/or whether you find this organization offensive. I believe that changes like this, once propagated to all the new tests, will reduce our travis build times also.

### CODE REVIEW

**Comment by rhornung67** [comment]
@davidbeckingsale @trws @willkill07 @MrBurmark @artv3 @ajkunen @mdavis36 @rchen20 Please look this over when you have time and let me know what you think.

**Comment by MrBurmark** [comment]
This seems like a reasonably small change to me for the benefit.
Is there a way to avoid duplicating the files, compile the same source file with different defines?

**Comment by davidbeckingsale** [comment]
@MrBurmark - you can do this in CMake, creating targets with different defines but the same source file, we do this to build multiple LULESH versions in the proxy app repo.

I don't oppose this, but I do think there are some negatives to spreading things out over so many files in terms of maintainability. It might be worth trying out the defines to maintain the single file .

**Comment by trws** [comment]
The performance is clearly worth it.  Having the files be so nearly identical does make me think along similar lines to @davidbeckingsale and @MrBurmark though, either using defines or (if that isn't quite the right fit) even using some file templating or cmake file generation to manage the generation of those files.  If we can't, or it gets too complex, I'm fine with this, but it feels like a place that would be really easy to introduce a *small* bug in a test that causes it to run a completely different test than intended for example.

**Comment by rhornung67** [comment]
All, I believe I can make this cleaner and much more easily manageable by reorganizing the test header files. The current headers contain redundant definitions for different tests, plus a bunch of crazy relative file path header inclusions. I will sort this out and put up a separate PR. After that, I will return to this and work it in.

**Comment by artv3** [comment]
@rhornung67 which script did you use for omp target? I tried ``blueos-xl_2019.08.20_omptarget`` but hit an error in the examples

```
include/RAJA/pattern/kernel/Lambda.hpp:153:3: error: no matching function for call to object of type 'const
      tuple_element_t<0L, camp::tuple<(lambda at examples/omp-target-ltimes.cpp:133:7)> >' (aka 'const (lambda at examples/omp-target-ltimes.cpp:133:7)')
  camp::get<LoopIndex>(data.bodies)
```

After disabling the examples, building is taking over an hour.

**Comment by rhornung67** [comment]
@artv3 I used the build script 'blueos_xl-2020.03.18_omptarget.sh' and I disabled the examples and exercises. I don't believe the ltimes example builds with any compiler if openmp target is enabled. Also, for the build times above, I turned off everything in the build except the reduce-sanity tests.

**Pull request closed without merging**
