### PR TITLE
Adding a Tioga Gitlab CI Pipeline

### PR DESCRIPTION
**Pull request by kab163**
# Summary

- This PR is a feature
- It does the following:
  - Adds a Tioga CI pipeline to test latest rocm CI jobs

WIP:
- [ ] What other compiler combos should be added?

### CODE REVIEW

**Comment by adrienbernede** [comment]
@kab163 you’ll need to update `radiuss-spack-config` to the branch `spack-0.18.0` to address the issues you see on tioga.

**Comment by adrienbernede** [comment]
@kab163 The latest errors on Tioga suggest that we should have a look at the external packages configured in radiuss-spack-config.
Tioga systype is `toss_4_x86_64_ib_cray`. In the associated `packages.yaml` in radiuss-spack-config (https://github.com/LLNL/radiuss-spack-configs/blob/main/toss_4_x86_64_ib_cray/packages.yaml) I see that there is no hip@5.1.0 defined, although it is required by the spec.

Note:
I had to figure this out "by hand". It is unfortunate that with clingo we lost so much in clarity about the failed constraints. However, spack claims that the 0.18.0 release (just a few days newer than what we use here) should have better error messages. Maybe worth a try (in a separate branch).

**Comment by kab163** [comment]
Hmm, not sure what to do with `package 'umpire' not found` error - https://lc.llnl.gov/gitlab/radiuss/RAJA/-/jobs/854105#L198

**Comment by rhornung67** [comment]
> Hmm, not sure what to do with `package 'umpire' not found` error - https://lc.llnl.gov/gitlab/radiuss/RAJA/-/jobs/854105#L198

I don't see how your changes try to pull in Umpire. Is there something amiss with the RADIUSS shared spack configs?

Also, the ROCm 5.3.0 compiler breaks RAJA tests (AMD folks are looking into this). We should back off to 5.2 for now.

**Comment by adrienbernede** [comment]
@kab163 I ran into the `package 'umpire' not found` too.
I debugged it by running local on the machine, with spack in debug mode, which is possible updating uberenv to the lastest version. Here is the hopefully complete sequence of actions:
- Clone locally on LC
- Update uberenv to latest main (adds `--spack-debug` option)
- Edit `scripts/gitlab/build-and-test.sh` to add `--spack-debug` option to the uberenv call
- Launch a local build, with a command like (on ruby): `SPEC="..." srun -N 1 -p pdebug ./scripts/gitlab/build-and-test.sh`.

**Comment by kab163** [comment]
> * srun -N 1 -p pdebug ./scripts/gitlab/build-and-test.sh

I ran that and am trying to parse the output. 
```
lib/spack/spack/main.py:1006 ==> [2022-11-11-10:03:29.004341] UnknownPackageError: Package 'umpire' not found.
    You may need to run 'spack clean -m'.
lib/spack/spack/error.py:54 ==> [2022-11-11-10:03:29.004567] Error: Package 'umpire' not found.
You may need to run 'spack clean -m'.
Traceback (most recent call last):
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 1357, in get_pkg_class
    module = importlib.import_module(fullname)
  File "/collab/usr/gapps/python/build/spack-toss4.1/var/spack/environments/python/._view/75prb56irmif5ejtirjthpx6kq3gqo52/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/dev/shm/tioga38-manual_job_1668189782/spack/var/spack/repos/builtin/packages/umpire/package.py", line 13, in <module>

ImportError: cannot import name 'hip_repair_cache' from 'spack.pkg.builtin.camp' (/dev/shm/tioga38-manual_job_1668189782/spack/var/spack/repos/builtin/packages/camp/package.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/main.py", line 1003, in main
    return _main(argv)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/main.py", line 958, in _main
    return finish_parse_and_run(parser, cmd_name, env_format_error)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/main.py", line 986, in finish_parse_and_run
    return _invoke_command(command, parser, args, unknown)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/main.py", line 635, in _invoke_command
    return_val = command(parser, args)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/cmd/dev_build.py", line 123, in dev_build
    spec.concretize()
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/spec.py", line 2915, in concretize
    self._new_concretize(tests)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/spec.py", line 2890, in _new_concretize
    result = solver.solve([self], tests=tests)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/solver/asp.py", line 2394, in solve
    reusable_specs = self._check_input_and_extract_concrete_specs(specs)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/solver/asp.py", line 2342, in _check_input_and_extract_concrete_specs
    if s.virtual:
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/spec.py", line 1637, in virtual
    return spack.repo.path.is_virtual(self.name)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 1021, in is_virtual
    return have_name and pkg_name in self.provider_index
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 901, in provider_index
    self._provider_index.merge(repo.provider_index)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 1227, in provider_index
    return self.index["providers"]
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 731, in __getitem__
    self._build_all_indexes()
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 746, in _build_all_indexes
    self.indexes[name] = self._build_index(name, indexer)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 777, in _build_index
    indexer.update(namespaced_name)
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 651, in update
    not self.repository.exists(name) or self.repository.get_pkg_class(name).virtual
  File "/dev/shm/tioga38-manual_job_1668189782/spack/lib/spack/spack/repo.py", line 1359, in get_pkg_class
    raise UnknownPackageError(pkg_name)
spack.repo.UnknownPackageError: Package 'umpire' not found.
    You may need to run 'spack clean -m'.
```

**Comment by adrienbernede** [comment]
@kab163 I merged #1391 in your branch. This way we benefit from all the latest changes, and have much less divergence:
- we all use spack@0.19.0
- we all use the same radiuss-spack-configs (I think)
- we benefit from the latest improvements in radiuss-shared-ci.

I changed the base of your PR to be #1391. That is so that we only see here your changes.
I am hoping for a better behavior of the CI.

**Comment by kab163** [comment]
> @kab163 I merged #1391 in your branch. This way we benefit from all the latest changes, and have much less divergence:
> 
>     * we all use spack@0.19.0
> 
>     * we all use the same radiuss-spack-configs (I think)
> 
>     * we benefit from the latest improvements in radiuss-shared-ci.
> 
> 
> I changed the base of your PR to be #1391. That is so that we only see here your changes. I am hoping for a better behavior of the CI.

Thanks for adding updates! Hope to get this resolved soon.

**Comment by adrienbernede** [comment]
@kab163 I was mistaken: since we do not attempt to build rocprim anymore (we added it as an external package) we can keep using spack@v0.19.0, which does not know about that version.

I am also doing an attempt at pointing to rocm@5.2.3 because @davidbeckingsale mentionned that codes where having issues with 5.3.0: https://github.com/LLNL/radiuss-shared-ci/issues/15.

**Comment by adrienbernede** [comment]
@kab163 are you OK with me merging this in #1391 ?
The rationale is that this PR is not strongly connected to the update of the shared CI.

I moved, to rocm@5.2.3, but if that’s 5.3.0 you want, I suggest opening a PR from the resulting merge, targeting #1391.

**Pull request merged**
