### PR TITLE
Add patch rc-v2022.03.1 to develop.

### PR DESCRIPTION
**Pull request by rchen20**
# Summary

- This PR is something else
- It does the following:
  - Adds patch rc-v2022.03.1 to develop.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
This needs to be updated with develop changes prior to merging.

**Comment by davidbeckingsale** [comment]
And was the fix associated with this patch already available in develop?

**Comment by rchen20** [comment]
> And was the fix associated with this patch already available in develop?

Yes, it was this commit https://github.com/LLNL/RAJA/pull/1311#issuecomment-1214202533. It seemed weird to re-commit that change to this PR (not even sure I can do that).

**Comment by rchen20** [comment]
@davidbeckingsale The HIP DESUL tests keep timing out for some reason. Should I increase the job length, or is this not expected to happen?

**Comment by rchen20** [comment]
@rhornung67 @davidbeckingsale This finally passed, would you mind approving so we can merge?

**Comment by rchen20** [comment]
@rhornung67 @davidbeckingsale Approve again? Thanks!

**Review by rhornung67 — APPROVED** [review]
@rchen20 did the change make it into develop? There is nothing in the changes here except for documentation. Nevermind. I see your earlier comment.

**Comment by rchen20** [comment]
> @rchen20 did the change make it into develop? There is nothing in the changes here except for documentation. Nevermind. I see your earlier comment. David is out until 10/3.

Right, this should only be documentation. The actual change required was already merged into `develop` a few months ago.

**Pull request merged**
