### PR TITLE
bandaid to run tests with travis until #50 drops

### PR DESCRIPTION
**Pull request by trws**
As @rhornung67 noted in #55, the CI isn't actually running any tests.  This is a bandaid to get it to at least run the unit tests and check their output until the unit testing refactor drops.

Thoughts @rhornung67, @davidbeckingsale?

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
This is a great temporary addition while we work on #50 
Once it builds/runs with clang I'm happy for this to be merged.

**Comment by davidbeckingsale** [comment]
Note that the clang issue is a know failure: https://github.com/travis-ci/travis-ci/issues/6120#issuecomment-224072540

I would actually be okay with dropping clang from the matrix for now, and just using gcc to sanity check PRs.

**Comment by trws** [comment]
I'm trying a quick thing to just build clangs with spack then cache them.  If it works, great, if not I'll pull it out and we'll at least have GCCs.

**Comment by davidbeckingsale** [comment]
Sounds great!

**Comment by DavidPoliakoff** [comment]
YESSSSS, shenanigans with Spack with Travis. Possible update, only use Spack if Spack's Travis CI is passing, using Travis to verify the Spack which you're using to improve the Travis so it can verify the RAJA.

**Comment by DavidPoliakoff** [comment]
whoa, actually a little more seriously, might we think about improving the spack package for RAJA so that the Travis verification becomes "git clone spack; spack install raja?" @tgamblin , interesting possibility of using Spack to cover the holes in Travis for CI on C++'y projects

**Comment by tgamblin** [comment]
@davidpoliakoff: I'm all for that.  We talked about allowing spack to do things like travis matrices, but with more dimensions.  So we need that functionality for spack CI anyway. I guess the difference is that while spack would do it *across* a known stack, RAJA would do it over time (commits) just for RAJA.

**Comment by trws** [comment]
So, LLVM no longer puts up an apt repository.  In looking at the caching options on travis, there are several package managers, but none of them for built C/C++ projects.  Methinks perhaps there's an opportunity here if there's an easy way to cache requested spack specs.  Thoughts @tgamblin?

**Comment by trws** [comment]
*sighs*, also possibly a spack option to output a single line every 5 minutes or something? Travis kills a build that outputs nothing for 10 minutes *grumble, grumble, LLVM, grumble*.

**Comment by tgamblin** [comment]
@trws: RE: binaries, well, the CERN guys have binary caching in progress -- there is a PR for it.  Look for ones by @hegner.  I think it'll be awesome once we merge it in.  Of course we need a place to host the binaries.  I wonder how we can do that from LLNL... or maybe S3?  I dunno what's accepted and kind of think it'll take some talking to people.

RE: adding a keepalive to install... so `spack install -v` is too much but `spack install` is too little?  Or LLVM outputs nothing for 10 minutes because it's LLVM?  I wouldn't be opposed to a `--keepalive` option for `install`.... it could just spawn another process that prints "." or something every so often.  I don't think it's worth spending a single-letter flag on though.

**Comment by trws** [comment]
@tgamblin: RE: binaries, I was thinking talking to the travis guys about adding a spack source, with caching, that could leverage the CERN stuff.  That way they deal with the storage, at least until there's a central option

RE: keepalive, travis only shows 10,000 lines of output, so building llvm with -v doesn't even get to the python dependency before you have to download the raw log to see what's going on.  Building without -v dies on building cmake, actually, it doesn't even make it to llvm.

**Comment by tgamblin** [comment]
@trws: do you know the Travis guys?  Because that would be awesome.  As would, apparently, `--keepalive`

**Comment by trws** [comment]
@tgamblin, I do not, but they have a rather annoyed user base (especially over there being no good way to get LLVM compilers) and we have a potential solution so... maybe worth getting ahold of them

**Comment by trws** [comment]
This could probably use a squash as it goes in, but the tests are running correctly on three versions each of clang and gcc at this point.

Good to go @davidbeckingsale, @rhornung67?

**Comment by davidbeckingsale** [comment]
Looks good, I agree with the squash and merge.

**Comment by rhornung67** [comment]
Since I don't know how travis works, but I understand the gist of what you're doing in the yaml file, I approve based on my trust in @davidbeckingsale ...

**Pull request merged**
