### PR TITLE
Update local spack package

### PR DESCRIPTION
**Pull request by adrienbernede**
### Summary

- Update the local "copy" of RAJA Spack package to reflect changes in Spack.

### Details

The local copy of RAJA Spack package is used to experiment with future changes in the official RAJA Spack package.
That means that it is totally optional to have a local copy, and should only happen when needed. The changes should be updated to Spack asap.

There are currently new changes in the local copy, due to the recent introduction of Uberenv in the CI on Gitlab.
These changes will be submitted to Spack soon. They should first be reviewed here, and are tested as part of RAJA CI on Gitlab.

### CODE REVIEW

**Comment by adrienbernede** [comment]
@davidbeckingsale It would probably be wise to merge and test this in #906.

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale It would probably be wise to merge and test this in #906.

That sounds like a good idea. Can you change the destination branch?

**Comment by adrienbernede** [comment]
hmm, OK.

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
Note: @davidbeckingsale Tests on Gitlab are not run on the merge, but only on the branch itself. So changing the destination does not change the tests on Gitlab...

**Pull request merged**
