### PR TITLE
Added new header file

### PR DESCRIPTION
**Pull request by PratikChakraborty10**
# Summary

- This PR is a (refactoring, bugfix, feature, something else)
- It does the following (modify list as needed):
  - Modifies/refactors (class or method) (how?)
  - Fixes (issue number(s))
  - Adds (specific feature) at the request of (project or person)

# Design review (for API changes or additions---delete if unneeded)

On (date), we reviewed this PR.  We discussed the design ideas:

1. First idea or goal
2. Second idea
3. Third idea

This PR implements 1. and 3.  It leaves out 2. for the following reasons

- (impractical)
- (too big)
- (not a good idea anyway)

### CODE REVIEW

**Comment by rhornung67** [comment]
@PratikChakraborty10 what is the point of adding this header file? It is not standard C++ (part of GNU C++). So it is not portable. Also, it pulls in all std C++ headers resulting in potentially longer compile times. Also, you included it in only one of our exercise files. Why is this needed?

**Comment by PratikChakraborty10** [comment]
I am newbie to open source files, I added it to participate in
hacktoberfest.If you merge my pull request it will help me a lot.

**Review by rhornung67 — COMMENTED** [review]
This will not be merged.

**Comment by trws** [comment]
I'd read people were doing this, but who knew it would happen here.  Either way, marked as spam and closed.

**Comment by rhornung67** [comment]
I thought it may be a bot.

**Comment by trws** [comment]
Sadly probably not...

https://www.theregister.com/2020/10/01/digitalocean_hacktoberfest_pull_request_spam/
https://joel.net/how-one-guy-ruined-hacktoberfest2020-drama
https://hacktoberfest.digitalocean.com/hacktoberfest-update

DigitalOcean will be looking for "invalid" and "spam" labels on bad PRs related to this to flag/ban people, hence the new "spam" label.

**Comment by rhornung67** [comment]
Yup. I just read the joel.net article. Some people have too much time on their hands to waste.

**Pull request closed without merging**
