### PR TITLE
Make existing tests use CTest

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This is a stopgap PR until we get #50 up and running.

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/LLNL/RAJA/pull/73" target="_blank">ReviewNinja

**Comment by davidbeckingsale** [comment]
@trws check this out. The diff is still a mess because I deleted Kripke and LULESH, but if you check it out offline you should be able to see what I added.

**Comment by trws** [comment]
I heartily approve.
👍 
:shipit:

**Comment by davidbeckingsale** [comment]
@rhornung67 can you take a look at this - I have removed the apps and integrated the existing unit-tests with CMake's test support so that the 'make test' target works correctly (in the CPU case)

**Comment by rhornung67** [comment]
@davidbeckingsale Are we still planning to use Google Test?  Also, if the proxy apps are in a separate repo, we need to make sure the release information for each is in place (it should be), and we'll need to make some useful documentation.  Will the RAJA repo be a git submodule for the proxy app repo (i.e., users will have to do a git clone --recursive)?

**Comment by davidbeckingsale** [comment]
Yup, we will move to GoogleTest. 

The proxy app repository hasn't been created yet, so we can structure it however we want.

**Comment by DavidPoliakoff** [comment]
@davidbeckingsale : https://github.com/DavidPoliakoff/performance-test-suite if you need a template for proxy app repo

**Comment by trws** [comment]
@rhornung67, I would recommend that the proxy app/performance test/examples repo, whatever we call it, use the cmake `ExternalProjectAdd` functionality to get raja, much like #50 is now using it to get google test.  That way, if raja is available, we can use it, if not then cmake will download it or check it out without the user having to know about dealing with submodules.  Does that sound reasonable?

**Comment by davidbeckingsale** [comment]
@trws - good suggestion, that's how the performance repo is currently configured. I can use exactly the same setup for the app repo.

**Comment by rhornung67** [comment]
Works for me.  Thanks.

**Comment by davidbeckingsale** [comment]
Was that you approving this branch?

**Comment by trws** [comment]
LGTM: contingent on a rebase or merge to get it up to date.

[Approved with PullApprove](https://pullapprove.com/LLNL/RAJA/pull-request/73/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=LLNL/RAJA)

**Comment by davidbeckingsale** [comment]
Thanks @trws, I'll get the rebase done and update this PR.

**Comment by davidbeckingsale** [comment]
Pushed the rebase, let's make sure this builds. It also needs re-approval!

**Comment by trws** [comment]
Interesting, I thought I had set it not to reset on new push to a PR, guess not.

Either way:
:shipit:

**Comment by trws** [comment]
@rhornung67, was your comment of last week meant as an approval?

**Comment by rhornung67** [comment]
@trws yes, I approve. Sorry for the confusion.

**Comment by trws** [comment]
Thanks @rhornung67!

@davidbeckingsale, have time for one more merge/rebase so we can get this merged?

**Comment by davidbeckingsale** [comment]
Yup, I'll get this done today.

**Comment by davidbeckingsale** [comment]
This should be good to go now - I rebased onto develop.

**Comment by davidbeckingsale** [comment]
Note that I didn't convert the GPU tests yet, since they don't run in Travis anyway.

**Comment by trws** [comment]
Ok.  As soon as travis passes I'll merge. Thanks @davidbeckingsale!

**Pull request merged**
