### PR TITLE
Fix build on macosx with clang9

### PR DESCRIPTION
**Pull request by gzagaris**
# Summary

Building RAJA on macosx with a macports provided
llvm-clang9 compiler was causing a cmake configuration
error:

```
-- Configuring done
CMake Error in CMakeLists.txt:
  No known features for CXX compiler

  "Clang"

  version 9.0.1.
```

Setting the cmake policy CMP0025 to NEW fixes the issue.

### CODE REVIEW

**Comment by gzagaris** [comment]
> Are you sure that policy is correct? Based on the documentation (https://cmake.org/cmake/help/v3.0/policy/CMP0025.html) it's to correctly detect AppleClang. I think that setting this policy with clang 9 will make CMake think you are using AppleClang.

I think so. It appears that under certain circumstances, CMake only allows Apple's Clang to provide info on supported features. So setting this circumvents the problem. See related discussion:

- https://trac.macports.org/ticket/53201
- https://trac.macports.org/ticket/53615

I believe this is a CMake bug. That said, I am not sure what the exact trigger is. Perhaps, it is a combination of the other cmake policy settings in RAJA. Building RAJA was the only instance that triggered the issue for me thus far. By setting this policy I was able to build RAJA successfully and run all the tests.

**Comment by gzagaris** [comment]
Also, I tried this with both CMake-3.11.4 and the latest CMake 3.16 and got the same behavior regardless of version.

**Comment by rhornung67** [comment]
@gzagaris I don't do any code development on my Mac except for via containers. So I'll defer evaluation of this PR to others.

**Comment by davidbeckingsale** [comment]
@gzagaris - does CMake detect "Clang" or "AppleClang" with Clang 9 and this change?

**Comment by gzagaris** [comment]
> @gzagaris - does CMake detect "Clang" or "AppleClang" with Clang 9 and this change?

@davidbeckingsale -- CMake detects "Clang" with this change, i.e., `CMAKE_CXX_COMPILER_ID` is "Clang", as I'd expect. 

To the best of my knowledge, setting this policy to NEW, provides a workaround to a CMake bug where only AppleClang compiler information can be retrieved by CMake.

**Comment by rhornung67** [comment]
@gzagaris regarding your question about Travis last week: If you have the proper privileges, you can go into Travis and restart a specific build and test configuration.

**Comment by gzagaris** [comment]
> @gzagaris regarding your question about Travis last week: If you have the proper privileges, you can go into Travis and restart a specific build and test configuration.

Thanks -- looks like merging from develop triggered Travis and everything is passing.  Since I don't have appropriate permissions, please, feel free to merge this at your convenience.

**Comment by rhornung67** [comment]
@gzagaris I updated your branch with RAJA develop. After checks pass, I will merge this.  Thanks.

**Pull request merged**
