### PR TITLE
Break apart some workgroup tests to improve build times

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary
Break apart workgroup tests containing more than one test definition per translation unit.

- This PR is a refactoring
- It does the following (modify list as needed):
  - refactors workgroup tests by breaking the individual tests apart.

### CODE REVIEW

**Review by rhornung67 — COMMENTED** [review]
@MrBurmark how long did it take to compile this branch with XL+nvcc? I tried and it timed out in a standard 60 min. allocation. Trying on another compute node to see if that was the issue.

**Comment by rhornung67** [comment]
> @MrBurmark how long did it take to compile this branch with XL+nvcc? I tried and it timed out in a standard 60 min. allocation. Trying on another compute node to see if that was the issue.

Ah. You didn't have Robert's changes in here. I updated you branch and am rebuilding.

**Review by rhornung67 — DISMISSED** [review]

**Comment by MrBurmark** [comment]
Weird, I think the last time I looked at these tests we were working more on intel build times.
In this PR I re-enabled some tests that were previously not being built with intel now that things are more under control, but that should not have affected the xl build.
I took a look and it looks like this makes intel build times on travis about 10 minutes worse, going from 1hr 5mins to 1hr 15mins.

**Comment by rhornung67** [comment]
> Weird, I think the last time I looked at these tests we were working more on intel build times.
> In this PR I re-enabled some tests that were previously not being built with intel now that things are more under control, but that should not have affected the xl build.
> I took a look and it looks like this makes intel build times on travis about 10 minutes worse, going from 1hr 5mins to 1hr 15mins.

You could disable some tests for Intel on Travis since they will be hit by Intel in our GItlab runs.

**Comment by MrBurmark** [comment]
> You could disable some tests for Intel on Travis since they will be hit by Intel in our GItlab runs. That may be the best because we are starting to rework kernel tests and adding teams tests.

Ok, I'll re-disable those tests to give us some more head room then.

**Review by rhornung67 — APPROVED** [review]

**Review by rchen20 — APPROVED** [review]

**Pull request merged**
