### PR TITLE
Add cub as a submodule

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Since we now provide and install cub ourselves, I'm don't think we need the fallback. If you prefer, I can still have an `ENABLE_CUB` option that's on by default, and just allow people to explicitly choose thrust?

**Comment by rhornung67** [comment]
If we don't need a fallback, then I'd prefer it not be there. Let's hope CUB doesn't go away 👍

**Comment by davidbeckingsale** [comment]
@MrBurmark - can you give this a spin, I want to make sure it's still working for you since you are the heaviest CUB user.

**Comment by MrBurmark** [comment]
This works, but I ran into a couple of issues when I tried it out.
I use cub for histogram and the way cub is included in RAJA I have to type `#include "cub/cub/file.cuh` instead of `#include cub/file.cuh`. I could have the build system include RAJA_PATH/include/cub to fix this, but it would be nice if there were another solution.
I discovered that I can't use cub version >= 1.7.5 due to a resolution error between `isinf(float)` vs `std::isinf(float)` in the cuda9 header `cuda_fp16.h`. I'm not sure whose code is causing that, but cub added support for half precision in 1.7.5 and started explicitly including that header.

**Comment by davidbeckingsale** [comment]
Okay, we can roll back the submodule version to be pinned at 1.7.5

I can fix the include path location pretty easy, just need to move the submodule and rework some of the CMakeLists.txt

**Comment by MrBurmark** [comment]
It breaks for 1.7.5 and up, so 1.7.4 would be better for now.
Thanks.

**Comment by davidbeckingsale** [comment]
Gotcha, I wasn't parsing the `>=` correctly in my head.

**Comment by davidbeckingsale** [comment]
@MrBurmark - changes made, please approve if this works for you.

**Pull request merged**
