### PR TITLE
Fix synchronization in examples

### PR DESCRIPTION
**Pull request by artv3**
Folks, I noticed that with the transition of running team kernels on the CAMP default stream we introduced some failing examples. This occurs since our examples draw from the CUDA default stream (different than CAMP default stream). 

This PR adds a fix by adding synchronization after kernels.

### CODE REVIEW

**Comment by trws** [comment]
I assume the false tells it to sync? For the tut matmult one, adding a device sync to the checkResults function should take care of it for all of them if async is desirable there.

**Comment by trws** [comment]
Actually, that might be nice for the teams one too, or for that one actually use a resource so the async behavior works correctly.

**Comment by artv3** [comment]
> I assume the false tells it to sync? For the tut matmult one, adding a device sync to the checkResults function should take care of it for all of them if async is desirable there.

Correct, I think leaving the policies as synchronous is fine under tut variant. We can cover async execution in other examples; like "-Resource"

**Review by mdavis36 — APPROVED** [review]

**Review by MrBurmark — APPROVED** [review]
It looks like these lacked synchronization before. It looks like you can use the policy or synchronize in the check function.

**Pull request merged**
