### PR TITLE
Update blt

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR updates BLT to the latest release (0.3.0) and updates our unit tests and test macros to work with that.

### CODE REVIEW

**Comment by rhornung67** [comment]
Do we need to add the -DBLT_CXX_STD==c++11 option to the CMake args to get travis to build?

**Comment by davidbeckingsale** [comment]
Shouldn’t do, let me check.

**Comment by rhornung67** [comment]
I didn't want to commit that change and then back it out if not needed.

**Comment by davidbeckingsale** [comment]
We don't need that, but something is up with the Travis builds. I'm not entirely sure what the problem is.

**Comment by rhornung67** [comment]
It's just the two nvcc builds. I'll restart them in a bit.  ReadTheDocs is also having issues today.

**Comment by rhornung67** [comment]
@davidbeckingsale No luck restarting the builds. nvcc builds are failing with an error internal to gtest.

**Comment by rhornung67** [comment]
@davidbeckingsale this works on our systems with CUDA 9, which is what we test on Travis. Flummoxed!

**Comment by davidbeckingsale** [comment]
Yup, I'm a bit lost. @trws - do you have any ideas?

**Comment by trws** [comment]
I just got off the plane and my phone doesn’t want to load Travis, I’ll look through the backlog and see what I can do in the morning. If something is changing in the c++ level selection logic it’s possible there’s an undiscovered big in c++11 mode mixed with CUDA on certain host compiler versions or something.

**Comment by rhornung67** [comment]
@trws @davidbeckingsale here's a new data point. I was able to reproduce the gtest compiler error on LC with cuda 9.1.76 and gcc 4.9.3 (cuda 9.1.x versions don't work with gcc 6.x or newer).  The code builds and all tests pass with three versions of cuda 9.2.x I tried. 

So the fix for this may just be updating the docker compiler images we use. @trws it looks like you own those images. Do you have time to update those?

If that works, I will make a note in the release notes and user docs that enabling the RAJA tests requires with CUDA enabled requires a min version of 9.2.x

**Comment by trws** [comment]
They're re-generated with 9.2, I also made a 10.2 image and pushed it, and am adding that to travis.  Will push up the commit once I see the re-run of the tests on your merge commit come back green with the new image.

**Comment by rhornung67** [comment]
Great. Thanks @trws. I'll set up the PRs for the next RAJA release later today after this is merged.

**Comment by trws** [comment]
*sigh* of course it helps to remember to install the opemp runtime with clang... will restart the dead test builds when the updated image with libomp in it finishes uploading.

**Comment by rhornung67** [comment]
No worries. Thanks @trws

**Comment by rhornung67** [comment]
Looks good @trws. Thanks. Is this ready to merge? 

 I need to get some approvals because I can't approve my own PR. @artv3 , @ajkunen , @MrBurmark , @davidbeckingsale need an approval to merge this.

**Comment by trws** [comment]
Yup, as long as the last run came back green it’s good to go.

**Pull request merged**
