### PR TITLE
Fix for using external cub when raja is a submodule

### PR DESCRIPTION
**Pull request by adayton1**
# Summary

- This PR is a feature
- It does the following (modify list as needed):
  - Modifies CMakeLists.txt to allow for an external cub when raja is itself a submodule

### CODE REVIEW

**Comment by adayton1** [comment]
@trws What do you think of this change?

**Comment by trws** [comment]
My understanding of generator expressions is a bit limited, IIRC BUILD_INTERFACE used like that means "add these include directories if this target is used by something internally, but not if it's used externally."  Does that accomplish what you want, such that if you specify a different cub all the targets inside RAJA get re-directed? If so I think this is fantastic, it's far smaller than where I thought we would end up.

**Comment by adayton1** [comment]
My understanding of generator expressions is also a bit limited, but I interpreted BUILD_INTERFACE the same way: https://cmake.org/cmake/help/latest/guide/tutorial/index.html#adding-export-configuration-step-11. I was getting the same error message about halfway down this section of the tutorial and adding BUILD_INTERFACE fixed it. Though I certainly don't claim to understand the finer points. @davidbeckingsale do you have any thoughts?

**Comment by rhornung67** [comment]
@adayton1 We briefly discussed this PR at the RAJA meeting this morning. We're OK with it. Does it meet your needs. If so, please update the base branch and re-ping folks for approvals.  Thank you.

**Comment by trws** [comment]
Closing #838 in favor of this version, if there's more over there you stil need, let me know.

**Comment by davidbeckingsale** [comment]
@adayton1 - is this PR good to go?

**Comment by MrBurmark** [comment]
Is this ready to go?

**Comment by adayton1** [comment]
Yeah it is good to go. Thanks!

**Pull request merged**
