### PR TITLE
Update BLT and re-introduce xml to junit report conversion

### PR DESCRIPTION
**Pull request by adrienbernede**
# Summary

This PR is an update and a fix:
- it updates BLT to include new logic to convert cmake xml test reports to junit
- it fixes the Gitlab CI to export the test reports in the UI

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
Thanks @adrienbernede !

**Comment by adrienbernede** [comment]
As a bonus, this PR activate some more tests reports in Gitlab on Lassen.

**Review by kab163 — APPROVED** [review]
Looks great!

**Review by rhornung67 — APPROVED** [review]
Thanks @adrienbernede Good to merge?

**Comment by adrienbernede** [comment]
@rhornung67 Unless you have other tests to run when there is a BLT update, this is good to merge.

**Pull request merged**
