### PR TITLE
Remove forall_segments

### LINKED ISSUE #41: Document or remove prototypes with unclear purpose or usage
I've noticed a couple of outward-facing functions that puzzle me.  Thoughts/history @keasler, @rhornung67?
- `forall_segments`: this has definitions in a couple of places, but is not used by anything in raja itself.  Is this a deprecated usage, or something in active use?
- `void forall(const INDEXSET_T& iset, LOOP_BODY loop_body)`: This takes any first argument at all and treats it as an indexset.  Is there an assumption someplace that custom IndexSet types do not need to inherit from IndexSet?

### PR DESCRIPTION
**Pull request by davidbeckingsale**
Fixes #41

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@rhornung67 @trws @DavidPoliakoff can I get some approvals for this?

**Comment by DavidPoliakoff** [comment]
I'd need to know that the issue we reference in the linked issue has been resolved, we have no test for it. Rich?

**Comment by davidbeckingsale** [comment]
I believe it is - the `forall_segments` method was only used in CoMD on the CPU.

**Comment by keasler** [comment]
I approve.  This just reminds me that I need to hand off the fast version of CoMD I wrote to someone, so that when the IndexSets objects are supported directly on the GPU, that code should just work.

**Comment by rhornung67** [comment]
:+1:

**Pull request merged**
