### PR TITLE
add a portable c++11-based timer and refactor timer selection

### PR DESCRIPTION
**Pull request by trws**
This adds a c++11 timer as discussed in issue #40.  It also refactors the timer selection somewhat.  I'm not sure what's best by way of a default here, chrono is most portable, but the unfortunately ancient versions of the C++ standard library floating around don't support all of it.  Maybe it's worth adding a configure-time test?

### CODE REVIEW

**Comment by trws** [comment]
*sigh* as evidenced by the travis result.

**Comment by trws** [comment]
So, a bit of egg on my face here, the cause of the issue was twofold:

1. I had my namespaces scoped incorrectly, causing the chrono include to be scoped incorrectly
2. Travis was using an old (4.8) gcc with too old a libstdc++

With those addressed, this appears to be in shape to merge, and gives us timer portability.

Review @DavidPoliakoff, @rhornung67?

**Comment by rhornung67** [comment]
I approve. We will need to update the Config/build section of the user docs for the new options (chrono, caliper). @trws feel free to do that. If you don't have time, I can do it over the weekend.

**Comment by DavidPoliakoff** [comment]
Looks good in the diff, let me build/test

**Comment by DavidPoliakoff** [comment]
Cool, it produces results on the LULESH builds. I appreciate the documentation update (on the option calls) as well. Feel free to merge it (I would, but I don't have merge access)

**Comment by trws** [comment]
Good point @rhornung67, I'll adjust the docs shortly.

**Comment by DavidPoliakoff** [comment]
I like the docs changes (in 4d19cc8). Still 👍

**Comment by DavidPoliakoff** [comment]
Also, a little more broadly, I like the pattern of instead of a set of BOOLS, only one of which we want ON, having a string with values.

**Comment by trws** [comment]
I generally prefer that also.  The odd pattern of using the cmake properties has one additional benefit, in that ccmake and similar will only display the options that are listed in the property.  In fact, the graphical should show it as a drop-down menu rather than an editable string.

**Comment by trws** [comment]
I think this one is good to go, but I'm not really comfortable with merging my own PR here.  @davidbeckingsale, @rhornung67, final review and merge?

**Pull request merged**
