### PR TITLE
fixes for build on bgq

### PR DESCRIPTION
**Pull request by trws**
This alters the BGQ host_config files to use reasonably up-to-date c++
standard libraries.  The clang solution is not ideal, it really should
use the gcc-4.8.4 libstdc++ as well, but because of the way the wrapper
script is written, that's infeasible without completely reimplementing
the wrapper logic.  The libc++ version works fine for tests, but it's
conceivable it could cause issues for some code that uses raja in a
component and thus ends up with two standard libraries.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
👍 Intel fixes look good.

**Comment by rhornung67** [comment]
@trws this appears to have fixed the clang and gcc issues on BG/Q.  Thanks!

I did notice that the timing output (for LULESH 1.0) is garbage, both chrono and gettime options. But that's a minor detail we can address later.

**Comment by trws** [comment]
Thanks @rhornung67, I think I have a fix for the chrono version of that (it was doing a cast it shouldn't) but I'll have to get a look at it to be sure.

**Comment by trws** [comment]
As a heads up, it seems there will be a solution to let us use the 4.8.4 lib with clang in the near future.  Possibly also a newer clang build to go with it, so maybe good news coming on that front.

**Pull request merged**
