### PR TITLE
Unify and fixup RAJA_COMPILER_XLC_* defines

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This takes the place of #80

### CODE REVIEW

**Comment by tomdeakin** [comment]
If I apply this patch and try to build with the XL compiler I'm getting `error: RAJA compiler is undefined!` errors.

**Comment by davidbeckingsale** [comment]
Uh oh, does #80 work for you though? These basically do exactly the same thing....

**Comment by tomdeakin** [comment]
If I use this part of #80 I get the builtin errors back`error: unknown linkage language "builtin"`
```
elseif(CMAKE_CXX_COMPILER_ID MATCHES XL)
set(RAJA_COMPILER "RAJA_COMPILER_XLC12")
```

**Comment by davidbeckingsale** [comment]
Okay, give this new version a shot. There was some code that wanted both `XLC12` and `XLC_POWER8` defined :(

**Comment by tomdeakin** [comment]
It's closer. It also needed the C++11 flag
`set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")`

I get these errors though where I commented out those lines you deleted in the read_datatypes.hxx file.
```include/RAJA/real_datatypes.hxx:144:2: error: RAJA compiler is undefined!
#error RAJA compiler is undefined!```

**Comment by tomdeakin** [comment]
Oh dear. I now have a couple of warnings about C++14 behaviour, and then the compiler crashes with an internal error when building `recipe for target 'test/unit/cpu/CMakeFiles/CPUtraversal-test.exe.dir/main-traversal.cxx.o' failed`

**Comment by davidbeckingsale** [comment]
The C++14 stuff is odd. I need to take a better look at this when I have some more time. For a temporary fix, you can probably switch back to `b431fd0` and also define RAJA_COMPILER_XLC_POWER8 somewhere.

**Comment by tomdeakin** [comment]
I tried that and used the `cmake/SetupCompilers.cmake` to define `RAJA_COMPILER_XLC_POWER8` but it doesn't seem to propagate very well, and I get the `RAJA compiler is undefined!` in config.hxx and real_datatypes.hxx.

**Comment by davidbeckingsale** [comment]
Did you just do `add_definitions(RAJA_COMPILER_XLC_POWER8)`

**Comment by tomdeakin** [comment]
No, I did added this:
```
elseif(CMAKE_CXX_COMPILER_ID MATCHES XL)
  set(RAJA_COMPILER "RAJA_COMPILER_XLC_POWER8")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")
```

**Comment by davidbeckingsale** [comment]
Looking at the code, I think you need to have both defined.

**Comment by tomdeakin** [comment]
I've also included that line, and I'm getting an unknown compiler warning
```
include/RAJA/config.hxx:238:9: warning: RAJA_COMPILER unknown, using default empty macros. [-W#pragma-messages]
#pragma message("RAJA_COMPILER unknown, using default empty macros.")
```
and then a failure:
`recipe for target 'src/CMakeFiles/RAJA.dir/AlignedRangeIndexSetBuilders.cxx.o' failed`

**Comment by davidbeckingsale** [comment]
Sorry, I think I didn't make sense. I think the magic definitions are `#define RAJA_COMPILER RAJA_COMPILER_XLC12` and `#define RAJ_COMPILER_XLC_POWER8`.

If you set RAJA_COMPILER as RAJA_COMPILER_IBM_XLC12 and use `add_definitions(-DRAJA_COMPILER_XLC_POWER8)`  you should be good.

**Comment by rhornung67** [comment]
@davidbeckingsale we should probably get rid of the XLC12 stuff since we don't use. I think this goes back to some earlier days where we tested RAJA concepts using functors with that compiler on BG/Q. If you agree, I'll add an issue.

**Comment by davidbeckingsale** [comment]
Yeah, I basically think the only XLC we will support is the newer power 8 stuff. I can modify this branch to do this.

**Comment by rhornung67** [comment]
Thanks.

**Comment by davidbeckingsale** [comment]
@tomdeakin can you post the errors you are getting when you run with commit `656137a`?

**Comment by tomdeakin** [comment]
With no changes to 656137a, using xlC v13.1.3, it crashes the compiler:
```
/opt/ibm/xlC/13.1.3/bin/.orig/xlc++: error: 1501-230 Internal compiler error; please contact your Service Representative. For more information visit:
http://www.ibm.com/support/docview.wss?uid=swg21110810
test/unit/cpu/CMakeFiles/CPUtraversal-test.exe.dir/build.make:62: recipe for target 'test/unit/cpu/CMakeFiles/CPUtraversal-test.exe.dir/main-traversal.cxx.o' failed
make[2]: *** [test/unit/cpu/CMakeFiles/CPUtraversal-test.exe.dir/main-traversal.cxx.o] Error 41
CMakeFiles/Makefile2:265: recipe for target 'test/unit/cpu/CMakeFiles/CPUtraversal-test.exe.dir/all' failed
```

**Comment by davidbeckingsale** [comment]
Oh wow. Try passing `-DRAJA_ENABLE_TESTS=Off` when you run CMake, and see if it works with whatever user code you are trying to build it for. Are you trying to run GPU-STREAM on a power8 node?

**Comment by tomdeakin** [comment]
RAJA itself built, but when I try to compile GPU-STREAM I get the same Internal error.

**Comment by rhornung67** [comment]
@tomdeakin have you tried backing off the compiler optimization level to see if that works?

**Comment by tomdeakin** [comment]
@rhornung67 I tried using `-O0`, but it gets the same error.

**Comment by rhornung67** [comment]
Arrgh...unfortunately, the 1501-230 code is a generic IBM internal compiler error code. We're looking into this to see if we can reproduce this here.

**Comment by rhornung67** [comment]
@tomdeakin is 13.1.3 the newest version of the compiler you have access to?

**Comment by tomdeakin** [comment]
v13.1.3 is the newest version on the particular Power 8 box at the moment.

**Comment by rhornung67** [comment]
We have 13.1.5 here. We'll see if we see the same issue. If it works for us, you may need an update.

**Comment by tomdeakin** [comment]
It's not my box so updating is a problem. 4 months ago the RAJA version in #80 worked (with modifications similar to those in @davidbeckingsale 's commits in this issue) with the v13.1.2 IBM compiler worked fine.

**Comment by tomdeakin** [comment]
@rhornung67 I now have 13.1.4 available on the box I'm using so am able to test with that.

The `bugfix/xlc-power8` branch builds with xlc++ 13.1.4, and my code builds and runs. Hooray!

**Comment by rhornung67** [comment]
Awesome! Thanks for the update.

**Comment by davidbeckingsale** [comment]
We should get this merged? @rhornung67

**Comment by DavidPoliakoff** [comment]
👍  thanks for doing the fixes @davidbeckingsale , and thanks again @tomdeakin for the consistently helpful feedback

**Comment by tomdeakin** [comment]
@DavidPoliakoff No problem! Happy to try to be a helpful user.

**Comment by davidbeckingsale** [comment]
Yeah, thanks @tomdeakin 😄

**Comment by rhornung67** [comment]
:+1:

**Pull request merged**
