### PR TITLE
Add Travis configuration

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@rhornung67 here are the changes required to build with Travis

**Comment by rhornung67** [comment]
David,

How do I approve a pull request on github?

—Rch

**Comment by tgamblin** [comment]
Add a thumbs up (optional) and click merge


________________________________

**Comment by davidbeckingsale** [comment]
You just leave a comment saying how great I am at coding, maybe use some emojis, and then we will consider this PR approved. 👍 ⭐ 

There isn't a formal approval process.

If you view the PR on github, you can hit the "Merge pull request" button and it will merge it.

**Comment by keasler** [comment]
Go for it.

**Comment by rhornung67** [comment]
What is this? Facebook?

**Comment by rhornung67** [comment]
Am I the only one who can merge?

**Comment by ajkunen** [comment]
I think we just need to discuss how we want to do approvals/merges.

I would be for:   The person who submitted the PR should do the merge, once they feel they have gotten the feedback they were looking for (unless that person doesn't have "merge" permissions). And like we did on Stash, you need at least one "I approve" comment form someone.

**Comment by davidbeckingsale** [comment]
I approve of this process.

**Comment by DavidPoliakoff** [comment]
What if we start having significant external collaboration? Perhaps a process of "if internal, get an approval, if external, get approvals and Beckingsale handles final approval?"

**Comment by davidbeckingsale** [comment]
I am happy to be the watcher in the water.

**Comment by keasler** [comment]
Since the consequences are higher, and since there are more eyes on github, I think it would be nice to have two approvals.  Also, I think that only one dissenter should be able to stop the process until the dissenters issue is handled to their satisfaction, or the dissenter is over-ruled by at least two people who are not the branch owner.

The most common dissent you will hear from me is, ‘Did you try to build and run with GNU, NVCC, and Intel?’  The automation should squelch that kind of dissent.

-Jeff

**Comment by rhornung67** [comment]
I agree with that.  It would be nice if the system helped to enforce it, like Stash does.

**Comment by davidbeckingsale** [comment]
@keasler good suggestion - I think that the # of approvers can be handled fairly informally based on the size of the PR. For example, documentation fixes, small code changes probably only need 1 approver.

Adding a large new feature (e.g. BoxSegment) should require 2.

**Comment by rhornung67** [comment]
I believe I clamped down the master and develop branches so that only members of the RAJA team can merge into them via github.  This gives us some level of protection.  But, I could have screwed this up.  —Rich

**Comment by ajkunen** [comment]
I agree with @keasler , This should get moved from a PR comment-thread to a Wiki page.  @davidbeckingsale , do you want to formulate this discussion on our github wiki page?

**Comment by davidbeckingsale** [comment]
Sure thing!

**Pull request merged**
