### PR TITLE
Fix logic around external cub to depend on cuda version

### LINKED ISSUE #1194: RAJA does not respect my wish to not use an external CUB
https://github.com/LLNL/RAJA/blob/4a07809dfd0d8dcd4daf5eeb91fb692394c5815b/cmake/SetupPackages.cmake#L32

I don't want to use an external cub, but  no matter what I do, RAJA always uses the system install. I can't figure out if its even possible to use the submodule if there is a the is findable by `FindPackage`. Any advice?

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary
Fix external cub logic.

Now the use of external cub is only forced if using cuda version 11 or greater.
An external cub is no longer searched for before using the raja cub submodule with cuda versions less than 11.

- This PR is a bugfix
- It does the following (modify list as needed):
  - Fixes #1194

### CODE REVIEW

**Comment by rhornung67** [comment]
Question out of ignorance: for the case CUDA version < 11, where is the logic to pull in the cub submodule?

**Comment by MrBurmark** [comment]
The install of the submodule is handled in the top level CMakeLists.txt here https://github.com/LLNL/RAJA/blob/develop/CMakeLists.txt#L300.

**Comment by rhornung67** [comment]
> The install of the submodule is handled in the top level CMakeLists.txt here https://github.com/LLNL/RAJA/blob/develop/CMakeLists.txt#L300.

Right. I forgot to look there. Thanks.

**Review by rhornung67 — APPROVED** [review]
I'm good with this if i works for others.

**Comment by rhornung67** [comment]
@MrBurmark the gitlab ci is failing because corona is down. the corona jobs will have to be restarted when it comes back up.

Also, we should make the CMake logic for ROCprim the same as for CUB.

**Review by rhornung67 — DISMISSED** [review]
Thanks @MrBurmark

**Comment by rhornung67** [comment]
@MrBurmark i merged develop into this. when this comes back green, i think it can be merged. does it solve Matt's problem?

**Comment by MrBurmark** [comment]
I'll ping him again, @mclarson. This PR makes things better because our config will no longer fall back to the submodule unexpectedly if the user wants to use an external cub. It does still force the use of an external cub in cases where the cuda version requires a newer version of cub than the version in our cub submodule. So with newer cuda versions it does force the user to use an external version of cub, hopefully provided in the cuda toolkit, even if they were expecting the submodule to be used because they didn't specify that an external cub should be used. Does that seem like the right way to handle things?

**Comment by MrBurmark** [comment]
@rhornung67 Do you think this is good to merge?

**Review by rhornung67 — APPROVED** [review]

**Comment by rhornung67** [comment]
I do and I approved.

**Comment by mclarsen** [comment]
Sorry I missed missed this. This does not fix my issue. I am using cuda 11.5 and don't want to use and external cub for  complicated reasons.

**Comment by MrBurmark** [comment]
The cub version in the submodule is not compatible with cuda 11, and it will generate compiler warnings if you try to use it with cuda 11. The cuda toolkit as of cuda 11 contains a version of cub. That is why we switched to use the version of cub in the cuda toolkit as of cuda 11. So, I don't think you can build a valid executable with the submodule and cuda 11.
Is there something about the way we package the external cub that causes problems with your configuration?

**Pull request merged**
