### PR TITLE
Task/kernel 3level segment tests

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR adds nested kernel tests that use multiple segment types in each kernel.
- It also updates copyright year in some files that we missed earlier and script to cover these files.
- Removed some unused variables in openmp target policy implementations to squash compiler warnings.

### CODE REVIEW

**Comment by rhornung67** [comment]
LGTM

**Comment by rhornung67** [comment]
Anybody want to review this?

**Review by mdavis36 — APPROVED** [review]

**Review by rchen20 — APPROVED** [review]
Not sure how much cleaner this would be, but should we just run all 3 permutations (with clearing of the work_array between permutations) in each test? This would eliminate the need for the "perm" parameter, and the 3 calls to the test.

**Comment by rhornung67** [comment]
I thought about that. I decided to do it this way in case we wanted to add more permutation cases. Either way works for me.

**Comment by rchen20** [comment]
Yeah, it's perfectly fine with the permutations too.

**Review by artv3 — APPROVED** [review]

**Pull request merged**
