### PR TITLE
Omp reducer update

### PR DESCRIPTION
**Pull request by mcordery**
New reductions that use a vector of length teams*max_threads, which eliminates forced copy construct in target_forall.
Reductions are done by using teams to fold their vector to a single value, then all teams are summed.
Still having problems linking with TRAP_INT, due to the reduction there. Some kind of multiple definition problem.
The INIT_VIEW1D kernels also give the wrong answer for the target kernel so I'm not sure if those required the forced copy construct in the target_forall.
Tests with Stream_DOT showed marked improvements

### CODE REVIEW

**Comment by rhornung67** [comment]
@mcordery it looks like all omp critical sections gone in the reducers now; is this correct?  Did you try atomics with the original implementation? Just curious...

**Comment by rhornung67** [comment]
@mcordery sounds good. Keep on truckin'.  I think the travis builds are failing because the RAJA_ENABLE_TARGET_OPENMP CMake variable is not turned on....

**Comment by trws** [comment]
That is probably right, but we currently don't have a target enabled compiler on travis, which is something we really need to fix with either a target enabled clang or GCC that can target the host or something.

**Comment by rhornung67** [comment]
@trws I believe we also rely on OpenMP features which are available in our Sierra compilers, but are not yet part of the standard or have not been added to some other vendor compilers yet. At least that is my impression based on some vendors attempting to exercise the OpenMP target variants of the perf suite. 

My goal is to set up (at least) nightly CI testing across all viable compilers on all LC platforms for RAJA, RAJA perf suite, RAJA proxy suite, etc. Getting there, but a lot of other stuff in pipleine right now....

**Pull request closed without merging**
