### PR TITLE
removing semicolon to make pedantic happy

### LINKED ISSUE #343: Latest commit to master breaks laser simulation
include/camp/lambda.hpp:126:24: error: extra ';' [-Werror=pedantic]
 CAMP_MAKE_L(bind_front);

include/camp/list/find_if.hpp:84:21: error: extra ';' [-Werror=pedantic]
 CAMP_MAKE_L(find_if);
                     ^

VarOpinclude/camp/camp.hpp:147:24: error: extra ';' [-Werror=pedantic]
 CAMP_MAKE_L(accumulate);

include/camp/camp.hpp:168:20: error: extra ';' [-Werror=pedantic]
 CAMP_MAKE_L(filter);
s::integer_sequence replaced by VarOps::index_sequence.

### PR DESCRIPTION
**Pull request by trws**
Fixes #343.

### CODE REVIEW

**Comment by tepperly** [comment]
Once in develop, will this migrate to master?

**Comment by davidbeckingsale** [comment]
@trws - can you change this branch to be based on master, and bump the version number to 0.4.1?

We will then merge this change to both develop and master.

**Comment by trws** [comment]
Is that just a change in the release file or are there more places?

**Comment by davidbeckingsale** [comment]
A few places, check out the PR here: 
https://github.com/LLNL/RAJA/pull/342/files

**Comment by trws** [comment]
I see... is there a reason we don't just set it in the project statement in cmake and propagate it to everything else at configuration/packing time?

**Comment by trws** [comment]
Ah, we're actually not setting the CMake version in the first place.  This might be a good thing to have an issue for.

**Comment by trws** [comment]
Either way, this should be set with version number 0.4.1.

**Comment by davidbeckingsale** [comment]
@trws can you open another PR to develop with this change?

**Pull request merged**
