### PR TITLE
[WIP] Switch to regular CMake-only build

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This moves the host-config functionality into CMake, removing the complicated Python script/CMake combination of yesteryear.

Comments appreciated.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
Will get some testing in next week, but looks like really nice work, thanks for putting the time in on this!

**Comment by rhornung67** [comment]
David, I'll take this out for a spin and start reworking the sphinx documentation. Thanks.

**Comment by keasler** [comment]
Is this branch still alive?

**Comment by davidbeckingsale** [comment]
Yes.

**Comment by trws** [comment]
So... Is there a remaining reason not to merge this?

**Comment by DavidPoliakoff** [comment]
I've been merging this into my clones for a while now, I'd support merging it if anybody wants to click the button

**Comment by trws** [comment]
I'm seriously wanting this... Actually wanting to build a couple of portability things on it too.  If there aren't any outstanding issues I'd love to see it go in.

**Comment by DavidPoliakoff** [comment]
Just to bring him in on the conversation: thoughts, @davidbeckingsale ?

**Comment by keasler** [comment]
David, feel free to merge this.  If there are any unintended consequences, we can patch any issues of concern.

**Comment by davidbeckingsale** [comment]
@rhornung67 still wanted to improve the documentation, although from what I've reviewed it's at least as good as what we currently have.

**Comment by trws** [comment]
So, merge and open a docs issue @davidbeckingsale?

**Pull request merged**
