### PR TITLE
Feature/probinso/hip active

### PR DESCRIPTION
**Pull request by robinson96**
# Summary

- This PR is a bugfix
- It does the following:
  - Adds a concept of RAJA_HIP_ACTIVE to allow the inclusion of RAJA headers that were configured with HIP with non HIP compilers.
  - Mirrors the analogous concept of RAJA_CUDA_ACTIVE

### CODE REVIEW

**Review by artv3 — APPROVED** [review]

**Comment by artv3** [comment]
We seem to have hit a correctness issue: 

```
[ RUN      ] Hip/ForallReduceMaxLocMultipleTest/3.ReduceMaxLocMultipleForall
/g/g92/ukbeck/.gitlab-runner/builds/N7JnTGEz/2/gitlab/radiuss/RAJA/test/functional/forall/reduce-multiple-segment/tests/test-forall-segment-multiple-ReduceMaxLoc.hpp:116: Failure
Expected equality of these values:
  current_max
    Which is: -9.71181
  static_cast<DATA_TYPE>(max0.get())
    Which is: -1
```

This is unexpected....

**Comment by artv3** [comment]
Note: HIP 4.1 + clang 9 previously failed the unit test above. -- Trying build again.

**Comment by artv3** [comment]
@robinson96 @rhornung67 This PR initially failed the following test `ReduceMaxLocMultipleForall` but after re-running it we arrived to the correct answer. Do you think it might have been a one-time thing? or should we investigate?

**Comment by rhornung67** [comment]
> @robinson96 @rhornung67 This PR initially failed the following test `ReduceMaxLocMultipleForall` but after re-running it we arrived to the correct answer. Do you think it might have been a one-time thing? or should we investigate?

I've seen this sort of thing before, but it happens infrequently. Let's keep an eye on it and if it keeps happening, we can look into it.

**Comment by rhornung67** [comment]
@artv3 this came back all green. Should we merge, or should we wait for Tom to weigh in?

**Comment by artv3** [comment]
> @artv3 this came back all green. Should we merge, or should we wait for Tom to weigh in?

I think it is probably okay to merge. I don't think the failure would be on account of this PR.

**Comment by rhornung67** [comment]
You may have the honor...

**Pull request merged**
