### PR TITLE
Task/forall view tests

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR adds segment and indexset tests using 1D Views. The segment tests also include offset view tests.
- Some test header files are moved up in the directory structure to make it easier to use exec policies, etc. in multipletest subdirectories.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Not sure what's up with the Travis build though...

**Comment by rhornung67** [comment]
@davidbeckingsale intel build times out at 50 minutes.

**Comment by artv3** [comment]
This looks good, could this go after https://github.com/LLNL/RAJA/pull/789, to enable bounds checking with travis?

**Comment by rhornung67** [comment]
@trws I converted a bunch of tests to use functors instead of lambda expressions. Here is an example of the gist of what I did: 
https://github.com/LLNL/RAJA/pull/793/files#diff-4d7de877c0bc995fbc11d2f94c8e291dR38

The functors are defined in a header file here:
https://github.com/LLNL/RAJA/pull/793/files#diff-590456cdfa49165f04bc0b9d7a325348R1

I didn't see any real drops in compile times when I built the code on the LC with a few different compilers and similar for Travis CI. The Intel build is still running. Hopefully, it will complete.

If these changes are not the sort of thing you had in mind, please let me know.

**Comment by rhornung67** [comment]
@trws Travis CI completed, with Intel build coming in at 48 mins 42 secs. Still too close to 50 minute max limit IM0. I may try backing off on the optimization level for intel and see if that helps. If you have any suggestions for my functor changes, please let me know.

**Comment by rhornung67** [comment]
@mdavis36 that header is used in the indexset-view directory also. The on thing that I find a bit unsavory is the fact that I use the exec policy header file in the scan test PR 
https://github.com/LLNL/RAJA/pull/794.  I'm going to keep plugging away on tests. We'll dole out the next round of test reorg tasks/issues at the meeting next week.

**Pull request merged**
