### PR TITLE
StaticLayout Warning

### PR DESCRIPTION
**Pull request by mdavis36**
# Summary

- This PR is a bugfix to #1033 
- It does the following (modify list as needed):
  - Changes the false return to a 0 to avoid signed/unsigned type warnings.

### CODE REVIEW

**Review by rhornung67 — DISMISSED** [review]
Looks OK to me. Best to have @ajkunen and/or @MrBurmark also review before merging. Thanks @mdavis36

**Review by ajkunen — DISMISSED** [review]
this looks reasonable to me
It will change the default behavior that the 0-index will be treated as stride-one

**Comment by ajkunen** [comment]
maybe, it would be better to change the behavior so that the stride-one dimension defaults to either: 

- num_dims  (which would be one past the right-most dimension, which would be the same behavior as -1)
- num_dims-1  (which would be the right-most dimension, being the same behavior as a C array)

**Comment by mdavis36** [comment]
@rhornung67 After some offline discussion with @ajkunen I think this solution might be more desirable, what do you think?

**Review by rhornung67 — APPROVED** [review]
Works for me if @ajkunen is OK with it.

**Comment by rhornung67** [comment]
@mdavis36 merge this?

**Comment by rhornung67** [comment]
@ajkunen are you OK with merging this?

**Pull request merged**
