### PR TITLE
Try switching to Axom images

### PR DESCRIPTION
**Pull request by davidbeckingsale**
# Summary

- This PR is a refactoring of the Travis CI
- It does the following:
  - Uses images from the `axom/compilers` Docker repository
  - Comments (for now) configurations without a corresponding Axom image

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@trws - any idea on the error in the CUDA build?

**Comment by trws** [comment]
Those errors are the checks for trivial copy ability of the views, but those should be protected by the preprocessor directives I added in to skip those checks.  Is it possible this is on a partial version of that patch set?

**Comment by rhornung67** [comment]
@davidbeckingsale Chris W. is planning to update the Axom compiler images in the next week or two. We should try running the checks on this again after he is done.

**Comment by davidbeckingsale** [comment]
Okay sounds good!

**Comment by davidbeckingsale** [comment]
Superseded by use of rse-ops images.

**Pull request closed without merging**
