### PR TITLE
Feature/rhornung67/perfsuite-blt

### PR DESCRIPTION
**Pull request by rhornung67**
Minor addition to make RAJA CMake macros work with BLT (perf suite-related)

### CODE REVIEW

**Comment by rhornung67** [comment]
@davidbeckingsale the reason that the nvcc build is failing for this PR is that we are using the FindCUDA.cmake in cmake-3.7rc2 which is missing the 'PUBLIC' qualifier in its target_link_libraries macro.  Recall that you added this recently to the FindCUDA.cmake in BLT.  Any thoughts on how to resolve the two?  I tried pulling the BLT FindCUDA.cmake file into RAJA, but that broke other things...

**Comment by davidbeckingsale** [comment]
Did it work?

**Comment by rhornung67** [comment]
Yes, nvcc build and tests passed. This is a temporary fix until we switch over to BLT in RAJA. I wanted to get this in so I can switch the perf suite over to the develop branch and help Adam keep making progress on Kripke.  Should I merge?

**Comment by davidbeckingsale** [comment]
Merged 😄

**Comment by rhornung67** [comment]
Thanks!

**Comment by rhornung67** [comment]
I'll have another PR soon with a complete set of build scripts and host config files for testing with Bamboo on all of our platforms.  Stay tuned!

**Comment by rhornung67** [comment]
BTW,  I looked at several newer versions of CMake on GitHub and none of the included FindCUDA.cmake files contained the 'PUBLIC' thingy. Should you send this fix to them?

**Comment by davidbeckingsale** [comment]
It's only a fix in some situations. If this was added internally to 
FindCUDA you don't add the "PUBLIC" keyword on any explicit 
`target_link_libraries` calls it would break.

**Pull request merged**
