### PR TITLE
Feature/artv3/rename index set

### PR DESCRIPTION
**Pull request by artv3**
I renamed StaticIndexSet to IndexSet. 
The old IndexSet is now SimpleSet, this is mainly for convenience and I can rename it to anything.

### CODE REVIEW

**Comment by willkill07** [comment]
IndexSet was left around only for backward compatibility. Renaming StaticIndexSet to IndexSet is full on API breaking — I personally am against the rename.

I’d just remove the type alias for IndexSet (or at least mark it as deprecated — see usage for RAJA_DEPRECATE_ALIAS)

**Comment by artv3** [comment]
@willkill07 brings up a good point. For those who use the old IndexSet doesn't that mean they would have to go in and add the template arguments? Similar situation with those who use StaticIndexSet, they would have to go in and manually rename.

**Comment by rhornung67** [comment]
@artv3 and @willkill07 we are still not at version 1.0 of RAJA so the understanding of users should be that things are still in flux and we have not yet published an API. The applications that are using RAJA hide the index set stuff behind their own software constructs -- I've checked with them and they don't have a problem with the rename. Also, the typedef has caused issues for some and they have been using the StaticIndexSet directly already. Lastly, the name 'StaticIndexSet' is not a good name IMO -- what's static about it? To be consistent with some of our other names and, to be more clear, it should have been named TypedIndexSet. 

So, I think it's best to do the rename sooner rather than later. @artv3 and I discussed the 'SimpleSet' name that he introduced. I think the tests, indexset builders, etc. are best handled by employing type aliases that are local and specific to their usage.

**Comment by artv3** [comment]
I like the name TypedIndexSet, I think the name reminds the user to specify the template arguments. Can I update IndexSet to TypedIndexSet? I can also make make an alias inside the test to confine SimpleSet there (I can also give a better name).

**Comment by rhornung67** [comment]
@artv3 go ahead and rename to TypedIndexSet. Thanks. Then, you can restore the old Index type alias (i.e., what you renamed to SimpleSet). As @willkill07 suggested, please mark that deprecated with the macro he mentioned.

**Comment by willkill07** [comment]
@rhornung67 sounds good to me. I’m okay with deprecating first, then removing. :+1

**Pull request merged**
