### PR TITLE
Cmake fixes

### PR DESCRIPTION
**Pull request by rhornung67**
This PR updates user guide, CMake stuff, build files to require CMake 3.10 or later. It also updates BLT.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
Can we please roll back the CMake 3.10 requirement and get it changed in camp? @trws

**Comment by rhornung67** [comment]
I would prefer rolling back the min version requirement too.

**Comment by trws** [comment]
Sure.  As I said this morning, the requirement was to support an older version of the cmake setup that I didn't end up using, but I didn't drop it to 3.9 because the camp fork in its own repo originally required something like 3.13, so I can make that change or would be perfectly fine with accepting that change on camp, I just haven't gotten time to do any implementation work yet today. 🙁

Given that the work is already done in here, I admit to being tempted to suggest we keep the uptick or make it 3.11 so we get some of the newer features if we actually have a high enough cmake version elsewhere however.  I assume there's at least one customer where it would be painful to update?

**Comment by trws** [comment]
Tried the online editor to throw in a minimum change in the above linked PR on camp, if travis passes, we can just hit merge to drop camp's requirement to 3.9.

**Comment by rhornung67** [comment]
@trws Sorry, I misinterpreted your comment yesterday. I thought you needed to make 3.10 the min cmake version for camp.  I say we stick with 3.9 min cmake version for now. On LC systems, there is no 3.11 available and 3.12 doesn't work with nvcc. I will amend this PR to remove the doc changes etc. inidicating that cmake 3.10 is the min version, and update the camp submodule.

**Comment by rhornung67** [comment]
@davidbeckingsale @trws @mdavis36 this is good to go. After Tom rolled back the min cmake version requirement in camp, I reverted those changes here including updates of blt and camp submodules.  Please review and approve when you have time.

**Pull request merged**
