### PR TITLE
Switch to camp::resources::Platform

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This PR adds an alias for `camp::resources::Platform` to the `camp_aliases.hpp` header. The previous `RAJA::Platform` enum has been removed from `PolicyBase.hpp`

This PR shouldn't be merged until https://github.com/LLNL/camp/pull/13 is merged.

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@trws - do you think aliasing `Platform` is okay?

**Comment by rhornung67** [comment]
@davidbeckingsale alternatively, you could define policy aliases in the camp_aliases.hpp file. I think the most important thing is to pick an approach that helps maintain consistency across the code.

**Comment by davidbeckingsale** [comment]
This is the least invasive change, and will avoid impacting user code (since users will still get `RAJA::Platform`). Since we are already aliasing things from camp, I thought this approach would be okay.

**Comment by trws** [comment]
Yeah, that seems ok to me.  I'm trying to reduce the amount of that we
have, the rework for the concepts refactor gets rid of most of the
aliasing, but I think this is a case where it's appropriate or at least
appropriate for the forseeable future.

**Pull request merged**
