### PR TITLE
Correct typo in ReduceMaxLoc copy constructor

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
👍 

....oof. But 👍 

[Approved with PullApprove](https://pullapprove.com/LLNL/RAJA/pull-request/146/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=LLNL/RAJA) [Approved with PullApprove](https://pullapprove.com/LLNL/RAJA/pull-request/146/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=LLNL/RAJA)

**Comment by davidbeckingsale** [comment]
Yeah, a real zinger. I'm following up on @trws reduction rework branch, and have converted all operators  - but it took me about 45 minutes to catch this one! I couldn't work out why the object never got copied 🤔

**Comment by rhornung67** [comment]
Yikes! Good catch.  :+1:

**Comment by davidbeckingsale** [comment]
I've merged this, but just FYI @rhornung67 you need to put the 👍  at the start of the line to match the pullaprove regex.

**Comment by rhornung67** [comment]
Sorry about that. I manually approved it on pullapprove.

**Comment by davidbeckingsale** [comment]
No worries!

**Comment by trws** [comment]
Wow... Gotta love c++.  Nice catch @davidbeckingsale!

**Pull request merged**
