### PR TITLE
WIP: Testing SYCL MemoryAccess changes.

### PR DESCRIPTION
**Pull request by rchen20**
# Summary

- This PR is a bugfix
- It does the following:
  - Points CAMP to fork in order to test a fix.
  - Should NOT merge this into develop. Any changes here should be reflected in https://github.com/LLNL/RAJA/pull/1081 instead.

### CODE REVIEW

**Review by rhornung67 — APPROVED** [review]
Hopefully, this will come back green. Fingers crossed!

**Comment by rhornung67** [comment]
@rchen20 more camp sycl compilation failures....:-(

**Comment by rchen20** [comment]
@trws @rhornung67 All of the tests have passed (Travis and AppVeyor hanging for some reason), so we should be ready for another CAMP tag, and an update to https://github.com/LLNL/RAJA/pull/1081. We can close this PR whenever you're ready.

**Comment by rhornung67** [comment]
Thanks @rchen20 I don't know what's wrong with travis. It hasn't been reporting results back to our GitHub space since last week. I think Appveyor is still working and will eventually report.

**Comment by rhornung67** [comment]
@rchen20 please update the RAJA SYCL PR https://github.com/LLNL/RAJA/pull/1081 to point the camp submodule to v0.2.2. This will trigger the CI. Maybe it will come back green by tomorrow morning.  Thanks for your work on this.

**Pull request closed without merging**
