### PR TITLE
[enhancement] Fix operator limits by removing `std::numeric_limits`

### PR DESCRIPTION
**Pull request by willkill07**
`numeric_limits` is great with host-only code, but breaks with GPU code. I hand-rolled limits for all integral types and floating-point types.

* Unsigned Integral types rely on the compiler masking appropriately
* Signed integral types use some bit hack magic -- I tested with numeric_limits before committing
* Floating-point types rely on `cfloat` and `{FLT,DBL,LDBL}_MAX`

I also threw in a fix for a massive warning dump with CUDA 8 on my arch box -- `operator()` within `ForallNPolicy` was not marked `RAJA_SUPPRESS_HD_WARN` (but is now). If this is intentional, I can revert it back.

### CODE REVIEW

**Comment by willkill07** [comment]
Also, do we want to consider adding `--expt-relaxed-constexpr` to CUDA 8 targets? This supposedly gets rid of the aforementioned warnings.

**Comment by davidbeckingsale** [comment]
@willkill07 I don't think we should use the `--expt-relaxed-constexpr` flag if these warnings can be addressed with pragmas. Since this stuff is predominantly in headers, the flag would work for our build, but someone using RAJA without this flag would still get the warning dump.

**Comment by trws** [comment]
So, it's a bit of a PITA, but if the bit twiddling is a worry there's always the option of using SFINAE combined with stdint to get everything from the implementation constants...  Alternatively, we could have a static_assert under an ifdef so it only compiles in host code that compares this with std::numeric_limits if it's enough of a worry.

**Comment by davidbeckingsale** [comment]
That would be good, just some kind of insurance policy against anything weird happening 😄 

@trws what's you opinion on the host-device warnings?

**Comment by trws** [comment]
Still thinking about it.  I prefer solving the warnings wherever practical, and it's making me wonder what the cause is there.

**Comment by willkill07** [comment]
> where was this tested, and where might it break?

I tested on `cab`, my laptop, `rzhasgpu`. Basically x86-64. I did not test under POWER.

The exact check i did was a bunch of `static_assert`s comparing `limit<T>::min()` to `std::numeric_limits<T>::max()`

I'll throw in a macro guard compile-time check for the integral types.

**Comment by willkill07** [comment]
The only two places where the bit hackery would fail is:

1. On architectures with non-power-of-two sized integral types
2. The compiler cannot use `unsigned long long` to perform compile-time constant folding.

**Comment by davidbeckingsale** [comment]
Makes sense, and the asserts look good. Thinking about it some more, we could probably do the check limits stuff as part of the CMake step...

**Comment by willkill07** [comment]
> we could probably do the check limits stuff as part of the CMake step...

Done! Unit test added for compile-time and run-time for all integral types.

**Comment by davidbeckingsale** [comment]
Whoops, I guess I wasn't clear - I meant using the CheckCXXSourceCompiles thing, so we know at "configure" time if the limits are working: https://cmake.org/cmake/help/v3.0/module/CheckCXXSourceCompiles.html

**Comment by willkill07** [comment]
@davidbeckingsale none of the existing files makes sense for me to add to within the `cmake` directory. Should I add a new file which does compiler compatibility checks? Perhaps name is `CompilerCompatibility.cmake`?

**Comment by davidbeckingsale** [comment]
Yeah, that works for me. Thanks!

**Comment by willkill07** [comment]
The irony that the compile-time check doesn't work on travis...

**Comment by willkill07** [comment]
Once travis finishes this should be good to go

**Comment by willkill07** [comment]
Tests pass on my machine with CUDA 8

**Comment by willkill07** [comment]
@trws changes have been made accordingly. If you or someone else could test on manta/ray that would be great -- I only have access to cross compilers for POWER.

**Comment by DavidPoliakoff** [comment]
Confirmed it builds. Any specific tests?

**Comment by trws** [comment]
The unit tests for ForallN almost all exercise that in some way, so it should be gtg.

**Comment by willkill07** [comment]
@DavidPoliakoff I just noticed that the test results you ran were CPU only. Any chance you could also run GPU tests?

**Comment by DavidPoliakoff** [comment]
@willkill07 probably not for a while, in meetings for a bit, but will when time allows

**Comment by willkill07** [comment]
friendly ping @DavidPoliakoff -- btw, I'll be requesting an account on manta/ray when I arrive in ~3 weeks (so I don't need you to do my bidding)

**Comment by davidbeckingsale** [comment]
@willkill07 I'm testing this right now - I had tried earlier which was when I uncovered the bugs fixed by #244 😄

**Comment by willkill07** [comment]
I'll work on this late tomorrow or on Saturday. Thanks for letting me know.

**Comment by davidbeckingsale** [comment]
Yeah no worries, I'll try another compiler tonight to see if it was just a gcc thing.

**Comment by willkill07** [comment]
It cropped up on another test machine of mine -- I'm missing something somewhere :)

**Comment by willkill07** [comment]
@davidbeckingsale I got the tests to pass by removing the extra `RAJA_SUPPRESS_WARN` I added to a few `operator()`. Behavior should be identical to what's on develop. I tested on an x86 CPU + Maxwell GPU. A run on manta/ray would be nice for verification purposes.

**Comment by davidbeckingsale** [comment]
@willkill07 I'll give this a shot today.

**Comment by davidbeckingsale** [comment]
Tests passing, this looks good.

**Pull request merged**
