### PR TITLE
enable address sanitizer on travis for clang debug build

### PR DESCRIPTION
**Pull request by trws**
This should run all of our unit tests under asan, the extra environment variables are necessary to avoid the profiling flags set by gtest causing spurious failures in the leak sanitizer.  This does mean that asan will be unable to detect leaks, but it leaves all of the out-of-bounds and use-after-scope and so-forth tests intact.

### CODE REVIEW

**Comment by trws** [comment]
If an asan check fails, the test will be halted and return a non-zero value, so it will be reported failed by ctest.  The report is part of the error output of the test, so it will be in the usual place where failure output would be reported by the gtest tests.

I'm not sure what the clang4 travis failures are normally about, this particular one is a set of leak sanitizer failures because the environment variables didn't propagate.  I'll fix that then we'll see if it still crops up.

**Comment by rhornung67** [comment]
@trws The kernel test failure is due to an issue with a TBB test. I haven't looked into it.

**Comment by trws** [comment]
After seeing it was TBB I wondered if it would be another privatization thing, but it shouldn't be since every TBB chunk creates its own private version the right way. 

The problem is actually that the `thread_privatize()` overload for kernel doesn't get called in all circumstances where it should be.  The generic non-nested privatizer is being selected as being at least as specific.  This is probably the cause of the region issue where to get parallel region to work the body had to be captured by reference.  In fact, capturing the body by reference in the TBB backend seems to work as a bandaid fix.  For a more generic fix we need to figure out some way to deterministically select the nested version, the trick being that we don't have a negative check we can use in the general case.  I'll have to think on that a bit, but if others are OK with it I'll make that a separate PR.

**Comment by trws** [comment]
Could I get a re-review here? The scope of the PR has creeped somewhat, in that this now fixes the overload selection issue for privatizers, I'm actually somewhat happier with this design too, it's more extensible.  This should make the random TBB and OpenMP kernel test failures go away.

**Pull request merged**
