### PR TITLE
Feature/holger/addget

### PR DESCRIPTION
**Pull request by jonesholger**
Adds a **get** member function to each of the CUDA reduction classes. This is based on #68

### CODE REVIEW

**Comment by review-ninja** [comment]
<a href="https://app.review.ninja/LLNL/RAJA/pull/71" target="_blank">ReviewNinja

**Comment by DavidPoliakoff** [comment]
Sorry for being a pain, but could you add the same methods on the other execution policies? I doubt it would happen, but would hate to see somebody change from cuda to OpenMP and ask why their function no longer works. Otherwise :+1:

**Comment by rhornung67** [comment]
@jonesholger Ditto on @DavidPoliakoff comment about adding the get method to the other reductions. Otherwise, I approve.

**Comment by davidbeckingsale** [comment]
I agree with @rhornung67 and @DavidPoliakoff - add the gets to all reductions before this gets merged.

**Comment by keasler** [comment]
Holger, I like how you implemented this to piggyback off the cast operator.  Thank you for implementing it this way.  In general, it's good if the RAJA functionality can be as transparent as possible with respect to existing serial code.  The only place I feel we really had to compromise this so far has been with the min(), max(), minloc(), and maxloc() methods.  By defining the get method as you did, people who want to stick with their old serial code can still do so.

**Comment by davidbeckingsale** [comment]
As a further comment I don't think this should have been based on #68 - that's a separate feature and hence shouldn't be included in this PR.

Can you update this branch to contain only #526d25d and then update the other reductions (or let someone else do it)?

**Comment by jonesholger** [comment]
@davidbeckingsale I half agree with you since #68 contains a hotfix.  But I can certainly back it out

**Comment by davidbeckingsale** [comment]
Okay, my comment still stands. Let's make sure #68 is okay, merge that, then merge this 'gets' branch separately, based on `develop`.

**Comment by jonesholger** [comment]
Blowing this PR away

**Pull request closed without merging**
