### PR TITLE
[WIP] Enhanced unit testing

### PR DESCRIPTION
**Pull request by davidbeckingsale**
Unit tests are being switched to use Google Test, meaning they integrate properly with CTest, and are also hopefully easier to write!

This branch also removes LULESH and Kripke from the main repository.

### CODE REVIEW

**Comment by rhornung67** [comment]
@davidbeckingsale this PR indicates that 373 files are changed. Is this correct? If so, there doesn't appear to be a way to see all the file differences in github. Also, it looks like there is an errant vim core file added in the top-level directory.

**Comment by DavidPoliakoff** [comment]
We should be sure to time the merges of your PR and mine in a good way. Mind waiting? I'm hacking the timing into the other files as we speak

**Comment by davidbeckingsale** [comment]
I got rid of the core file.

The many changes are because this commit removes LULESH and Kripke too.

**Comment by davidbeckingsale** [comment]
Closing this because it's superseded by #89

**Pull request closed without merging**
