### PR TITLE
Added special cases for cuda atomic Inc and Dec

### PR DESCRIPTION
**Pull request by JohnHynes**
Related issue found here: https://github.com/LLNL/RAJA/issues/1098

This PR adds several special cases to the cuda ``atomicInc`` and ``atomicDec`` functions to significantly boost their performance when there is hardware support from cuda.

### CODE REVIEW

**Comment by JohnHynes** [comment]
@davidbeckingsale Not entirely sure why the gitlab tests are failing, unless it's just a general issue right now. The change should've only affected cuda builds, hmm.

**Comment by davidbeckingsale** [comment]
> @davidbeckingsale Not entirely sure why the gitlab tests are failing, unless it's just a general issue right now. The change should've only affected cuda builds, hmm.

Looks like a timeout. I restarted the jobs.

**Comment by JohnHynes** [comment]
@davidbeckingsale Looks like the tests still failed, took another look and still not entirely sure why.

**Comment by JohnHynes** [comment]
@davidbeckingsale @rhornung67 This one should still be good to go, I'm not sure if anyone was able to take a look at it though.

**Review by davidbeckingsale — APPROVED** [review]

**Comment by JohnHynes** [comment]
@davidbeckingsale I just noticed that this PR is still open 👀

**Comment by MrBurmark** [comment]
@davidbeckingsale @rhornung67 Should we get this merged?

**Comment by rhornung67** [comment]
@MrBurmark let's get the multiple target export issue resolved first https://github.com/LLNL/RAJA/pull/1284 When that PR is good to go, we can get tioga CI PR and this one merged.

**Pull request merged**
