### PR TITLE
add header and namespace for getenv and abort

### PR DESCRIPTION
**Pull request by jeffhammond**
this was previously addressed by https://github.com/LLNL/RAJA/pull/231
but that used the C header.  subsequently, that change was undone.

this fix uses the correct C++ solution, which means `cstdlib` instead of
`stdlib.h` and prepending `getenv` and `abort` with `std::`

### CODE REVIEW

**Comment by jeffhammond** [comment]
This change is *required* to compile RAJA with Intel 18 update 1 (`icpc (ICC) 18.0.0 20170320`) using the default flags RAJA sets.

**Comment by trws** [comment]
@jeffhammond, I'm good with this, it just needed a quick merge.  I put the necessary change on the bugfix/jeffhammond/abort-and-getenv branch if you just want to snag the merge commit over.

**Comment by jeffhammond** [comment]
I'm not sure what "if you just want to snag the merge commit over" means.  Do you need me to do anything to merge?  I have no trouble cherry-picking and such locally, so nothing I'm doing needs the merge.

**Comment by trws** [comment]
All I meant was, I made the changes in the named branch, you can 
cherry-pick the commit from there if you like, or you can merge from 
LLNL/RAJA and move the changes to the new location for the defines 
header.

**Comment by willkill07** [comment]
I performed the merge to bring this up to develop. I also changed the usage of `NULL` to the more appropriate `nullptr`. Once the CI tests pass this should be good to go :shipit:

**Comment by davidbeckingsale** [comment]
Yes, excellent. We can merge this once the tests pass.

**Comment by willkill07** [comment]
@jeffhammond @davidbeckingsale 

The Intel Compiler Travis CI job is currently failing because the compiler does not install :( Otherwise, this branch should be good to go.

**Comment by davidbeckingsale** [comment]
Bummer. I trust you, but we should fix the Intel stuff... Otherwise I have to change the repo settings to be able to merge branches that don't have passing checks.

@jeffhammond do you know of any recent changes in the script or installer that would break this?

**Comment by jeffhammond** [comment]
No.  I don't know any changes here and https://github.com/nemequ/icc-travis/commits/master shows nothing since August 2016.

**Comment by willkill07** [comment]
What's weird is the Intel Compiler has been working just fine on other PRs. Is it possible to merge without the build fully passing? I tested v18 and v17 on quartz to verify it worked.

**Comment by jeffhammond** [comment]
Maybe move icc to xfail in Travis so the must-pass-CI bit is cleared?

**Pull request merged**
