### PR TITLE
File cleanup (see comments)

### PR DESCRIPTION
**Pull request by rhornung67**
Add missing header comments, fix clang-format issue,a few mods to clang-format configuration (braces at beginning of namespace, class, and method scope, indentation of access qualifiers), and changed
getMinLoc/getMaxLoc methods in reductions to getLoc.

### CODE REVIEW

**Comment by jonesholger** [comment]
Thanks for doing this @rhornung67 .  I was contemplating a formatting pass, but with clang-3.8.0, after we got Tom's fix in. 

 Where you refer to shared memory block chunks in reduce_cuda.hxx, I would modify that to global shared memory, or device memory to distinguish that from __shared__

**Comment by rhornung67** [comment]
@jonesholger I will make your suggested change to the comments about the reduction memory blocks and update the PR.  

What's up with the appveyor stuff? I assume we can ignore that since travis builds are passing. I also manually verified builds and tests for all platforms and compilers in our host-configs.

**Comment by jonesholger** [comment]
Looks like the appveyor stuff is tied to testing windows builds??

**Comment by davidbeckingsale** [comment]
👍 this looks good. We should try and figure out what's going on with the Travis builds before merging just to be safe.

**Comment by jonesholger** [comment]
I restarted the build in Travis - sometime it needs a kick.

**Pull request merged**
