### PR TITLE
Add RAJA_LOADED variable

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This will prevent repeated inclusion of RAJA in other projects

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@ajkunen my only question would be whether we want RAJA checking if it's loaded, or leave that up to the app... any thoughts?

**Comment by ajkunen** [comment]
@davidbeckingsale I'm not sure.  

Why is this any different than the BLT check?

Also, one nice thing might be to stash the RAJA version in RAJA_LOADED, and if RAJA_LOADED is set, then ensure that the versions match?!?

**Comment by DavidPoliakoff** [comment]
I'd like to request that RAJA_LOADED works like Adam is pointing out there, an application being able to know if it's using the RAJA it thinks it does sounds broadly useful.

**Comment by davidbeckingsale** [comment]
It's not really. And yes I can implement the version checking.

**Comment by davidbeckingsale** [comment]
How should be deal with commits inbetween versions? e.g. 0.5.1 + a few commits?

**Comment by ajkunen** [comment]
@davidbeckingsale  I wouldn't worry about that.  If you are using a develop version of RAJA you're on your own

**Comment by davidbeckingsale** [comment]
😆

**Comment by davidbeckingsale** [comment]
@ajkunen - added version check

**Comment by davidbeckingsale** [comment]
@ajkunen @rhornung67 Looks like builds are going to pass (I hope!) - can I get a final approval?

**Comment by davidbeckingsale** [comment]
I think I spoke too soon :( I'll figure out what the Appveyor problem is.

**Comment by rhornung67** [comment]
@davidbeckingsale I restarted the travis builds that barfed.

**Comment by davidbeckingsale** [comment]
@cyrush have you seen these AppVeyor failures before? GoogleTest is breaking the build, saying:
```
C:\projects\raja\blt\thirdparty_builtin\googletest-release-1.8.0\googletest\include\gtest/internal/gtest-port.h(998): error C2220: warning treated as error - no 'object' file generated [C:\projects\raja\build\blt\thirdparty_builtin\googletest-release-1.8.0
```

I saw you had commented on BLT about recent appveyor changes, but wasn't sure if this was the same thing.

**Comment by cyrush** [comment]
@davidbeckingsale  doesn't look like the same issue, but problems with cmake 3.10 prevented  from even configuring with MPI on -- so we didn't make it far enough to run into this issue. 

After some time trying to debug, I climbed out of the rabbit hole and I resorted to installing 3.9.6

https://github.com/LLNL/conduit/blob/master/appveyor.yml

(I haven't updated blt testing yet)

**Comment by davidbeckingsale** [comment]
@rhornung67 - can I get an approval to merge this, then I can start the release branch...

**Pull request merged**
