### PR TITLE
[WIP] Azure CI Docs

### PR DESCRIPTION
**Pull request by mdavis36**
# Summary

- This PR is a (refactoring, bugfix, feature, something else)
- It does the following (modify list as needed):
  - Modifies/refactors (class or method) (how?)
  - Fixes (issue number(s))
  - Adds (specific feature) at the request of (project or person)

# Design review (for API changes or additions---delete if unneeded)

On (date), we reviewed this PR.  We discussed the design ideas:

1. First idea or goal
2. Second idea
3. Third idea

This PR implements 1. and 3.  It leaves out 2. for the following reasons

- (impractical)
- (too big)
- (not a good idea anyway)

### CODE REVIEW

**Comment by rhornung67** [comment]
@mdavis36 please put your documentation content in this PR: https://github.com/LLNL/RAJA/pull/1237 so we can keep things together. Thank you.

**Comment by mdavis36** [comment]
> @mdavis36 please put your documentation content in this PR: #1237 so we can keep things together. Thank you.

Yep this points at #1237. I did some cleanup of azure-pipelines.yml so I wanted to launch a CI run before putting this there.

**Comment by rhornung67** [comment]
OK. Thanks.

**Comment by rhornung67** [comment]
@mdavis36 I see you merged in my ci docs branch into this. Is your plan to merge this into develop? Should we add more reviewers to this and close my PR?

**Comment by mdavis36** [comment]
@rhornung67 No the plan is to merge this into your branch / PR. If you're okay with what is here this should be ready to go.

**Review by rhornung67 — APPROVED** [review]
Let's merge this. Then we can merge my branch. I'll make one last request for folks to look it over.....

**Pull request merged**
