### PR TITLE
Correct list segment usage example for API change.

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR is a documentation bugfix. It addresses https://github.com/LLNL/RAJA/issues/995

### CODE REVIEW

**Review by artv3 — DISMISSED** [review]

**Comment by trws** [comment]
This example is surprisingly gnarly for how normal it seems it should be.  I'm guessing we get a compiler failure when doing `TypedListSegment ls(vec, resource)`, probably because we require the difference_type to be the same as the IndexType.  That feels like something we could fix pretty easily as a QOL thing unless there's some reason we need the count type to match the index type.

**Comment by rhornung67** [comment]
@trws let me check on how this works (probably get to it tomorrow morning). The gnarliness could be carryover from earlier list segment implementations. I'll correct/simplify the example as needed.

**Comment by rhornung67** [comment]
Good catch. There doesn't appear to be any required connection between index type and size of container type (or Index_type for that matter). Here's one of our basic tests: https://github.com/LLNL/RAJA/blob/develop/test/functional/forall/segment/tests/test-forall-ListSegment.hpp#L34

**Comment by rhornung67** [comment]
@trws I simplified the example and described the list segment constructor usage we support.

**Review by trws — APPROVED** [review]
Looks good to me, definitely an improvement!

**Comment by rhornung67** [comment]
@trws I'll add an issue to make the segment types consistent with minimal assumptions with respect to the type of the indices, iterators, size() return type, etc.

**Pull request merged**
