### PR TITLE
Remove double RAJA_ in macro.

### PR DESCRIPTION
**Pull request by rchen20**
# Summary

- This PR is a bugfix for https://github.com/LLNL/RAJA/issues/1160

### CODE REVIEW

**Review by trws — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]
Thanks @rchen20

**Review by davidbeckingsale — APPROVED** [review]

**Comment by davidbeckingsale** [comment]
It makes me think of this:

image

**Comment by rhornung67** [comment]
Wow. git blame says that I was the last person to touch those lines (in April 2018!!!).  Mea culpa.

**Comment by rhornung67** [comment]
@rchen20 I'm going to pull this change into the v0.14.1-RC2 branch.

**Pull request merged**
