### PR TITLE
Update nested_loop_reorder.rst

### PR DESCRIPTION
**Pull request by cdwdirect**
Fixed infinite loop in C-style example.

### CODE REVIEW

**Comment by rhornung67** [comment]
@davidbeckingsale I went into travis and all check for this PR passed. It looks like it's stuck reporting status to github. Any ideas?

**Comment by davidbeckingsale** [comment]
I think it is because it's from a fork, not sure how to force it to be reported :(

**Comment by rhornung67** [comment]
We've merged PRs from forks before, no? We can't merge this.

**Comment by davidbeckingsale** [comment]
I think maybe we turned off the guarding and force merged.

**Comment by rhornung67** [comment]
I found this 

https://travis-ci.community/t/known-issue-travis-ci-reports-expected-waiting-for-status-to-be-reported-on-the-github-status-api-but-the-status-never-arrives/1154 

But it doesn't seem to apply here.

**Comment by rhornung67** [comment]
@davidbeckingsale I think you're correct that we force merged.  What a pain.

**Comment by davidbeckingsale** [comment]
Yup, watch this 😎

**Pull request merged**
