### PR TITLE
Fix roctx cmake configuration

### PR DESCRIPTION
**Pull request by artv3**
Looks like there were some changes to cmake that were not propagated to the ROCTX configuration. 
This PR propagates those changes.

### CODE REVIEW

**Review by davidbeckingsale — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]
Good catch @artv3 👍

**Comment by kab163** [comment]
Ah! Those cmake buggers always manage to slip through the cracks lol Thanks for catching this!

**Review by kab163 — APPROVED** [review]

**Comment by artv3** [comment]
No luck getting the gitlab hip test to run, they have been timing out

**Comment by rhornung67** [comment]
@artv3 i merged the latest changes in develop into this PR branch. if you manually verify that this works on rznevada (corona is still down), and all other checks come back green, we can merge this.

**Comment by artv3** [comment]
This PR works, however; after running make test on rznevada I hit the following test errors:

```
	 67 - test-forall-segment-multiple-ReduceMinLoc-Hip.exe (Failed)
	129 - test-kernel-resource-nested-loop-Known-Hip-Failure-MultiLambda-Hip.exe (Failed)
	132 - test-kernel-nested-loop-Known-Hip-Failure-MultiLambda-Hip.exe (Failed)
	196 - test-workgroup-Unordered-Single-Hip.exe (Failed)
	197 - test-workgroup-Unordered-MultipleReuse-Hip.exe (Failed)
	236 - test-algorithm-sort-Hip.exe (Child aborted)
	247 - test-algorithm-util-sort-Known-Hip-Failure-Insertion-Hip.exe (Child aborted)
```

Do we know if these are known failures?

**Comment by rhornung67** [comment]
The tests with 'Known-Hip-Failure' in the name are known to fail. Try running the tests again and see if you get the same failures. Sometimes things fail at times for reasons we are not clear on. @MrBurmark may have thoughts on the workgroup and sort test failures.

**Comment by artv3** [comment]
Less failures this time, but these still came up: 
```
	196 - test-workgroup-Unordered-Single-Hip.exe (Failed)
	197 - test-workgroup-Unordered-MultipleReuse-Hip.exe (Failed)
	236 - test-algorithm-sort-Hip.exe (Child aborted)
```

**Comment by MrBurmark** [comment]
I feel like I've run into these failures before, but I can't remember exactly what was the cause. What rocm version are you using?

**Comment by rhornung67** [comment]
test-forall-segment-multiple-ReduceMinLoc-Hip.exe fails sometimes. we don't understand it. you may want to check with jason on the others.

**Comment by artv3** [comment]
> I feel like I've run into these failures before, but I can't remember exactly what was the cause. What rocm version are you using?

4.5.0

**Comment by MrBurmark** [comment]
I really doubt the changes in this PR are causing any tests to fail.
You may try unloading the rocm module, I discovered that if cmake reconfigures it may pick up different rocm stuff from the module?

**Review by MrBurmark — APPROVED** [review]

**Comment by artv3** [comment]
> I really doubt the changes in this PR are causing any tests to fail. You may try unloading the rocm module. If cmake reconfigures it may pick up a different rocm due to the module.

No luck with the modules. If there no objects I can merge this branch and we can look into it outside of this PR.

**Comment by rhornung67** [comment]
@artv3 i think you can merge this.

**Pull request merged**
