### PR TITLE
Fixed bug in nested::forall CUDA Collapse when using strongly typed indices

### PR DESCRIPTION
**Pull request by ajkunen**
Also, changed a unit test to tickle this issue

### CODE REVIEW

**Comment by rhornung67** [comment]
@ajkunen Travis is failing due to issues not associated with the code. You will have to go in and restart some of the jobs.

**Comment by ajkunen** [comment]
@rhornung67 some of these jobs just keep failing... like the clang-5 one

**Comment by rhornung67** [comment]
@ajkunen I see that. I've been restarting them, but they keep failing. It's all related to issues when downloading the LLVM stuff. @davidbeckingsale changed this recently so that none of this stuff is cached. But, I don't know exactly what he did. However, I've noticed that things are breaking much more frequently since then.  I'll do some poking around and see if I can figure it out.

**Comment by rhornung67** [comment]
@ajkunen when I get back to my office after lunch, I'm going to try a change that may fix this. I'm in a meeting right now and I don't want to start cursing while I'm here.

**Pull request merged**
