### PR TITLE
Artv3/task/tut reorg aws

### PR DESCRIPTION
**Pull request by artv3**
# Summary

Draft tutorial material.

### CODE REVIEW

**Comment by artv3** [comment]
I seem to be hitting a build error with Docker hip: 
#8 103.0 /home/raja/workspace/include/RAJA/util/Layout.hpp:103:15: error: cannot convert 'typename std::enable_if<!std::is_base_of<IndexValueBase, OffsetLayout<2, int>>::value, OffsetLayout<2, int>>::type' (aka 'RAJA::OffsetLayout<2, int>') to 'long' without a conversion operator
#8 103.0       : sizes{static_cast<IdxLin>(stripIndexType(ns))...},
#8 103.0               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by artv3** [comment]
@rhornung67 @mdavis36 I think branch: https://github.com/LLNL/RAJA/pull/1301 might have the same build errors. Would it be okay to merge this in to PR 1301?

**Comment by rhornung67** [comment]
@artv3 @mdavis36 I pushed a fix to the other branch.

**Comment by rhornung67** [comment]
More compilation fixes pushed to other PR branch.

**Comment by artv3** [comment]
I should be up to date now, may I merge if this comes up green?

**Pull request merged**
