### PR TITLE
Remove Cilk support

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
I'm sorry, I can't approve this PR until you write a stirring eulogy for our fallen parallel comrade.

**Comment by davidbeckingsale** [comment]
Here lies Cilk, oft' mentioned, rarely used. RIP.

**Comment by willkill07** [comment]
Looks good to me 👍

**Comment by DavidPoliakoff** [comment]
There's no Viking funeral emoji with which to make :shipit: puns, but there should be. LGTM

**Comment by davidbeckingsale** [comment]
Really, we should raise a glass... 🍻  but I couldn't add that as a reaction.

**Comment by davidbeckingsale** [comment]
Yup, I'll push a PR up there too.

**Comment by jeffhammond** [comment]
@davidbeckingsale You've stolen Cilk's honor with the efficiency that Cilk steals work :neckbeard:

@rhornung67 Brutal. I am totally going to use "your programming model isn't even worthy of a deprecation phase" in the future.

Is somebody working on a PSTL implementation yet?

**Comment by DavidPoliakoff** [comment]
@jeffhammond : in the eternal way of RAJA, it is certainly being discussed, I don't know that anybody is writing code. If anybody is writing code, it's probably @willkill07 , so I'll ping him

**Comment by rhornung67** [comment]
@jeffhammond not clear if you mis-interpreted my comment. It was a poke at @davidbeckingsale (a.k.a. "The Hammer") for taking the axe without mercy.

**Comment by willkill07** [comment]
@jeffhammond I do have a branch on my machine with `forall` and `scan` trivially implemented using PSTL but haven't touched reducers yet. I'm not sure of the best way to approach this problem given that the PSTL has zero mention of such a notion beyond the mentioning of `par_unseq` being an unsafe beast.

We'll definitely support `par` and `seq` (most likely with the `pstl_` prefix (I kind of like pronouncing it pistol). But until reductions are figured out, there won't be a PR for it. I welcome your input and suggestions.

**Comment by jeffhammond** [comment]
I haven't used RAJA reducers yet, so I don't know if `std::reduce`, `std::accumulate`, `std::transform_reduce`, etc. apply.  Presumably, there's a naive implementation that uses `std::atomic`, but it will not perform well on any CPU architecture out there, especially for floating-point types.

We recently had a discussion of the Intel PSTL implementation of reductions, which would benefit from understand how this is used, so if you do anything in that directly, I can start a dialog with the implementers.

**Comment by DavidPoliakoff** [comment]
I actually think that std::reduce couldn't work. If we were guaranteed that it would be

```
forall(....){
   myScalar += myArray[i]
}
```

that would be one thing, we might be able to get clever with the destructor of some reducer object calling std::reduce, but if it's

```
forall(....){
myArray[i] = //stuff
myScalar+= myArray[i]
myArray[i] = //other stuff
}
```

We have no way of generally working there that I can think of. This is just another place where us doing reducer objects is "hurting" us (in exchange for a lot of user convenience).

**Comment by jeffhammond** [comment]
@DavidPoliakoff If you user convenience and have a high tolerance for pain, just use `std::atomic`.  The performance will likely suck, but users will be able to do anything they want.

For what it's worth, I struggle to use parallel reducers, e.g. https://github.com/ParRes/Kernels/blob/master/Cxx11/stencil-vector-raja.cc#L200, although somehow I got it right in https://github.com/ParRes/Kernels/blob/master/Cxx11/transpose-vector-raja.cc#L274.

**Pull request merged**
