### PR TITLE
DO NOT MERGE: Update spack package to test in Gitlab CI…

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR is an update to the RAJA Spack package to make sure it works in our CI before pushing it to the radiuss-spack-config repo, which will eventually get pushed to the Spack repo.

### CODE REVIEW

**Comment by adrienbernede** [comment]
@rhornung67, in RAJA#1391, RAJA local packages moved to radiuss-spack-config so that we can have them evolve coherently with other radiuss local packages.

E.g., this ensures that Umpire, RAJA and CHAI use the same camp and blt package implementation.

Please work with that branch to update RAJA package, as those packages are the ones we want to then push to Spack.


Adrien

**Comment by rhornung67** [comment]
@adrienbernede I was unaware of the process. Thank you for setting me straight. 

The RAJA Spack package was removed in https://github.com/LLNL/RAJA/pull/1391. Should I make my Spack package changes in a PR in the radiuss-spack-config project?

**Comment by davidbeckingsale** [comment]
#1391 isn't merged yet. I think we are starting to get some non-trivial dependencies between PRs, and should decide on an order to merge them all.

**Comment by davidbeckingsale** [comment]
> > #1391 isn't merged yet. I think we are starting to get some non-trivial dependencies between PRs, and should decide on an order to merge them all.
> 
> Yes, I see that. I think the best thing to do is for me to make a PR in radiuss spack configs, first. Then, have Adrien pull that into #1391. When that is merged, we should be in sync as afar as RAJA is concerned. Agree?

Sounds good to me. You will need to make a PR against the woptim/gather-local-packages branch of radiuss-spack-configs: https://github.com/LLNL/radiuss-spack-configs/tree/woptim/gather-local-packages

**Pull request closed without merging**
