### PR TITLE
remove sycl::detail::setQueue and getQueue from codebase

### PR DESCRIPTION
**Pull request by johnbowen42**
remove setQueue and getQueue from codebase, addressing #1658

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@johnbowen42 can you remove the unrelated whitespace changes? it would make this easier to review

**Comment by johnbowen42** [comment]
> @johnbowen42 can you remove the unrelated whitespace changes? it would make this easier to review

sure, but I think that at some point we should remove trailing whitespace from the RAJA codebase

**Comment by davidbeckingsale** [comment]
Agree, we could add a style action like Umpire has

**Review by trws — APPROVED** [review]

**Review by MrBurmark — APPROVED** [review]

**Comment by rhornung67** [comment]
@johnbowen42 sorry I did not get to review this before you merged it. I'm concerned that all the internal places where a queue is needed assumes that the camp default resource/queue is the correct choice. What will happen if a user passes another resource (not the camp default) into a kernel with a RAJA reduction, for example?  I ran into issues with incorrect behavior when adding SYCL variants to RAJA Perf when there was a mis-match between the resource passed to a kernel and what was assumed in RAJA internally.  

We probably need to add tests to check for this sort of thing. For example, run a RAJA reduction test where a non camp default resource is passed into the kernel launch.

**Comment by johnbowen42** [comment]
@rhornung67 Sorry that I merged it without your review.  I will make a new branch with a test of the above, and fix any issues I can identify

**Pull request merged**
