### PR TITLE
Shift existing view

### PR DESCRIPTION
**Pull request by artv3**
@jonesholger , in regards to issue #635 . I added the shift method to RAJA Views. I was wondering if you could take a look and see if this might be what you are looking for?

### CODE REVIEW

**Comment by rhornung67** [comment]
👍

**Comment by jonesholger** [comment]
Hmm, still having issues: 1d and 3d don't compile; 2d compiles ok but address calculation is off, or it's a user/usability issue.

So shifting one double we get:
shift[1,0] comparing address orig 0x2aaab6cce870 orig - manual shift 0x2aaab6cce878 and view shifted 0x2aaab6ccebd0

shift[0,1] comparing address orig 0x2aaab6eca150 orig - manual shift 0x2aaab6eca250 and view shifted 0x2aaab6ecebd0

auto source = get_const_view<2>(src, d);
auto s2 = get_const_view<2>(src,d);
auto s3 = s2.shift({{1}},{{0}});

fprintf(stderr,"shift[%d,%d] comparing address orig %p orig - manual shift %p and view shifted %p \n",1,0,&source(0,0),&source(1,0),&s3(0,0));

I guess I was also expecting s2 to be shifted in place, that is it's offset at s2(0,0) would have been shifted relative to the original address, yet it remains at same as source original address, so I used  s3.

--------------------------------------------------------------------
for compiling:
1d example

auto source = get_const_view<1>(src, d);
ArrayDataOperationUtilities.C:109:10: note:   candidate expects 2 arguments, 1 provided
          source.shift({{-shift_i}});
          ^~~~~~

and similarly for 3d
auto source = get_const_view<3>(src, d);
ArrayDataOperationUtilities.C:136:10: note:   candidate expects 2 arguments, 3 provided
          source.shift({{-shift_i}},{{-shift_j}},{{-shift_k}});

**Comment by artv3** [comment]
@jonesholger, I think I understand what you are trying to do now. Here, the shift method regenerates an offset layout so it requires the lower and upper bounds. It seems like you want to offset the existing lower and upper bounds. I should be able to fix that. Thanks for clarifying, I'll give it another swing.

**Comment by rhornung67** [comment]
@artv3 thanks for digging into this!

**Comment by ajkunen** [comment]
@artv3 can you make sure this works with typed layouts and typed views

**Comment by artv3** [comment]
@jonesholger, I made a second pass and believe I have what you are looking for. Would you kindly give it a spin?

@ajkunen, sure thing currently working on it. I'll push it in when its ready.

**Comment by artv3** [comment]
@ajkunen, @rhornung67 we can make this work for typedviews but we don't currently support TypedOffsetLayouts, is that something we are interested in supporting?

**Comment by artv3** [comment]
I just added the test for typedlayouts. The shift method returns views with offset layouts.

**Comment by jonesholger** [comment]
@artv3 Tested 2d/3d .. awesome!  Thank you very much.

**Comment by artv3** [comment]
@rhornung67, @ajkunen , I added supported for typed offset layouts. Could I kindly get a review?

**Pull request merged**
