### PR TITLE
skip docker login on travis when secret unset

### PR DESCRIPTION
**Pull request by trws**
# Summary

- This PR is a CI bug fix
- It skips docker login when the password is unavailable

NOTE: I'm intentionally making this PR from a fork to test the change.  If travis passes here, we should be good.

### CODE REVIEW

**Comment by rhornung67** [comment]
@trws Please see my recent email about this. I think there is a better alternative than skipping the login.

**Comment by trws** [comment]
Ok, I think we still want something *like* this to handle external PRs.  Travis recommends skipping if the secrets are unavailable, which is what we do with the intel compiler, so perhaps we need to do that with docker as well.  This solution works, but can still cause timeouts on docker (that's why the tests failed this time).  What do you think @rhornung67 @davidbeckingsale ? Don't run the tests at all, or try them and probably run into rate limits?

**Review by rhornung67 — APPROVED** [review]
This works for me. I merged in the latest changes from develop. CI checks are restarting.

**Comment by rhornung67** [comment]
@trws all travis checks fail on this PR. I assume that this is expected since it's a PR from a fork.

**Comment by trws** [comment]
Yup, they're all shortcutting out.  What would actually be best is if this were moved to an in-tree PR as you were advocating to make sure they fail here and pass there.  If both of those things happen, we at least get something workable I think.

**Comment by rhornung67** [comment]
@trws good idea. should i do that or do you want to?

**Comment by trws** [comment]
Why don't you so we can see how things get handled when it's a different user managing the in-tree PR?  Seems like an opportunity for an experiment.

**Comment by rhornung67** [comment]
OK. I have a couple of webexes in a few minutes. Will do this after those.

**Pull request merged**
