### PR TITLE
Fix banner message concerning LULESH domain size.

### PR DESCRIPTION
**Pull request by keasler**

### CODE REVIEW

**Comment by keasler** [comment]
Travis died trying to do a sudo command -- I don't think this bug is mine.

**Comment by DavidPoliakoff** [comment]
Yeah, looks like a bug in our travis :/

**Comment by DavidPoliakoff** [comment]
If only we had something to patch over the problems with apt, some other spackage manager we know about at LLNL. Do you know of any,  @davidbeckingsale ?

**Comment by keasler** [comment]
Since this branch has an utterly trivial change (the variable name used in printf statements), I am going to go ahead and merge it.  I also deprecated a force-inline flag in the host-config for the Intel 17 compiler that was missed.

**Comment by DavidPoliakoff** [comment]
I'll retroactively approve it, just so the git gods don't strike us down :)

**Pull request merged**
