### PR TITLE
Introducing gitlab CI, splitting host-configs, generic build script [feature/gitlab_ci]

### PR DESCRIPTION
**Pull request by adrienbernede**
**This PR is a feature. It does the following:**
  - **Reformat host-config files (split shareable and project specific), rename host-config-files (for use as regex)**
  - **Introduces CI pipeline description for GitLab in LC context** 

This feature aims at introducing a first GitLab CI pipeline designed for the LC GitLab instance.
The additional constraint was to design this pipeline so that we could share as much configuration as possible with other projects.

**This PR is derived from #661, except it was not triggered from a fork, allowing it to be mirrored on Gitlab for demonstration.**

## First Action

The idea is to separate project specific and shareable configuration.

As for now, shareable information mainly consist in toolchain configuration, such as compiler paths, and is placed in the `.gitlab/conf` directory. More generally, the aim is to have .gitlab containing non-project specific gitlab configuration so that it can be easily moved elsewhere later on (submodule).

Project specific configuration, such as compiling flags and target release identification, remains at the same place.

Shareable and project configuration are linked by the directory layout which has been unified : `system_type/toolchain`

## Second Action

The `.gitlab-ci.yml` file is used by GitLab CI as the main configuration file. Using inclusion of files (`include:`) and job properties extensions (`extends:`) the pipeline configuration is split in several places in a modular manner.

`.gitlab-ci.yml` containins project specific configuration of the pipeline.

`.gitlab/ci` contains shareable configuration, such as configuration of jobs for different clusters.

In addition, an allocation mechanism is introduced so that on quartz only one resource allocation is required. Note that this allocation is currently using the pdebug queue.

## Third Action 

Configuration that use to be done at script level (typically omptarget stuff, or CUDA_ARCH) has been moved to the project specific host-config files.

This is possible thanks to a new support for a suffix in host-configs file naming. This allows to tune the configuration for specific use like omptargets. (IMHO, scripts/gitlab/build_and_test.sh could replace the usage of multiple scripts at this stage, which would ease maintenance).

i.e. on LC:
`> CONFIGURATION=clang_coral_2018_08_08__omptarget scripts/gitlab/build_and_test.sh`
Will do the same as, 
`> scripts/lc-builds/blueos_clang-coral-2018.08.08_omptarget.sh`
because all RAJA specific parameters, including those for openmp targets, are now included in
`host-configs/blueos_3_ppc64le_ib/clang_coral_2018_08_08__omptarget.cmake`
and the corresponding toolchain is defined in
`.gitlab/conf/host-configs/blueos_3_ppc64le_ib/clang_coral_2018_08_08`
(which could be exported to radiuss-ci, cf https://github.com/LLNL/Umpire/pull/294)
`> CONFIGURATION=clang_coral_2018_08_08 scripts/gitlab/build_and_test.sh`
will apply the default configuration, as in
`> scripts/lc-builds/blueos_clang-coral-2018.08.08.sh`

Thus, testing a new parameter for this configuration simply requires to duplicate the host-config file, and change the suffix:
`host-configs/blueos_3_ppc64le_ib/clang_coral_2018_08_08__mytest.cmake`
is then callable using:
`> CONFIGURATION=clang_coral_2018_08_08__mytest scripts/gitlab/build_and_test.sh`

## Summary
Host-config files have been split in two parts. The shareable/toolchain configuration, and the project specific configuration which adapts the config to the toolchain. Remaining configuration has been moved from launch scripts to project host-config files.

In this PR, I wrote a script to launch any build (`scripts/gitlab/build_and_test.sh`), using project host-config names as a regex to identify the one matching the selected toolchain.

Lastly, I added the possibility to have several RAJA host-config files matching the same toolchain so that one can easily derive new configuration without the need to duplicate a script.

### CODE REVIEW

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
- Update Gitlab CI with latest targets.
- Add toolchain categories: only most recent compilers are tested on PRs, all toolchains are tested on master.
- Improvements in build_and_test.sh script, and in CI

**Comment by adrienbernede** [comment]
LGTM

**Comment by adrienbernede** [comment]
Pipeline will fail because of some new toolchains build failing. I have to investigate to see why is that.

**Comment by davidbeckingsale** [comment]
@adrienbernede - I think we can close this one right?

**Comment by adrienbernede** [comment]
Closed in favor of #848 and #856.

**Comment by adrienbernede** [comment]
Closed in favor of #848 and #856.

**Pull request closed without merging**
