### PR TITLE
Generalize index type for minloc and maxloc reductions

### PR DESCRIPTION
**Pull request by rfhaque**
@trws : Please take a look

### CODE REVIEW

**Comment by trws** [comment]
I have no issues with this, in fact it's almost exactly what I was thinking of doing, thanks for the PR!

@rhornung67, @davidbeckingsale secondary review?

**Comment by davidbeckingsale** [comment]
Yeah, this looks great, thanks for the PR @rfhaque

**Comment by trws** [comment]
Hm, I pulled the trigger a bit soon it seems, the direct answer to your question is "no, but it helps."  If a user provided, say, a vec3 type with three members and all the arithmetic ops required, then this would work for that type, but tuple doesn't provide those at the moment.

**Comment by rhornung67** [comment]
@trws thanks for the clarification. @rchen20 started working on the multi-dim'l index loc reductions. This will help with that.

**Comment by rchen20** [comment]
These changes help clarify the loc reduction code in general. Because the work to tuple-ize loc reductions is still in its infancy, I suggest acceptance of this PR. Even without the RAJA_DECLARE_INDEX_REDUCER macro, I would have needed to modify most of this code anyway, and the new loc types make everything more readable for my issue. Good work!

**Comment by ajkunen** [comment]
There are a few issues with this PR.
Did it run travis?  
I don't see any record of the testing running.

I cannot build the develop branch anymore with nvcc due to these changes.

There are issues with defaulted template parameters on class partial specializations, and issues with nvcc initializing an object marked __shared__ which is not allowed.

Can we either fix these issues or back out this PR?

**Comment by trws** [comment]
We must have a travis issue, all checks showed green when it merged, but you're right I don't see that they ran.  This should go back through the process, @rfhaque, could you set up a new PR so we can hopefully see what's up?

**Pull request merged**
