### PR TITLE
clangcuda build script and compile fixes

### PR DESCRIPTION
**Pull request by MrBurmark**
Add a build script using the clang upstream compiler for a clang cuda build.
Fix a variety of compile issues found using said clang cuda build.

This compiler does have the same issues seen with a previous clang trunk build.
 - Wrong answers from reducers.
 - Invalid Device function errors in test-kernel

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@MrBurmark - does the build succeed, and fail at runtime, or do the invalid device function errors prevent the `make` finishing?

**Comment by MrBurmark** [comment]
The build (make) does complete, but the cuda reduce and some of the cuda kernel tests fail

**Comment by davidbeckingsale** [comment]
Cool, the reason I ask is because we can probably add a Travis build for this case (to compile but not run).

Do you mind if I take a crack at getting that added to this PR?

**Comment by MrBurmark** [comment]
@davidbeckingsale that would be excellent.

**Comment by davidbeckingsale** [comment]
Working on it 😄

**Comment by davidbeckingsale** [comment]
Added a build using cudatoolkit 9.0 and clang 7 👍

**Comment by rhornung67** [comment]
@davidbeckingsale Did you just approve your own work on this PR? 🥇

**Comment by davidbeckingsale** [comment]
Of course! I give myself a gold star.

**Comment by DavidPoliakoff** [comment]
I can't believe it @davidbeckingsale

**Comment by MrBurmark** [comment]
I just tried that too, but it was grayed out.

**Comment by davidbeckingsale** [comment]
You can't approve your own PR. Since I didn't open this, then I can approve it 😄

**Pull request merged**
