### PR TITLE
Make RAJA::Span public

### PR DESCRIPTION
**Pull request by MrBurmark**
# Summary

- This PR is a refactoring, feature
- It does the following:
  - Refactors RAJA::Span to be more std::span like
  - Fixes The lack of public RAJA::Span
  - Adds easy use of pointers/iterators with container API at the request of future users of RAJA::sort

### CODE REVIEW

**Comment by MrBurmark** [comment]
@ajkunen I changed RangeSegment to use DiffT instead of StorageT for IndexType, which is apparently only used in Kernel to make Spans. Does this break Strongly typed indices, or strongly typed indices with kernel?

**Comment by trws** [comment]
I'm a bit split on this.  To be sure, I think span should be available to users, but I had planned to make its interface work more like the [standardized version](https://en.cppreference.com/w/cpp/container/span) first, and possibly hoist it into camp as part of that.  I think the only real differences (aside from the fact we support non-pointer iterable types) is the slice would be called subspan (could just have both), and the addition of some more interfaces.

Either way I'm good with this happening, with the note that I have reason to want to slightly break the ABI of this type sometime in the near future.  Most things shouldn't care, but if external users depend on some specific details it might cause breakage, do you think that will be a worry for you @MrBurmark?

**Comment by MrBurmark** [comment]
That makes sense to me. I only plan to use it to call sort and scan probably via `RAJA::make_span` so I am not too worried about breakage as long as we alias it in RAJA.

**Comment by trws** [comment]
Ok, if that's all it is you should be all good as long as you're willing to do a recompile when as and if.  👍

**Comment by MrBurmark** [comment]
Next question what is the modulemap stuff?
Should I edit the file because I moved the span header?

**Comment by trws** [comment]
That's there so one can use -fmodules when compiling with clang.  It's going to be deprecated pretty soon, since that version of modules lost, when we get an importable module unit for C++20, but for now it would be good to keep it non-broken.  I wouldn't have thought any of this would break it, but if it's showing span in the wrong place it would be good if you would repair it.

**Comment by MrBurmark** [comment]
Fixed module map, tests pass.

**Comment by rchen20** [comment]
The tests seem fine to me. Good work!

**Comment by MrBurmark** [comment]
Shall I document span, or wait until the interface has stabilized?

**Comment by rhornung67** [comment]
@MrBurmark let's wait on documenting this until @trws decides how he wants to possibly support some of this in camp.

**Comment by trws** [comment]
I'd hit merge on this right now, but @rhornung67 do you want to hold off based on the request for waiting on tests?

**Comment by rhornung67** [comment]
@trws we should have all the test stuff merged into develop today or tomorrow. I spoke to @MrBurmark yesterday and he said he was fine with waiting a couple of days.

**Comment by trws** [comment]
Sounds good, I also have no issue waiting. Thanks!

**Comment by MrBurmark** [comment]
Merged develop, moved the span test to utils.

**Pull request merged**
