### PR TITLE
Add link to Gitter

### PR DESCRIPTION
**Pull request by davidbeckingsale**

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
Looks good to me, simple docfix, just links to the gitter chat

**Comment by ajkunen** [comment]
Ohh, so this is like twitter for github?

**Comment by DavidPoliakoff** [comment]
More of a chat channel, if somebody has questions about the software they can be answered quickly. Though yeah, the right hand side is essentially a feed

**Comment by davidbeckingsale** [comment]
Yup, pretty much a chat channel. It would be good to have a couple of us there just idling as a way to help out anyone who might have build issues or quick questions about RAJA.

**Pull request merged**
