### PR TITLE
Fix CUDA tests to align with CAMP resource default Device memory.

### PR DESCRIPTION
**Pull request by rchen20**
# Summary

- This PR is a refactoring
- It does the following:
  - CAMP https://github.com/LLNL/camp/pull/73 makes the resource default to Device allocations. This PR fixes the atomic-ref tests to use Device memory, and temporarily uses Managed memory to shore up the WorkGroup and Sort tests.
  - Updates CAMP to v0.2.1.

### CODE REVIEW

**Comment by rhornung67** [comment]
@rchen20 it looks like the git submodule on this branch points to SHA-1 hash 8e6f5a5, which is dated June 8. Shouldn't the campr PR #73 branch be pulled in?

**Comment by rhornung67** [comment]
@rchen20 to make it easier to test this (it doesn't compile as is), I suggest pulling Tom's PR fork branch into the camp repo and then update the camp submodule here to point to that. Here's how:

cd tpl/camp
git checkout master
git fetch origin pull/73/head:pr-from-fork/73 && git checkout pr-from-fork/73
git push https://github.com/llnl/camp pr-from-fork/73

**Comment by rhornung67** [comment]
@rchen20 I merged RAJA develop into this and updated the camp submodule to the v0.2.0 release. If testing comes back green, this should be good to merge.

**Review by rhornung67 — APPROVED** [review]

**Comment by rchen20** [comment]
> @rchen20 I merged RAJA develop into this and updated the camp submodule to the v0.2.0 release. If testing comes back green, this should be good to merge.

Thanks, I need to undo the pointing to the Camp fork, so I'm going to revert the last few commits and redo your last two.

**Comment by rchen20** [comment]
@rhornung67 I'll merge this into RAJA develop after https://github.com/LLNL/camp/pull/76 is merged into CAMP/master. Before merging this PR, the `.gitmodules` file needs to be changed to point to the correct CAMP repo (not a fork), so I'll do that to make sure everything is correct.

**Comment by rhornung67** [comment]
https://github.com/LLNL/camp/pull/76 is good to go, just needs approvals. Please add folks for review.

**Comment by rchen20** [comment]
@rhornung67 @MrBurmark Would you mind re-approving when you get a chance? Thanks!

Still not sure why the Travis CI is "waiting for status to be reported" when all of the tests have passed . . .

**Review by MrBurmark — APPROVED** [review]

**Review by rhornung67 — APPROVED** [review]
Don't know what's up with travis. If all tests pass, I say we merge this without waiting for it to report.

**Pull request merged**
