### PR TITLE
Merge pull request #1 from LLNL/develop

### PR DESCRIPTION
**Pull request by rfhaque**
Merge pull request #549 from rfhaque/develop

### CODE REVIEW

**Comment by davidbeckingsale** [comment]
@rfhaque @trws - this should run the tests correctly now.

**Comment by trws** [comment]
I'm good with it assuming the tests pass after the merge back in from develop.  Thanks again for putting this together @rfhaque, and helping us find a CI bug too. 😄

**Comment by rfhaque** [comment]
Can we please merge this PR?

**Comment by rhornung67** [comment]
@rchen20 @davidbeckingsale @MrBurmark can this PR be closed now that we have support in RAJA for min/max loc reductions where loc can be a tuple of indices?

**Comment by rchen20** [comment]
@rhornung67 Yes, this has been merged in another PR (branch since deleted).

**Comment by rhornung67** [comment]
Closing since the capability was merged in another PR.

**Pull request closed without merging**
