### PR TITLE
reporting bug with reducers (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by artv3**
I think I found the issue. Stay tuned for Travis reports.....

### CODE REVIEW

**Comment by artv3** [comment]
@ajkunen , @rhornung67  , it looks like if we have more than one type of reducer we run into a stalling issue with gcc-6. This branch was just made from develop.

**Comment by artv3** [comment]
It also seems it is the ReduceMinLoc and ReduceMaxLoc that are the problem, not so much the ReduceSum variables.

**Comment by davidbeckingsale** [comment]
Can this be closed? @artv3

**Comment by artv3** [comment]
Yup! This doesn't happen with the new kernel framework.

**Pull request closed without merging**
