### PR TITLE
fixing librt detecton for gettime timer

### PR DESCRIPTION
**Pull request by trws**
Fixes the '-DRAJA_TIMER=gettime' build.

@rhornung67, @keasler, does this version work for you?

### CODE REVIEW

**Comment by keasler** [comment]
I approve.  Thanks.

**Comment by rhornung67** [comment]
It looks like it should work, but I can't see your branch to try it.

**Comment by DavidPoliakoff** [comment]
@rhornung67 : the process Tom is using is that he has a "fork" of the git repo. None of his branches show up here, they show up on his copy of the repo. To get his copy you need to pull from his repo

```
git remote add trws https://github.com/trws/RAJA
git fetch trws gettime-fix
git checkout -b trws/gettime-fix
```

Should do it, though I haven't tested that exact sequence. @trws , right sequence of commands?

**Comment by trws** [comment]
That's odd... It won't let you fetch the branch from my fork? All you 
should need to get it is to run these two commands:

```
git remote add tom https://github.com/trws/RAJA
git fetch tom
```

**Comment by trws** [comment]
Yup, thanks @DavidPoliakoff, beat me to it. =)

**Comment by davidbeckingsale** [comment]
Any objections to merging this PR?

**Comment by keasler** [comment]
Please merge.

**Pull request merged**
