### PR TITLE
Adding Missing Associated Element/Index Types to Multiply ET Templates

### PR DESCRIPTION
**Pull request by braxtoncuneo**
This pull request adds the associated types `element_type` and `index_type` to TensorMultiply and TensorMultiplyAdd.

These types are necessary for the use of operations such as TensorDivide, which access them as part of their implementation. 

The absence of these associated types resulted in compilation errors when attempting to use such operations with TensorMultiply/TensorMultiplyAdd as operands (https://github.com/LLNL/RAJA/issues/1303#issue-1317442775).

Given that this PR simply adds in associated types, it is unlikely to create any unforeseen side-effects. After all, if any code previously intended to use these types, it would have failed to compile.

### CODE REVIEW

**Comment by braxtoncuneo** [comment]
This latest version includes `element_type` and `index_type` declarations in BinaryOperator as well.

**Review by rhornung67 — APPROVED** [review]
Is this the last of the vectorization PRs to get in before the release?

**Comment by rchen20** [comment]
Yes, let's cut it off here. I'll add more testing and cleanup after the release in here https://github.com/LLNL/RAJA/pull/1289.

**Review by MrBurmark — APPROVED** [review]

**Comment by rchen20** [comment]
> Does this have the camp update and warning fixes?
> Update: yes, let's merge and release.

It has everything in Camp up to October 7th. Is that enough?

**Comment by MrBurmark** [comment]
Ya, that should be the latest commit to main.

**Comment by rhornung67** [comment]
@rchen20 I restarted timed out Gitlab CI jobs and it is all green now. Do you want to merge?

**Pull request merged**
