### PR TITLE
Add service user account for Gitlab CI

### PR DESCRIPTION
**Pull request by rhornung67**
# Summary

- This PR switches GitLab CI to run as service user account "rajasa"
- This should give everyone on the team access to interact with GitLab CI runners, restart jobs, etc.

### CODE REVIEW

**Review by artv3 — APPROVED** [review]

**Review by MrBurmark — APPROVED** [review]

**Comment by rhornung67** [comment]
@adrienbernede I put up this PR to use the 'rajasa' service user account in the CI (I put in softlinks from the service user home directory into workspace, etc. The GitLab CI checks didn't run because it thinks it's a draft PR. What did I miss?

**Comment by adrienbernede** [comment]
@rhornung67 when you opened the PR, it likely was a draft, wasn’t it?
Switching it to a regular PR will not trigger the CI: GitLab will not see any change. Only the subsequent commits will trigger a pipeline.
To get the test running, I triggered a pipeline for that branch in GitLab directly. This always skips the draft verification step.

**Comment by rhornung67** [comment]
@adrienbernede thanks for restarting. tioga CI passed, but lassen and ruby die in resource allocation stage. It looks like there is an access issue with the service user account. I will look into this this afternoon in between meetings.

**Comment by adrienbernede** [comment]
Now for the allocation failures:
```
salloc: error: Job submit/allocate failed: Invalid account or account/partition combination specified
```
-> My bet is on rajasa not having access to `pdebug` yet.
```
You do not have a default group (bank).
Please specify a bank with -G option or contact your computer coordinator to request a bank.
```
-> Another "classic": no default bank set for rajasa.

**Pull request merged**
