### PR TITLE
Add check for GCC version

### PR DESCRIPTION
**Pull request by davidbeckingsale**
RAJA doesn't work with GCC 4.8 and lower. Since this isn't a configuration we are actively using, I thought it best to just error in the CMake code, rather than break at build time.

### CODE REVIEW

**Comment by rhornung67** [comment]
@davidbeckingsale forcing GCC 4.8 and higher is fine. I don't foresee the need to support anything older.

**Comment by davidbeckingsale** [comment]
Okay great.

We can also add similar checks for each compiler we want to support.
I'm not sure what the minimum Clang or Intel versions we want are 
though. @trws?

**Comment by trws** [comment]
I think I recall clang 3.4 is as low as we can go, but the bigger issue is if clang is pulling in too old a libstdc++.  Maybe check the clang version and have a small test that uses the chrono API or something and see if it builds?

**Comment by davidbeckingsale** [comment]
Good suggestion. I'll merge this and then start a larger PR with those tests. A libstdc++ check for Intel is probably a good idea too.

Any objections?

**Comment by trws** [comment]
None.  Only note is I would just have the compile test run for every compiler, it might catch some weird clang or gcc configuration we didn't know would break.

**Comment by rhornung67** [comment]
@davidbeckingsale FWIW, there is infrastructure in BLT for verifying correctness of TPL builds and other things. It may be useful for compiler support checks, etc.

**Pull request merged**
