### PR TITLE
Merge release/0.2.1 to develop

### PR DESCRIPTION
**Pull request by davidbeckingsale**
This keeps our develop branch up to date with the changes made in the release branch - e.g. version numbers.

### CODE REVIEW

**Comment by DavidPoliakoff** [comment]
👍 (Just assuming this mirrors #158)

**Comment by DavidPoliakoff** [comment]
(We should also just assume an approval for something like that other PR is approval for this kind of PR, save us on 👍 budget)

**Comment by davidbeckingsale** [comment]
It does, but note that the only changes are the things specific to v0.2.1 (version number changes and some small textual changes in comments)

**Comment by davidbeckingsale** [comment]
Agree, I wonder if we can tie them together some how. Just making a reference I guess.

**Comment by rhornung67** [comment]
To me it makes most sense to merge the release branch into master, tag that, then merge master into develop. Or is this what you're doing and I'm confused?

**Comment by davidbeckingsale** [comment]
That's not what I meant, but merging the release branch to develop accomplishes the same thing and has an obvious motivation behind it. Consider "Merge release branch to deveolp" vs. "Merge master to develop because we merged a release to master" :)

**Comment by davidbeckingsale** [comment]
By "obvious motivation" I mean the commit log more accurately reflects what happened.

**Comment by rhornung67** [comment]
Interesting take. I would prefer that topic branches never interact with master. Also, hotfix branches may need to be done off master occasionally to fix an issue in a release. If we always merge master into develop after a change to master the same simple process covers all cases. If written all these cases in the dev guide on my branch if you want to see what I'm thinking.

**Comment by davidbeckingsale** [comment]
It's not a topic branch, it's a release branch. And yeah, hotfix branches get merged to master, but also to develop. This stuff is all mapped out in http://nvie.com/posts/a-successful-git-branching-model/ which is what I thought we agreed on. I guess I didn't realize the dev guide differed from this.

**Comment by davidbeckingsale** [comment]
image

**Comment by rhornung67** [comment]
@davidbeckingsale I understand this branching model, which is basically Gitflow. This is what I recommend and is what I have described in the dev guide (I'll finish cleaning this up so we can upload it soon). 

I think we are aiming for the same basic development and release processes. To be clear, here's how I think releases should work (this is essentially what you have done, except I think fewer merge steps and always following the same merge pattern is preferable):

When a release is ready, a release branch is created off of develop to finalize the release. Creating a release branch starts the next release cycle on develop. At that point, new work can start on topic branches (off develop) for the next release. Only changes required to complete the release are added to a release branch (documentation, release notes, bug fixes, etc). When the release branch is ready, it is merged into master and master is tagged with a new version number. Finally, master is merged back into develop since it may have changed since the release was initiated (e.g., hotfixes may have been merged in). 

So, key points:

1. Master versions record the release history of the project.
2. Merging a release branch or hotfix branch into master is followed by tagging master with a new version (increment the major, minor, or patch number appropriately).
3. A change to master is always followed by a merge of master back into develop.
4. Hotfix branches are the only branches created off of master.
5. All other topic branches (features, bugfixes, etc.)  are created off of develop and only interact with develop.

**Pull request merged**
